# For documentation on this file format, see chord_sb2_et.yml, and the tex notes.

zone_nfreq: [16384]
zone_freq_edges: [400, 800]
time_sample_ms: 1.0

dtype: float16
beams_per_gpu: 250
time_samples_per_chunk: 2048

# pirate_frb make_subbands 400 800 0.3 -r 4
frequency_subband_counts: [0,0,1,2,1]

# GPU configuration.
max_gpu_clag: 3
beams_per_batch: 2
num_active_batches: 2

# Dedispersion tree configuration follows.
toplevel_tree_rank: 15

primary_trees:
  - {num_early_triggers: 0, max_width: 32, dm_downsampling: 0, time_downsampling: 0, wt_dm_downsampling: 64, wt_time_downsampling: 64}
  - {num_early_triggers: 0, max_width: 16, dm_downsampling: 0, time_downsampling: 0, wt_dm_downsampling: 64, wt_time_downsampling: 64}
  - {num_early_triggers: 0, max_width:  8, dm_downsampling: 0, time_downsampling: 0, wt_dm_downsampling: 64, wt_time_downsampling: 64}
  - {num_early_triggers: 0, max_width:  4, dm_downsampling: 0, time_downsampling: 0, wt_dm_downsampling: 64, wt_time_downsampling: 64}

# No early triggers, so we allow WriteFiles to extend ~5K samples into the future, in case padding is desired.
future_write_max_samples: 5000
