# Subscale "toy" dedisperser, sometimes convenient for testing.
# Does not need production_kernels=True in makefile_helper.py (unlike the chime/chord files in this directory).
# For documentation on this file format, see chord_sb2_et.yml, and the tex notes.

# Overrideable params: frequency channels, time sample length, number of beams.
zone_nfreq: [640]
zone_freq_edges: [400, 800]
time_sample_ms: 1.0
beams_per_gpu: 16

# Non-overrideable params start here.
dtype: float32
time_samples_per_chunk: 256

frequency_subband_counts: [2,2,1]

# GPU configuration.
max_gpu_clag: 1
beams_per_batch: 2
num_active_batches: 2

# Dedispersion tree configuration follows.
# FIXME: max_width=32 doesn't currently work with "toy-sized" kernels.
# (It does work with "production-sized" kernels.)

toplevel_tree_rank: 12

primary_trees:
  - {num_early_triggers: 0, max_width: 16, dm_downsampling: 0, time_downsampling: 0, wt_dm_downsampling: 16, wt_time_downsampling: 16}
  - {num_early_triggers: 1, max_width:  8, dm_downsampling: 0, time_downsampling: 0, wt_dm_downsampling: 16, wt_time_downsampling: 16}
  - {num_early_triggers: 2, max_width:  4, dm_downsampling: 0, time_downsampling: 0, wt_dm_downsampling: 16, wt_time_downsampling: 16}

# In this config, early triggers may extend 12*1024 samples into the future.
# We add an extra ~2K samples, in case padding is desired.

future_write_max_samples: 14000
