// To debug an autogenerated kernel:
//
//  - Copy an autogenerated .cu file to debug.cu (overwriting)
//  - Modify debug.cu to rename __globals__ (to avoid name collisions) and specify k.debug=true
//  - This allows the debug.cu kernels to take precedence over the autogenerated kernels
//  - Note also that debug.cu is not deleted by 'make clean'.


