# For use with 'python -m pirate_frb hwtest'.
# See cf00_all.yml for full syntax.

ssd_dirs: [ '/scratch', '/scratch2/scratch' ]
ssd_devices: [ '/dev/nvme0n1p2', '/dev/nvme1n1p3' ]
write_threads_per_ssd: 8
write_asdf: true


dedisperse: false
ip_addrs: [ ]
downsampling_threads_per_cpu: 0
h2g_bw: false
g2h_bw: false
gmem_bw: false
hmem_bw: false
