#include "../include/pirate/DedispersionTree.hpp"
#include "../include/pirate/CoalescedDdKernel2.hpp"  // get_registry_dcore()
#include "../include/pirate/YamlFile.hpp"
#include "../include/pirate/inlines.hpp"  // pow2(), xdiv(), is_power_of_two()
#include "../include/pirate/utils.hpp"    // integer_log2()

#include <sstream>
#include <ksgpu/xassert.hpp>
#include <yaml-cpp/emitter.h>

using namespace std;
using namespace ksgpu;

namespace pirate {
#if 0
}  // editor auto-indent
#endif


// -------------------------------------------------------------------------------------------
//
// Constructor.


// Note: assumes config.validate() has been called (DedispersionPlan's constructor calls it,
// and DedispersionConfig::from_yaml() calls it). Several asserts below -- in particular the
// power-of-two checks on the peak-finding downsampling factors -- are only meaningful for a
// validated config.
DedispersionTree::DedispersionTree(const DedispersionConfig &config, long itree,
                                   bool Dcore_from_cdd2_registry)
{
    long ipri, et_level;
    config.locate_dedispersion_tree(itree, &ipri, &et_level);

    // Note that stage1_dd_rank can be different for downsampled trees vs the
    // non-downsampled tree, but is the same for different downsampled trees.
    // This property is necessary in order for the LaggedDownsampler to work later.

    int primary_tree_rank = ipri ? (config.toplevel_tree_rank - 1) : config.toplevel_tree_rank;
    int st1_dd_rank = (primary_tree_rank / 2);
    int st1_amb_rank = (primary_tree_rank - st1_dd_rank);

    this->primary_tree_index = ipri;
    this->early_trigger_level = et_level;
    this->amb_rank = st1_dd_rank;              // note amb <-> dd swap
    this->dd_rank = st1_amb_rank - et_level;   // note amb <-> dd swap
    this->nt_ds = xdiv(config.time_samples_per_chunk, pow2(ipri));

    xassert_ge(this->dd_rank, 1);

    long tot_rank = this->total_rank();
    long dd_rank1 = (this->dd_rank + 1) / 2;   // the GPU kernel's second-stage rank

    // Frequency range searched by tree, accounting for early trigger.
    long dmax = pow2(config.toplevel_tree_rank - et_level);
    double fmin = config.delay_to_frequency(dmax);
    double fmax = config.zone_freq_edges.back();

    // Restrict the config's subband_counts to this tree (accounts for early triggering).
    // The result can have pf_rank < dd_rank1: an early trigger drops subband levels, and
    // nothing puts them back. The kernel folds the difference K = dd_rank1 - pf_rank into
    // its argmax tokens -- see xdm_rank() and CoalescedDdKernel2.hpp.
    vector<long> sc = FrequencySubbands::restrict_subband_counts(config.frequency_subband_counts, et_level);
    this->frequency_subbands = FrequencySubbands(sc, fmin, fmax);

    this->pf = config.primary_trees.at(ipri);

    // NOT pow2(pf_rank): the coarse-grained DM axis is one DM per warp of the kernel's
    // second dedispersion stage, whatever the subbands turn out to be. Pinning it to
    // pow2(dd_rank1) is what holds ndm_out -- and every output array shape -- fixed as
    // pf_rank drops. It is also what makes xdm_rank() recoverable from the tree.
    //
    // Unconditional: config.validate() requires the config's value to be 0.
    this->pf.dm_downsampling = pow2(dd_rank1);

    if (this->pf.time_downsampling == 0)
        this->pf.time_downsampling = this->pf.dm_downsampling;

    // All four downsampling factors are now powers of two: the wt factors and any
    // explicitly-set dm/time factors are checked by config.validate(); the dm/time factors
    // left at 0 (which validate() leaves unchecked) are pow2() by the auto-fill just above.
    // Assert all four here -- where the resolved values are first established and much
    // downstream code assumes the property.
    xassert(is_power_of_two(this->pf.dm_downsampling));
    xassert(is_power_of_two(this->pf.time_downsampling));
    xassert(is_power_of_two(this->pf.wt_dm_downsampling));
    xassert(is_power_of_two(this->pf.wt_time_downsampling));

    xassert_le(this->pf.dm_downsampling, this->pf.wt_dm_downsampling);
    xassert_le(this->pf.wt_dm_downsampling, pow2(tot_rank));
    xassert_le(this->pf.time_downsampling, this->pf.wt_time_downsampling);
    xassert_le(this->pf.wt_time_downsampling, this->nt_ds);

    this->nprofiles = 1 + 3 * integer_log2(this->pf.max_width);
    this->ndm_out = xdiv(pow2(tot_rank), this->pf.dm_downsampling);
    this->ndm_wt = xdiv(pow2(tot_rank), this->pf.wt_dm_downsampling);
    this->nt_out = xdiv(this->nt_ds, this->pf.time_downsampling);
    this->nt_wt = xdiv(this->nt_ds, this->pf.wt_time_downsampling);

    // Dcore (the peak-finder's internal time-downsampling factor, which sets the time
    // granularity of out_argmax tokens) is a compile-time property of the autogenerated cdd2
    // kernel -- a registry value, not derivable from the config. If Dcore_from_cdd2_registry
    // is set, a missing kernel throws (via get_registry_dcore()). Otherwise a placeholder is
    // assigned: such a tree cannot be used in a GpuDedisperser, so tokens can only come from
    // a ReferenceDedisperser, whose historical convention is Dcore = time_downsampling
    // (= Dout).
    //
    // Note this query needs the (nearly complete) tree, which is why it is last.
    this->Dcore = Dcore_from_cdd2_registry
        ? CoalescedDdKernel2::get_registry_dcore(config.dtype, *this)
        : this->pf.time_downsampling;

    double dm0 = config.dm_per_unit_delay() * pow2(config.toplevel_tree_rank);
    this->dm_min = dm0 * ((ipri > 0) ? pow2(ipri-1) : 0);
    this->dm_max = dm0 * pow2(ipri);
    this->trigger_frequency = fmin;
}


// -------------------------------------------------------------------------------------------
//
// Derived quantities. See the doc-comments in DedispersionTree.hpp.


// Number of toplevel tree-freq channels spanned by one coarse-freq channel of 'tree'.
//
// This is the same for every tree of a config, including early-trigger trees: the early
// trigger removes exactly as many subband levels as it removes tree rank (see
// FrequencySubbands::restrict_subband_counts), so the channel width never moves. The
// computation below deliberately does NOT rely on that -- it uses only the tree's own
// members, so it stays correct for a tree considered on its own.
static long _toplevel_channels_per_coarse_channel(const DedispersionTree &tree)
{
    // Rank of the underlying dedispersion, i.e. this tree searches the low 2^rr of the
    // toplevel band. (Early triggers restrict the search to a prefix; time-downsampling
    // leaves the freq axis alone.)
    long rr = tree.toplevel_tree_rank() - tree.early_trigger_level;
    return pow2(rr - tree.frequency_subbands.pf_rank);
}


long DedispersionTree::n_to_toplevel_flo(long n) const
{
    return this->frequency_subbands.n_to_flo.at(n) * _toplevel_channels_per_coarse_channel(*this);
}


long DedispersionTree::n_to_toplevel_fhi(long n) const
{
    return this->frequency_subbands.n_to_fhi.at(n) * _toplevel_channels_per_coarse_channel(*this);
}


long DedispersionTree::xdm_rank() const
{
    // The constructor pins pf.dm_downsampling = pow2(dd_rank1).
    return integer_log2(this->pf.dm_downsampling) - this->frequency_subbands.pf_rank;
}


// -------------------------------------------------------------------------------------------
//
// check_consistency(). See the doc-comment in DedispersionTree.hpp.


void DedispersionTree::check_consistency(const DedispersionConfig &config) const
{
    const string where = "DedispersionTree::check_consistency";

    long itree = config.dedispersion_tree_index(this->primary_tree_index,
                                                this->early_trigger_level);
    DedispersionTree ref(config, itree, /*Dcore_from_cdd2_registry=*/ false);

    // Context prefix, so a failure names WHICH tree without the caller having to.
    stringstream ctx;
    ctx << where << ": tree " << itree << " (primary_tree_index=" << this->primary_tree_index
        << ", early_trigger_level=" << this->early_trigger_level << "): ";

    auto cmp = [&](const char *name, long got, long expected) {
        if (got == expected)
            return;
        stringstream ss;
        ss << ctx.str() << name << " is " << got << " from the deserialized tree but "
           << expected << " when rebuilt from the config. The config and the tree describe"
           " different instruments -- most likely the producer and this process are running"
           " pirate_frb builds whose dedispersion-tree geometry differs, or mismatched"
           " config/plan yamls were sent.";
        throw runtime_error(ss.str());
    };

    cmp("amb_rank", this->amb_rank, ref.amb_rank);
    cmp("dd_rank", this->dd_rank, ref.dd_rank);
    cmp("nt_ds", this->nt_ds, ref.nt_ds);
    cmp("nprofiles", this->nprofiles, ref.nprofiles);
    cmp("ndm_out", this->ndm_out, ref.ndm_out);
    cmp("ndm_wt", this->ndm_wt, ref.ndm_wt);
    cmp("nt_out", this->nt_out, ref.nt_out);
    cmp("nt_wt", this->nt_wt, ref.nt_wt);

    // The peak-finding factors. Note {dm,time}_downsampling may be 0 in the config and are
    // auto-filled by the tree constructor, so this is where a change to that rule surfaces.
    cmp("pf.max_width", this->pf.max_width, ref.pf.max_width);
    cmp("pf.dm_downsampling", this->pf.dm_downsampling, ref.pf.dm_downsampling);
    cmp("pf.time_downsampling", this->pf.time_downsampling, ref.pf.time_downsampling);
    cmp("pf.wt_dm_downsampling", this->pf.wt_dm_downsampling, ref.pf.wt_dm_downsampling);
    cmp("pf.wt_time_downsampling", this->pf.wt_time_downsampling, ref.pf.wt_time_downsampling);

    // The tree's RESTRICTED subband counts: restrict_subband_counts() is the most intricate
    // derivation in the tree, and drift in it would silently reinterpret every subband.
    // (The FrequencySubbands tables derived from these are deliberately not compared -- both
    // sides rebuild them from the counts with the same code.)
    const vector<long> &sc = this->frequency_subbands.subband_counts;
    const vector<long> &sc_ref = ref.frequency_subbands.subband_counts;

    if (sc != sc_ref) {
        auto str = [](const vector<long> &v) {
            stringstream ss;
            ss << "[";
            for (size_t i = 0; i < v.size(); i++)
                ss << (i ? ", " : "") << v[i];
            ss << "]";
            return ss.str();
        };
        stringstream ss;
        ss << ctx.str() << "frequency_subband_counts are " << str(sc) << " from the"
           " deserialized tree but " << str(sc_ref) << " when rebuilt from the config"
           " (FrequencySubbands::restrict_subband_counts of the config's toplevel counts)."
           " The config and the tree describe different instruments -- most likely the"
           " producer and this process are running pirate_frb builds whose subband"
           " restriction rule differs, or mismatched config/plan yamls were sent.";
        throw runtime_error(ss.str());
    }

    // 'Dcore' is deliberately NOT compared: it is the producer's cdd2-registry value, and
    // 'ref' carries the placeholder. Check its standalone invariant instead -- it is
    // otherwise the one member nothing constrains, and it sets the token time granularity
    // (decode_argmax() uses dt = min(Dcore, 2^lpf) and requires t % dt == 0). See
    // PeakFindingKernelParams::Dcore: a power of two dividing (nt_in / nt_out), where the
    // kernel's nt_in is this tree's nt_ds.
    long Dout = this->nt_ds / this->nt_out;

    if ((this->nt_out <= 0) || (this->nt_ds != Dout * this->nt_out) ||
        (this->Dcore <= 0) || !is_power_of_two(this->Dcore) || (Dout % this->Dcore != 0)) {
        stringstream ss;
        ss << ctx.str() << "Dcore=" << this->Dcore << " is not a power of two dividing"
           << " nt_ds/nt_out = " << this->nt_ds << "/" << this->nt_out << ". Dcore is the"
           " producer's cdd2-registry value and is adopted verbatim (it is not re-derived"
           " here, which is what lets decoding work across builds), so this is the only"
           " check on it -- and a wrong Dcore mis-decodes the fine-time field of every"
           " out_argmax token.";
        throw runtime_error(ss.str());
    }
}


// -------------------------------------------------------------------------------------------
//
// Decoding peak-finder output. These need a DedispersionConfig for the band geometry and the
// dispersion relation (delay_to_frequency(), dm_per_unit_delay()), which are properties of
// the instrument rather than of one tree, so it is passed as an argument rather than copied
// onto the tree. See the doc-comments in DedispersionTree.hpp for the full specification.


// For a detailed specification (and the definitions of the output params), see the
// doc-comment in DedispersionPlan.hpp. Background for the formulas below: the token
// encoding and its time quantization are described in PeakFindingKernel.hpp and (for the
// extra 'mu' field, which is what these tokens carry) CoalescedDdKernel2.hpp, the
// subband time-lag conventions in notes/dedispersion.tex (subband search section)
// and ReferenceTree.cpp, and the output-array indexing in the "Dedispersion output
// arrays" section of the dedispersion tex notes.


void DedispersionTree::decode_argmax(
    uint argmax_token, long idm_coarse, long itime_coarse,
    long &fmin, long &fmax, long &tlo, long &thi, long &p) const
{
    const DedispersionTree &tr = *this;
    const FrequencySubbands &fs = tr.frequency_subbands;

    xassert((idm_coarse >= 0) && (idm_coarse < tr.ndm_out));
    xassert((itime_coarse >= 0) && (itime_coarse < tr.nt_out));

    long Dout = xdiv(tr.nt_ds, tr.nt_out);   // = tr.pf.time_downsampling
    long Dcore = tr.Dcore;                   // token time granularity (see PeakFindingKernel.hpp)

    // Parse token = (t) | (p << 8) | (mu << 16) | (m << (16+K)).
    //
    // The tree's cdd2 kernel computes 2^K output DMs per warp of its second dedispersion
    // stage, where K = xdm_rank(). Those extra DMs do NOT get their own rows of out_max /
    // out_argmax: the index 'mu' is folded into the token's m-field as
    // m_ext = (m << K) | mu, and the peak-finder max-reduces over it. See
    // CoalescedDdKernel2.hpp. K is zero unless the tree has an early trigger.
    //
    // This is the only place that splits the m-field; every producer (cdd2 kernel,
    // ReferencePeakFindingKernel) writes it whole.

    long K = tr.xdm_rank();
    long m_ext = (argmax_token >> 16) & 0xffff;
    long mu    = m_ext & (pow2(K) - 1);
    long m     = m_ext >> K;
    p          = (argmax_token >> 8) & 0xff;
    long t     = argmax_token & 0xff;

    // Note (m < fs.M) is exactly the bound (m_ext < pow2(K) * fs.M), so 'mu' needs no
    // separate range check.
    xassert_lt(m, fs.M);           // m = multiplet (frequency subband, fine dm)
    xassert_lt(p, tr.nprofiles);   // p = peak-finding profile
    xassert_lt(t, Dout);           // t = fine time within coarse output bin

    // The token's fine time is quantized: t = isamp * dt, where dt = min(Dcore, 2^lpf)
    // and lpf is the peak-finding level (boxcar length 2^lpf) of profile p.
    long lpf = p ? ((p-1)/3) : 0;
    long dt = std::min(Dcore, pow2(lpf));
    xassert_eq(t % dt, 0);

    long n = fs.m_to_n.at(m);                 // frequency subband
    long dfine = fs.m_to_d.at(m);             // fine dm within subband
    long flo = fs.n_to_flo.at(n);             // subband range, in coarse-freq channels
    long fhi = fs.n_to_fhi.at(n);
    long lsb = integer_log2(fhi - flo);       // subband level

    long ipri = tr.primary_tree_index;

    // Frequency: the tree's channels ARE toplevel tree-freq channels (early triggers
    // restrict the search to a prefix; time-downsampling leaves the freq axis alone).
    // Note n_to_toplevel_fhi() is exclusive, whereas the reported 'fmax' is inclusive.

    fmin = tr.n_to_toplevel_flo(n);
    fmax = tr.n_to_toplevel_fhi(n) - 1;

    // Times, first in the tree's (time-downsampled) frame. The trailing pf-input sample
    // read by the winning trial is Tpf. The pf input at time T sums channel f at time
    // (T - Delta(f)), where Delta is exact at the subband edges: Delta(fmax) = Tlag
    // (the extrapolate-to-band-top lag) and Delta(fmin) = Tlag + Dsub (Dsub = delay
    // across the subband).

    // Coarse delay, at the pow2(fs.pf_rank) granularity that the lag formulas below assume:
    // 'idm_coarse' indexes bins of width pow2(pf_rank + K), and 'mu' selects one of the 2^K
    // sub-bins inside it. (Do not confuse 'mu' with 'dfine': 'mu' is the low K bits of the
    // COARSE DM index, whereas 'dfine' is the multiplet's fine DM within its subband -- two
    // different axes.) Downsampled trees search the upper half of a tree one rank larger.

    long dhi = (idm_coarse << K) | mu;

    if (ipri > 0)
        dhi += (tr.ndm_out << K);
    long Tpf = itime_coarse * Dout + t + dt - 1;
    long thi_ds = Tpf - (pow2(fs.pf_rank) - fhi) * dhi;      // Tpf - Tlag
    long tlo_ds = thi_ds - (dhi * pow2(lsb) + dfine);        // Tpf - Tlag - Dsub

    // Convert to toplevel full-resolution samples. Downsampled sample T covers full-res
    // samples [T*2^ipri, (T+1)*2^ipri - 1]. The reported trailing edge is EXCLUSIVE
    // (one past the last full-res sample summed), i.e. the end boundary of the
    // trailing bin.

    thi = (thi_ds + 1) << ipri;
    tlo = (tlo_ds + 1) << ipri;
}

// See DedispersionPlan.hpp for details of input/output params.
void DedispersionTree::decode_argmax2(
    const DedispersionConfig &config,
    long fmin, long fmax, long tlo, long thi, long p,
    double &freq_lo_MHz, double &freq_hi_MHz, double &dm,
    double &timestamp_samp, double &width_samp) const
{
    long ntree = pow2(config.toplevel_tree_rank);  // note "toplevel"
    long ipri = this->primary_tree_index;
    
    xassert_ge(fmin, 0);
    xassert_lt(fmin, fmax);
    xassert_lt(fmax, ntree);  // strict inequality
    xassert_le(tlo, thi);
    xassert_ge(p, 0);
    xassert_lt(p, this->nprofiles);

    // dispersion delay (in samples) per tree-freq
    double dslope = double(thi-tlo) / double(fmax-fmin);

    // The next block of code computes (based on peak-finding kernel index 0 <= p < P):
    //
    //  pf_width = nominal width of peak-finding kernel, in time samples (not sec or ms)
    //  pf_shift = offset between pf-kernel center-of-mass and "trailing edge" of kernel
    //
    // Currently, we use an informal definition of pf_width, but pf_shift is unambiguous.
    
    long pdiv = p / 3;
    long pmod = p - 3*pdiv;
    double pf_width, pf_shift;

    if (p == 0) {
        // Boxcar of width 2^ipri.
        pf_width = 1.0 * (1 << ipri);
        pf_shift = 0.5 * (1 << ipri);
    }
    else if (pmod == 1) {
        // Boxcar of width 2^{ipri+pdiv+1}
        pf_width = 1.0 * (1 << (ipri+pdiv+1));
        pf_shift = 0.5 * (1 << (ipri+pdiv+1));
    }
    else if (pmod == 2) {
        // kernel = [0.5,1,0.5] upsampled by 2^{ipri+pdiv}.
        pf_width = 2.0 * (1 << (ipri+pdiv));    // let's say pre-upsampled kernel has nomimal width 2
        pf_shift = 1.5 * (1 << (ipri+pdiv));    // pre-upsampled kernel has pshift 1.5 (unambiguous)
    }
    else {
        // kernel = [0.5,1,1,0.5] upsamled by 2^(ipri+pdiv-1)
        pf_width = 3.0 * (1 << (ipri+pdiv-1));   // let's say "base" kernel has nominal width 3
        pf_shift = 2.0 * (1 << (ipri+pdiv-1));   // pre-upsampled kernel has pshift 2.0 (unambiguous)
    }

    // Now we're ready to compute output params.
    // Note that the DM is estimated by converting "dslope" to a full-band delay (ntree tree-freqs)
    // The timestamp is computed as (thi + tdd - pf_shift), where
    //   thi = (trailing-edge timesamp at tree-freq f = fmax + 0.5)
    //   tdd = (dedispersion delay between f=ntree and f=fmax+0.5)
    //   pf_shift = (offset between pulse center and trailing edge)
    
    freq_lo_MHz = config.delay_to_frequency(fmax+1);
    freq_hi_MHz = config.delay_to_frequency(fmin);
    dm = dslope * ntree * config.dm_per_unit_delay();
    timestamp_samp = thi + dslope * (ntree-0.5-fmax) - pf_shift;
    width_samp = pf_width;
}

// See DedispersionPlan.hpp for the meaning of the returned array.
//
// Implementation: element (ichunk, idm, it) of tree 'itree' is unaffected by the
// zero-padding before the start of the acquisition iff
//
//     n*T_ds >= d0 + (idm+1)*D_ds - 1 + 4*Wmax,    n = ichunk*nt_out + it
//
// in "tree" samples (= 2^p input samples; max_width has these units too), where
// T_ds/D_ds are the tree's time/dm downsampling factors, and d0 = d_lo / 2^(e+p) is
// the tree's lowest internal delay (d_lo = 0 for the base tree, 2^(r_top+p-1) for
// downsampled trees). DM bin idm covers internal delays [d0 + idm*D_ds,
// d0 + (idm+1)*D_ds): the dedispersion output at internal delay d and (trigger-freq)
// time tau references input samples [tau - d, tau], subband multiplets reference
// within that range, output time bin n starts at tree sample n*T_ds, and the causal
// peak-finding kernels reach back up to 2*Wmax - 1 more samples (padded to 4*Wmax).
// Solving for the smallest steady-state n (ceil division; exact for integer n) gives
// the per-idm array below.

Array<long> DedispersionTree::compute_steady_state_it0(const DedispersionConfig &config) const
{
    const DedispersionTree &tr = *this;

    long p = tr.primary_tree_index;
    long e = tr.early_trigger_level;
    long T_ds = tr.pf.time_downsampling;
    long D_ds = tr.pf.dm_downsampling;
    long Wmax = tr.pf.max_width;
    long r_top = config.toplevel_tree_rank;

    long d_lo = (p > 0) ? pow2(r_top + p - 1) : 0;   // lowest full-band delay searched by tree
    long d0 = xdiv(d_lo, pow2(e + p));               // lowest internal delay

    Array<long> ret({tr.ndm_out}, af_uhost);

    for (long idm = 0; idm < tr.ndm_out; idm++) {
        long dmax = d0 + (idm+1) * D_ds - 1;         // max internal delay in DM bin idm
        ret.data[idm] = (dmax + 4*Wmax + T_ds - 1) / T_ds;
    }

    return ret;
}


// -------------------------------------------------------------------------------------------
//
// Yaml I/O. See doc-comments in DedispersionTree.hpp.
//
// to_yaml() and from_yaml() are two transcriptions of the same field list, so a field added
// to one must be added to the other. The round-trip unit test in
// pirate_frb/tests/test_decode_argmax.py is what enforces this.


void DedispersionTree::to_yaml(YAML::Emitter &emitter, const DedispersionConfig &config,
                               long tree_index, bool verbose) const
{
    const DedispersionTree &tree = *this;
    long et_level = tree.early_trigger_level;
    double time_sample_ms = config.time_sample_ms;
    double ds_factor = pow2(tree.primary_tree_index);
    double max_delay = 1.0e-3 * time_sample_ms * ds_factor * pow2(config.toplevel_tree_rank - et_level);

    emitter << YAML::Newline;
    emitter << YAML::BeginMap;

    emitter << YAML::Key << "tree_index" << YAML::Value << tree_index;

    emitter << YAML::Key << "ndm_out" << YAML::Value << tree.ndm_out;
    if (verbose)
        emitter << YAML::Comment("Number of output (dedispersed) DM channels");

    emitter << YAML::Key << "nt_out" << YAML::Value << tree.nt_out;
    if (verbose)
        emitter << YAML::Comment("Number of output time samples");

    emitter << YAML::Key << "dm_min" << YAML::Value << tree.dm_min;
    if (verbose)
        emitter << YAML::Comment("Minimum DM (pc/cm^3)");

    emitter << YAML::Key << "dm_max" << YAML::Value << tree.dm_max;
    if (verbose)
        emitter << YAML::Comment("Maximum DM (pc/cm^3)");

    emitter << YAML::Key << "trigger_frequency" << YAML::Value << tree.trigger_frequency;
    if (verbose)
        emitter << YAML::Comment("Early-trigger frequency (MHz)");

    emitter << YAML::Key << "primary_tree_index" << YAML::Value << tree.primary_tree_index;
    if (verbose) {
        stringstream ss;
        ss << (time_sample_ms * ds_factor) << " ms samples"
           << ", DM range [" << tree.dm_min << ", " << tree.dm_max << "]";
        emitter << YAML::Comment(ss.str());
    }

    emitter << YAML::Key << "early_trigger_level" << YAML::Value << et_level;
    if (verbose) {
        stringstream ss;
        ss << (et_level > 0 ? "early" : "non-early")
           << " trigger at " << tree.trigger_frequency << " MHz"
           << ", max delay " << max_delay << " seconds";
        emitter << YAML::Comment(ss.str());
    }

    emitter << YAML::Key << "amb_rank" << YAML::Value << tree.amb_rank;
    if (verbose)
        emitter << YAML::Comment("Ambient rank of this tree (see DedispersionTree.hpp)");

    emitter << YAML::Key << "dd_rank" << YAML::Value << tree.dd_rank;
    if (verbose)
        emitter << YAML::Comment("Active dedispersion rank of this tree (see DedispersionTree.hpp)");

    emitter << YAML::Key << "nt_ds" << YAML::Value << tree.nt_ds;
    if (verbose)
        emitter << YAML::Comment("Downsampled time samples per chunk (= nt_in / 2^primary_tree_index)");

    emitter << YAML::Key << "max_width" << YAML::Value << tree.pf.max_width;
    if (verbose) {
        stringstream ss;
        ss << (tree.pf.max_width * ds_factor * time_sample_ms) << " ms";
        emitter << YAML::Comment(ss.str());
    }

    emitter << YAML::Key << "dm_downsampling" << YAML::Value << tree.pf.dm_downsampling;
    if (verbose && (tree.primary_tree_index > 0)) {
        stringstream ss;
        ss << (tree.pf.dm_downsampling * ds_factor) << " before downsampling";
        emitter << YAML::Comment(ss.str());
    }

    emitter << YAML::Key << "time_downsampling" << YAML::Value << tree.pf.time_downsampling;
    if (verbose && (tree.primary_tree_index > 0)) {
        stringstream ss;
        ss << (tree.pf.time_downsampling * ds_factor) << " before downsampling";
        emitter << YAML::Comment(ss.str());
    }

    emitter << YAML::Key << "Dcore" << YAML::Value << tree.Dcore;
    if (verbose)
        emitter << YAML::Comment("Peak-finder internal time-downsampling (sets out_argmax token granularity)");

    emitter << YAML::Key << "nprofiles" << YAML::Value << tree.nprofiles;
    if (verbose)
        emitter << YAML::Comment("Number of peak-finding profiles (= 1 + 3*log2(max_width))");

    emitter << YAML::Key << "wt_dm_downsampling" << YAML::Value << tree.pf.wt_dm_downsampling;
    if (verbose && (tree.primary_tree_index > 0)) {
        stringstream ss;
        ss << (tree.pf.wt_dm_downsampling * ds_factor) << " before downsampling";
        emitter << YAML::Comment(ss.str());
    }

    emitter << YAML::Key << "wt_time_downsampling" << YAML::Value << tree.pf.wt_time_downsampling;
    if (verbose && (tree.primary_tree_index > 0)) {
        stringstream ss;
        ss << (tree.pf.wt_time_downsampling * ds_factor) << " before downsampling";
        emitter << YAML::Comment(ss.str());
    }

    emitter << YAML::Key << "ndm_wt" << YAML::Value << tree.ndm_wt;
    if (verbose)
        emitter << YAML::Comment("Number of DMs in peak-finding weights array");

    emitter << YAML::Key << "nt_wt" << YAML::Value << tree.nt_wt;
    if (verbose)
        emitter << YAML::Comment("Number of time samples in peak-finding weights array");

    if (verbose) {
        const FrequencySubbands &fs = tree.frequency_subbands;

        // Note: the multiline comment starting with "# At tree_index=..." is indented
        // by a Python post-processing hack in pirate_frb/__main__.py (show_dedisperser).
        // If you change the format of this comment, update the Python code accordingly!
        stringstream ss;
        ss << "At tree_index=" << tree_index << ", " << fs.N << " frequency subband(s) are searched:\n";
        fs.show_compact(ss);
        emitter << YAML::Newline << YAML::Newline << YAML::Comment(ss.str())
                << YAML::Newline << YAML::Newline;
    }

    emitter << YAML::Key << "frequency_subband_counts"
            << YAML::Value << YAML::Flow << YAML::BeginSeq;
    for (long n: tree.frequency_subbands.subband_counts)
        emitter << n;
    emitter << YAML::EndSeq;

    emitter << YAML::EndMap;
}


// Static member function.
DedispersionTree DedispersionTree::from_yaml(const YamlFile &yt, const DedispersionConfig &cfg)
{
    DedispersionTree tree;

    tree.primary_tree_index = yt.get_scalar<int>("primary_tree_index");
    tree.early_trigger_level = yt.get_scalar<int>("early_trigger_level");
    tree.amb_rank = yt.get_scalar<int>("amb_rank");
    tree.dd_rank = yt.get_scalar<int>("dd_rank");
    tree.nt_ds = yt.get_scalar<int>("nt_ds");
    tree.Dcore = yt.get_scalar<long>("Dcore");
    tree.nprofiles = yt.get_scalar<long>("nprofiles");
    tree.ndm_out = yt.get_scalar<long>("ndm_out");
    tree.ndm_wt = yt.get_scalar<long>("ndm_wt");
    tree.nt_out = yt.get_scalar<long>("nt_out");
    tree.nt_wt = yt.get_scalar<long>("nt_wt");

    // Informational members. Note that these round-trip lossily (to_yaml() uses
    // yaml-cpp's default ~6-significant-digit precision for doubles); they are
    // print/display values, not used by decode_argmax*().
    tree.dm_min = yt.get_scalar<double>("dm_min");
    tree.dm_max = yt.get_scalar<double>("dm_max");
    tree.trigger_frequency = yt.get_scalar<double>("trigger_frequency");

    // 'pf' is seeded from the config's PrimaryTree (for num_early_triggers), then
    // the per-tree values are overwritten from the yaml. Note that the config's
    // {dm,time}_downsampling can be 0 (= "choose for me"), but the yaml carries the
    // post-auto-fill values -- the auto-fill rule is deliberately not reimplemented here.
    xassert((tree.primary_tree_index >= 0) && (tree.primary_tree_index < long(cfg.primary_trees.size())));
    tree.pf = cfg.primary_trees.at(tree.primary_tree_index);
    tree.pf.max_width = yt.get_scalar<long>("max_width");
    tree.pf.dm_downsampling = yt.get_scalar<long>("dm_downsampling");
    tree.pf.time_downsampling = yt.get_scalar<long>("time_downsampling");
    tree.pf.wt_dm_downsampling = yt.get_scalar<long>("wt_dm_downsampling");
    tree.pf.wt_time_downsampling = yt.get_scalar<long>("wt_time_downsampling");

    // Same (subband_counts, fmin, fmax) call as the normal constructor path, where
    // fmin == trigger_frequency by construction, and fmax == top edge of the band.
    vector<long> sc = yt.get_vector<long>("frequency_subband_counts");
    tree.frequency_subbands = FrequencySubbands(sc, tree.trigger_frequency, cfg.zone_freq_edges.back());

    // Light local sanity checks (deliberately NOT consistency-vs-rederivation checks).
    xassert(tree.Dcore > 0);
    xassert(tree.nprofiles > 0);
    xassert(tree.ndm_out > 0);
    xassert(tree.nt_out > 0);
    xassert(tree.nt_ds > 0);

    return tree;
}


string DedispersionTree::to_yaml_string(const DedispersionConfig &config, long tree_index,
                                        bool verbose) const
{
    YAML::Emitter emitter;
    this->to_yaml(emitter, config, tree_index, verbose);
    return emitter.c_str();
}


// Static member function.
DedispersionTree DedispersionTree::from_yaml_string(const string &yaml_string,
                                                    const DedispersionConfig &config)
{
    YamlFile f = YamlFile::from_string(yaml_string, "<dedispersion tree string>");
    return from_yaml(f, config);
}


}  // namespace pirate
