"""GPU driver for the brute-force variance map (see brute_force.py for the algorithm).

Runs the same sweep as BruteForceVarianceMap, but on the GPU: one cupy stream, kernels launched
synchronously from python, no GpuDedisperser, no worker thread, no CudaEventRingbuf. The pipeline
is (see notes/variance_map.tex and the plan):

    one-hots -> [Detrender2d] -> GpuTreeGriddingKernel -> GpuDedispersionKernel (stage 1)
             -> MegaRingbuf -> GpuSbDedispersionKernel (stage 2 + subbands)
             -> sb_out -> GpuPfSquare -> float64 accumulator, one per tree

The beam axis is a pure spectator, so a batch of B beams runs B distinct (input channel, phase)
passes concurrently; that is the only reason to raise beams_per_batch.
"""

import numpy as np

from .brute_force import BruteForceVarianceMap
from ..utils import atomic_print


class GpuBruteForceVarianceMap:
    """Computes the dense variance map A of every DedispersionTree in a plan, on the GPU.

    Constructed from a DedispersionPlan and an optional Detrender2dParams, then allocated and
    run::

        bf = GpuBruteForceVarianceMap(plan, detrender=None)
        A = bf.run(progress=True)     # list of (2^(r-R), M, P, nfreq) float64 arrays

    Same arguments, same requirements on the plan and the same return value as
    slow_avar.BruteForceVarianceMap, which is the CPU implementation of the same algorithm and
    the reference this is validated against (test_vs_cpu). Three additional requirements:

      - The config dtype must be float32 (GpuSbDedispersionKernel is float32-only).
      - One primary tree, i.e. no time-downsampled trees. Downsampled trees would need a
        GpuLaggedDownsamplingKernel between the gridding kernel and stage 1, which is not
        bound to python.
      - A compiled sbdd kernel must exist for every tree's (dd_rank, subband_counts) pair.
        The constructor builds all of them, so a missing one throws immediately, naming the
        key; see autogenerated_sbdd_kernels() in makefile_helper.py.
    """

    def __init__(self, plan, detrender=None, detrender_dtype=np.float64):
        """Builds all the GPU kernels (which is what makes a missing sbdd variant fail here
        rather than mid-sweep), but allocates nothing; see allocate(), which run() calls.

        Args: as slow_avar.BruteForceVarianceMap. 'detrender_dtype' applies only to the
        one-hot responses this class computes on the host when the GPU Detrender2d is not
        used (see _make_input_stream); it does not affect the GPU kernel, which is float32.
        """

        from ..kernels import (Detrender2d, GpuDedispersionKernel, GpuPfSquare,
                               GpuSbDedispersionKernel, GpuTreeGriddingKernel)

        self.geom = BruteForceVarianceMap(plan, detrender=detrender,
                                          detrender_dtype=detrender_dtype)
        self.plan = plan
        self.nbeams = self.geom.nbeams
        self.detrender = detrender

        if np.dtype(plan.dtype) != np.float32:
            raise RuntimeError(f"GpuBruteForceVarianceMap: config dtype must be float32 (got"
                               f" {np.dtype(plan.dtype)}); GpuSbDedispersionKernel is float32-only")
        if int(plan.num_primary_trees) != 1:
            raise RuntimeError(f"GpuBruteForceVarianceMap: num_primary_trees ="
                               f" {int(plan.num_primary_trees)}, expected 1. Time-downsampled"
                               " trees need a GpuLaggedDownsamplingKernel, which is not bound"
                               " to python.")

        rb = plan.mega_ringbuf
        if int(rb.host_global_nseg) != 0:
            raise RuntimeError(f"GpuBruteForceVarianceMap: the MegaRingbuf has"
                               f" {int(rb.host_global_nseg)} host segments, so the sweep would"
                               " need host<->gpu ring-buffer copies. Raise 'max_gpu_clag' in the"
                               " config (the default, 10000, keeps the ring buffer pure-GPU).")

        self.tg_kernel = GpuTreeGriddingKernel(plan.tree_gridding_kernel_params)
        self.dd1_kernel = GpuDedispersionKernel(plan.stage1_dd_kernel_params[0])
        self.rb_nelts = int(rb.gpu_global_nseg) * int(plan.stage1_dd_kernel_params[0].nt_per_segment)

        # Tree channels, which is NOT the input channel count: gridding rebins nfreq input
        # channels into nchan = 2^toplevel_tree_rank tree channels.
        self.nchan = int(plan.tree_gridding_kernel_params.nchan)

        self.sb_kernels, self.pf_kernels = [], []
        for itree in range(self.geom.ntrees):
            p2 = plan.stage2_dd_kernel_params[itree]
            if int(p2.dd_rank) < 3:
                raise RuntimeError(f"GpuBruteForceVarianceMap: tree {itree} has stage-2 dd_rank ="
                                   f" {int(p2.dd_rank)}, and GpuSbDedispersionKernel needs >= 3."
                                   f" A tree's dd_rank is ceil((toplevel_tree_rank -"
                                   " early_trigger_level)/2), so either raise"
                                   " toplevel_tree_rank or use fewer early triggers.")
            self.sb_kernels.append(GpuSbDedispersionKernel(p2, plan.trees[itree].frequency_subbands))
            # Every axis except time is a spectator to GpuPfSquare, so sb_out's (Dpf, M) pair is
            # simply flattened into its 'ndm' row count.
            self.pf_kernels.append(GpuPfSquare(int(plan.trees[itree].pf.max_width),
                                               self.nbeams, self.nbeams,
                                               self.geom.tree_D[itree] * self.geom.tree_M[itree],
                                               self.geom.tree_nt_ds[itree]))

        # detrender.M is checked against beams_per_batch by BruteForceVarianceMap, above.
        self.gpu_detrender = Detrender2d(detrender) if (detrender is not None) else None

        self.is_allocated = False

    def allocate(self, allocator=None):
        """Allocates the kernels' persistent state and this class's GPU buffers.

        Args:
          allocator: a BumpAllocator with af_gpu set, or None to make a dummy-mode one (each
            allocation independent), which is what a standalone sweep wants.
        """

        import cupy as cp
        from ..core import BumpAllocator

        if allocator is None:
            allocator = BumpAllocator('af_gpu | af_zero', -1)

        for k in [self.tg_kernel, self.dd1_kernel] + self.sb_kernels + self.pf_kernels:
            k.allocate(allocator)

        g, B, nt_in = self.geom, self.nbeams, self.geom.nt_in
        W = g.W

        # Detrender2d reads (B, nfreq, nt_in+2W) and overwrites only [W, W+nt_in); the gridding
        # kernel wants a contiguous (B, nfreq, nt_in), so the two are separate arrays.
        self.det_data, self.det_mask = None, None
        if self.gpu_detrender is not None:
            self.det_data = cp.zeros((B, g.nfreq, nt_in + 2*W), dtype=np.float32)
            self.det_mask = cp.ones((B, g.nfreq, nt_in + 2*W), dtype=np.uint8)

        self.stream_in = cp.zeros((B, g.nfreq, nt_in), dtype=np.float32)
        p1 = self.plan.stage1_dd_kernel_params[0]
        assert (1 << int(p1.amb_rank + p1.dd_rank)) == self.nchan, (p1.amb_rank, p1.dd_rank)
        self.tree_in = cp.zeros((B, 1 << int(p1.amb_rank), 1 << int(p1.dd_rank), nt_in),
                                dtype=np.float32)
        self.ringbuf = cp.zeros(self.rb_nelts, dtype=np.float32)

        self.sb_out, self.acc = [], []
        for itree in range(g.ntrees):
            self.sb_out.append(cp.zeros((B, g.tree_D[itree], g.tree_M[itree], g.tree_nt_ds[itree]),
                                        dtype=np.float32))
            self.acc.append(cp.zeros((B, g.tree_D[itree]*g.tree_M[itree], g.tree_P[itree]),
                                     dtype=np.float64))

        self.allocator = allocator
        self.is_allocated = True
        self._mask_checked = False   # see _make_input_stream()

    def run(self, progress=False, guard_chunk=True):
        """Computes A for every tree, and returns it as a list of ntrees float64 numpy arrays of
        shape (2^(r-R), M, P, nfreq). Same contract as BruteForceVarianceMap.run().

        Passes are laid end to end in a single continuous stream: pass k occupies input samples
        [k*nchunks*nt_in, (k+1)*nchunks*nt_in), which is long enough that pass k's response has
        died out before pass k+1's one-hot arrives. No kernel's persistent state, and no part of
        the ring buffer, is ever reset -- only the small GpuPfSquare accumulator, at each
        interval boundary.
        """

        import cupy as cp

        if not self.is_allocated:
            self.allocate()

        g = self.geom
        nchunks = g.ndata_chunks + (1 if guard_chunk else 0)

        # Accumulate with the frequency axis SLOWEST, so that a pass writes a contiguous block
        # rather than a column of stride nfreq, and transpose once at the end. The strided
        # version costs about as much as the whole GPU pipeline at r = 12.
        Acol = [np.zeros((g.nfreq, g.tree_D[i], g.tree_M[i], g.tree_P[i])) for i in range(g.ntrees)]

        # (ifreq, iphase) pairs, in launch-sized groups of nbeams. The last group may be short;
        # its unused beams are simply left with zero input, which costs a little work and
        # produces zeros rather than needing any special case.
        passes = [(f, c) for f in range(g.nfreq) for c in range(g.nphases)]
        groups = [passes[i : i+self.nbeams] for i in range(0, len(passes), self.nbeams)]

        if progress:
            atomic_print(f"GpuBruteForceVarianceMap: {len(passes)} passes in {len(groups)} launches"
                         f" x {nchunks} chunks (nfreq={g.nfreq}, nphases={g.nphases},"
                         f" nbeams={self.nbeams}, ntime={g.ntime}, nt_in={g.nt_in})")

        report_every = max(1, len(groups) // 20)
        stream = cp.cuda.get_current_stream()

        for igroup, group in enumerate(groups):
            for itree in range(g.ntrees):
                self.acc[itree].fill(0.0)

            for j in range(nchunks):
                self._run_chunk(group, igroup*nchunks + j, j)

            stream.synchronize()

            for itree in range(g.ntrees):
                # (B, Dpf*M, P) -> (B, Dpf, M, P); beam b carried pass group[b].
                a = cp.asnumpy(self.acc[itree]).reshape(
                    self.nbeams, g.tree_D[itree], g.tree_M[itree], g.tree_P[itree])
                for b, (ifreq, _) in enumerate(group):
                    Acol[itree][ifreq] += g.tree_phase_weight[itree] * a[b]

            if progress and ((igroup+1) % report_every == 0):
                atomic_print(f"  GpuBruteForceVarianceMap: launch {igroup+1}/{len(groups)}")

        A = [np.ascontiguousarray(a.transpose(1, 2, 3, 0)) for a in Acol]
        del Acol

        g.check_structure(A)
        return A

    def _run_chunk(self, group, ichunk, j):
        """Runs one chunk of one launch group: fills the input stream, then walks the pipeline.
        'j' is the chunk's index within the interval (only chunk 0 carries a one-hot)."""

        import cupy as cp

        g, B = self.geom, self.nbeams
        sptr = cp.cuda.get_current_stream().ptr
        self._make_input_stream(group, j)

        # The gridding kernel's output is (B, nchan, ntime), which reshapes to the
        # (B, 2^amb_rank, 2^dd_rank, ntime) that stage-1 dedispersion wants. Note nchan is the
        # TREE channel count, which need not equal the input channel count nfreq.
        self.tg_kernel.launch(self.tree_in.reshape(B, self.nchan, g.nt_in), self.stream_in, sptr)
        self.dd1_kernel.launch(self.tree_in, self.ringbuf, ichunk, 0, sptr)

        for itree in range(g.ntrees):
            self.sb_kernels[itree].launch(self.sb_out[itree], self.ringbuf, ichunk, 0, sptr)
            self.pf_kernels[itree].launch(
                self.acc[itree],
                self.sb_out[itree].reshape(B, g.tree_D[itree]*g.tree_M[itree], g.tree_nt_ds[itree]),
                0, sptr)

    def _make_input_stream(self, group, j):
        """Fills self.stream_in (the tree gridding kernel's input) with the one-hots of this
        launch group, detrending them if a Detrender2d is configured.

        Only chunk 0 of an interval carries anything: L is linear, so the all-zero chunks that
        follow map to zero, and running the detrender on them would be pure cost. The one-hot's
        detrended response spans [t0-W, t0+W] with t0 = 2W + c, so it lies strictly inside chunk
        0's emitted region [W, W+nt_in) of the detrender buffer (checked in the geometry).
        """

        import cupy as cp

        g = self.geom

        if j != 0:
            self.stream_in.fill(0.0)
            return

        if self.gpu_detrender is None:
            self.stream_in.fill(0.0)
            for b, (ifreq, iphase) in enumerate(group):
                self.stream_in[b, ifreq, 2*g.W + iphase] = 1.0
            return

        self.det_data.fill(0.0)
        self.det_mask.fill(1)
        for b, (ifreq, iphase) in enumerate(group):
            self.det_data[b, ifreq, g.W + (2*g.W + iphase)] = 1.0   # buffer index = W + t0

        self.gpu_detrender.launch(self.det_data, self.det_mask)

        # Checked once, not once per launch: the Detrender2d's mask expansion is driven by
        # r_min, which depends on the mask and the basis but not on the data, so an all-ones
        # input mask either survives every time or never. If it did not survive, L would not be
        # the linear operator this tool assumes.
        if not self._mask_checked:
            if not bool((self.det_mask[:, :, g.W : g.W+g.nt_in] != 0).all()):
                raise RuntimeError("GpuBruteForceVarianceMap: the Detrender2d dropped an"
                                   " ill-conditioned zone even with an all-ones input mask, so L"
                                   " is not the linear operator this tool assumes.")
            self._mask_checked = True

        self.stream_in[...] = self.det_data[:, :, g.W : g.W+g.nt_in]

    @staticmethod
    def test_vs_cpu(toplevel_tree_rank=8, subband_counts=None, num_early_triggers=0,
                    detrender=False, nbeams=1, nfreq=None, verbose=True):
        """Compares the GPU sweep against the CPU sweep of BruteForceVarianceMap, element by
        element, on the same config.

        Both GPU kernels are separately validated against their reference implementations
        ('pirate_frb test --sbdd' and '--pfsq'), so a discrepancy here points at this driver
        rather than at a kernel. 'nfreq' defaults to 2^toplevel_tree_rank, but is worth varying:
        that is the case where the input channel count and the TREE channel count differ, and
        the buffers this driver allocates are sized by one or the other.
        """

        from ..pirate_pybind11 import DedispersionPlan
        from .brute_force import _make_test_config, _make_test_detrender

        if subband_counts is None:
            subband_counts = [2, 2, 1]

        config = _make_test_config(toplevel_tree_rank, subband_counts, nfreq=nfreq,
                                   num_early_triggers=num_early_triggers)
        dparams = _make_test_detrender(config) if detrender else None

        cpu_plan = DedispersionPlan(config, cdd2_kernel_required=False)
        cpu = BruteForceVarianceMap(cpu_plan, detrender=dparams, detrender_dtype=np.float32)
        want = cpu.run()

        config.beams_per_gpu = config.beams_per_batch = nbeams
        gpu_plan = DedispersionPlan(config, cdd2_kernel_required=False)
        if dparams is not None:
            dparams.M = nbeams
        got = GpuBruteForceVarianceMap(gpu_plan, detrender=dparams).run()

        worst, worst_where = 0.0, None
        for itree in range(len(want)):
            assert got[itree].shape == want[itree].shape, (got[itree].shape, want[itree].shape)
            scale = float(np.abs(want[itree]).max())
            e = float(np.abs(got[itree] - want[itree]).max()) / scale if (scale > 0) else 0.0
            if e > worst:
                worst, worst_where = e, itree

        if verbose:
            atomic_print(f"    test_vs_cpu(r={toplevel_tree_rank}, subbands={subband_counts},"
                         f" net={num_early_triggers}, detrender={bool(detrender)},"
                         f" nbeams={nbeams}, nfreq={cpu.nfreq}): worst relative difference"
                         f" {worst:.3g} at tree {worst_where}")

        # Both sides are float32 pipelines, but they are different float32 pipelines (the GPU
        # tree is not the reference tree), so this is a float32-roundoff comparison.
        assert worst < 1.0e-4, (worst, worst_where)
