#!/usr/bin/env python

import os
import sys
import contextlib

if (len(sys.argv) != 2) or (not sys.argv[1].endswith('.cu')):
    with contextlib.redirect_stdout(sys.stderr):
        print('Usage: autogenerate_kernel.py <filename>')
        print()
        print('Example filenames:')
        print()
        print('   # Dedispersion kernel.')
        print('   autogenerate_kernel.py src_lib/autogenerated_kernels/dd_fp32.cu')
        print()
        print('   # Peak-finding kernel.')
        print('   autogenerate_kernel.py src_lib/autogenerated_kernels/pf_fp32_f1_f1_E1_Dcore1_Dout1_Tinner1.cu')
        print()
        print('Note: the filename must end in .cu.')

    sys.exit(2)
    
# This way of importing 'pirate_frb.cuda generator' doesn't assume that the
# larger 'pirate_frb' package has been built or installed.
sys.path.insert(0, 'pirate_frb')
import cuda_generator

filename = sys.argv[1]
basename = os.path.basename(filename)

if basename.startswith('dd_'):
    cls = cuda_generator.MultiDedisperser
elif basename.startswith('pf_weight_reader'):
    cls = cuda_generator.PfWeightReader
elif basename.startswith('pf_output'):
    cls = cuda_generator.PfOutput
elif basename.startswith('pf_'):
    cls = cuda_generator.PeakFinder
elif basename.startswith('cdd2_'):
    cls = cuda_generator.CoalescedDdKernel2
else:
    raise RuntimeError(f"Couldn't parse autogenerated kernel filename {filename}")

cls.write_kernel(filename)