#!/usr/bin/env python

import os
import sys
import contextlib

if (len(sys.argv) != 2) or (not sys.argv[1].endswith('.cu')):
    with contextlib.redirect_stdout(sys.stderr):
        print('Usage: autogenerate_kernel.py <filename>')
        print()
        print('Example filenames:')
        print()
        print('   # Dedispersion kernel.')
        print('   autogenerate_kernel.py src_lib/autogenerated_kernels/dd_fp32.cu')
        print()
        print('   # Peak-finding kernel with (M,E,Dout,Dcore,W,BlocksPerSM) = (16,8,16,8,4,4).')
        print('   autogenerate_kernel.py src_lib/autogenerated_kernels/pf_fp32_M16_E8_Dout16_Dcore8_W4_B4.cu')
        print()
        print('Note: the filename must end in .cu.')

    sys.exit(2)
    
# This way of importing 'pirate_frb.cuda generator' doesn't assume that the
# larger 'pirate_frb' package has been built or installed.

sys.path.insert(0, 'pirate_frb')
import cuda_generator

filename = sys.argv[1]
basename = os.path.basename(filename)

if basename.startswith('dd_'):
    k = cuda_generator.make_dd_file(basename)
elif basename.startswith('pf_weight_reader'):
    cuda_generator.PfWeightReader.write_test_kernel(filename)
    sys.exit(0)  # FIXME
elif basename.startswith('pf_output'):
    cuda_generator.PfOutput2.write_test_kernel(filename)
    sys.exit(0)  # FIXME
elif basename.startswith('pf_'):
    k = cuda_generator.make_pf_file(basename)

with open(filename,'w') as f:
    with cuda_generator.utils.clang_formatter(f) as ff:
        k.write(ff)
