#!/usr/bin/env python
#
# This script is invoked by the Makefile, to generate "derived" Makefile variables:
#
#   - PYTHON_INCDIR
#   - NUMPY_INCDIR
#   - PYBIND11_INCDIR
#   - PYEXT_SUFFIX
#   - KSGPU_DIR
#   - AUTOGENERATED_KERNELS
#
# Values of these variables are written to makefile_helper.out.


# These global boolean variables are used to control which kernels are procedurally generated.
# This is a tradeoff between coverage and compile time.
#
# In "production" builds, I set production_kernels=True, and debug_*_kernels=False.
# When developing, I usually set all flags to False, so that compile times are short.
# If I'm debugging something specific, then I'll set a debug flag.
# For a long CI-style test run, I'll set all flags to true (high compile time!)

production_kernels = True     # "production" CHIME/CHORD kernels
varmap_kernels = True         # sbdd kernels for 'pirate_frb varmap bf' (see below)
debug_dd_kernels = False      # debug dedispersion kernels
debug_pf_kernels = False      # debug peak-finding kernels
debug_pfo_kernels = False     # debug peak-finding output microkernel
debug_pfwr_kernels = False    # debug peak-finding weight reader kernels
debug_cdd2_kernels = False    # debug coalesced dedispersion-pf kernels
debug_gpu_dd = False          # end-to-end test of gpu dedisperser

# 'varmap_kernels' is unlike the flags around it: it widens sbdd coverage ONLY, and is
# cheap enough to leave on. It exists because 'pirate_frb varmap bf' (notes/variance_map.tex,
# section "The variance map") runs the dedispersion stages standalone and needs an sbdd kernel
# for whatever (dd_rank, subband_counts) its config specifies -- but never needs the matching
# cdd2 kernel, which is where the compile time actually goes. See varmap_sbdd_kernels().
#
# Kernels with pf_rank < dd_rank1 ("xdm" = the extra DM bits such a kernel produces, see
# cuda_generator/Dedisperser.emit_subband_extraction()) used to be behind an 'xdm_kernels'
# flag. They are now unconditional: xdm_sbdd_kernels() sweeps the full (dd_rank, pf_rank)
# grid, since sbdd compiles are cheap, and the cdd2 half is a seven-row section of
# autogenerated_cdd2_kernels(), with the rest of the grid behind debug_cdd2_kernels.


####################################################################################################


import io
import os
import re
import sys
import sysconfig
import importlib.util

try:
    import pybind11
except:
    raise RuntimeError("Couldn't import pybind11 -- this is a fatal error")

try:
    import numpy
except:
    raise RuntimeError("Couldn't import numpy -- this is a fatal error")

# This way of getting KSGPU_DIR is awkward, but avoids importing 'ksgpu'.
# (This is useful since imports can generate unexpected output.)
ksgpu_spec = importlib.util.find_spec('ksgpu')
if ksgpu_spec is None:
    raise RuntimeError("Couldn't find 'ksgpu' package -- this is a fatal error")

# This way of importing 'pirate_frb.cuda generator' doesn't assume that the
# larger 'pirate_frb' package has been built or installed.
sys.path.insert(0, 'pirate_frb')
import cuda_generator


####################################################################################################


def main():
    s = io.StringIO()
    print("# Autogenerated by makefile_helper.py (which is automatically invoked by the Makefile)\n", file=s)

    python_incdir = sysconfig.get_config_var('INCLUDEPY')
    print("# Include directory for python headers", file=s)
    print("# From sysconfig.get_config_var('INCLUDEPY')", file=s)
    print(f"PYTHON_INCDIR = {python_incdir}\n", file=s)

    numpy_incdir = numpy.get_include()
    print("# Include directory for numpy headers", file=s)
    print("# From numpy.get_include()", file=s)
    print(f"NUMPY_INCDIR = {numpy_incdir}\n", file=s)

    pybind11_incdir = pybind11.get_include()
    print("# Include directory for pybind11 headers", file=s)
    print("# From pybind11.get_include()", file=s)
    print(f"PYBIND11_INCDIR = {pybind11_incdir}\n", file=s)

    pyext_suffix = sysconfig.get_config_var('EXT_SUFFIX')
    print("# Filename suffix for python extension modules", file=s)
    print("# From sysconfig.get_config_var('EXT_SUFFIX')", file=s)
    print("# Equivalent to 'python3-config --extension-suffix'", file=s)
    print(f"PYEXT_SUFFIX = {pyext_suffix}\n", file=s)

    ksgpu_dir = os.path.dirname(ksgpu_spec.origin)
    print("# Base directory for 'ksgpu' package", file=s)
    print("# From importlib.util.find_spec('ksgpu').origin", file=s)
    print(f"KSGPU_DIR = {ksgpu_dir}\n", file=s)

    print("# CUDA kernels that will be autogenerated (by running ./autogenerate_kernel.py)", file=s)
    print('AUTOGENERATED_KERNELS =', end='', file=s)
    for filename in autogenerated_kernel_filenames():
        print(f' \\\n    {filename}', end='', file=s)
    print(file=s)

    s = s.getvalue()
    outfile = 'makefile_helper.out'
    print(f'Writing {outfile}')

    with open(outfile,'w') as f:
        print(s, file=f, end='')

    # Show summary on stdout (for debugging).
    if False:
        for line in s.split('\n'):
            if (len(line) > 0) and (line[0] != '#'):
                print('   ', line)


####################################################################################################


def autogenerated_kernel_filenames():
    """
    Top-level generator for autogenerated kernels:

       - removes duplicate filenames ("lower-level" generators are allowed
         to emit duplicates freely)
     
       - converts basenames to 'src_lib/autogenerated_kernels/{basename}'
    """
    
    kernels = { }   # registry key -> basename

    # The generator autogenerated_kernel_basenames() is defined below.
    for basename in autogenerated_kernel_basenames():
        # The 'key' addresses a detail of our KernelRegistry: for some pf-kernels (namely
        # those beginning with 'pf_' but not 'pf_weight_reader' or 'pf_output', we don't
        # allow two kernels which are identical except for the same value of Dcore. In
        # these cases, we strip "DcoreNN" from the key, and then raise an exception if
        # two kernels have the same key but different basenames.
        key = basename
        if basename.startswith('pf_') and not basename.startswith(('pf_weight_reader', 'pf_output')):
            key = re.sub(r'_Dcore\d+', '', basename)

        prev = kernels.get(key)

        if prev is None:
            kernels[key] = basename
            yield f'src_lib/autogenerated_kernels/{basename}'
        elif prev != basename:
            raise RuntimeError("autogenerated_kernel_filenames: these two kernels are identical,"
                               f" except for the value of Dcore: {prev} {basename}")


def autogenerated_kernel_basenames():
    for kernel in autogenerated_dedispersion_kernels():
        yield kernel.kernel_basename
    
    for kernel in autogenerated_cdd2_kernels():
        for basename in kernel.all_kernel_basenames:
            yield basename

    for kernel in autogenerated_sbdd_kernels():
        yield kernel.kernel_basename

    for kernel in autogenerated_peak_finding_kernels():
        for basename in kernel.all_kernel_basenames:
            yield basename
    
    for kernel in autogenerated_pf_weight_reader_kernels():
        yield kernel.kernel_basename

    for kernel in autogenerated_pf_output_kernels():
        yield kernel.kernel_basename


def autogenerated_dedispersion_kernels():
    """
    Generates objects of type 'cuda_generator.MultiDedisperser'.
    Duplicates are okay here (they'll be caught later, see 'duplicate_checker' above.)
    """
    
    T, F = True, False

    # Triples are of the form (input_is_ringbuf, output_is_ringbuf, apply_input_residual_lags).
    # We always generate enough kernels to run 'pirate_frb -m test --dd', even if debug_dd_kernels == False.
    triples = [ (F,F,F), (F,T,F), (T,F,T) ]

    if debug_dd_kernels:
        triples += [ (F,F,T), (F,T,T), (T,F,F) ]

    for dtype in [ 'float', '__half' ]:
        for irb,orb,rlag in triples:
            nspec_list = [1,8] if debug_dd_kernels else [1]
            for nspec in nspec_list:
                yield cuda_generator.MultiDedisperser(
                    dtype = dtype,
                    apply_input_residual_lags = rlag,
                    input_is_ringbuf = irb,
                    output_is_ringbuf = orb,
                    nspec = nspec
                )

        
def autogenerated_peak_finding_kernels():
    """
    Generates objects of type 'cuda_generator.PeakFinder'.
    Duplicates are okay here (they'll be caught later, see 'duplicate_checker' above.)
    """

    # The parameter space (dtype, subband_counts, Wmax, Dcore, Dout, Tinner) is too
    # large to enumerate, so we chooise a few representative kernels.

    # "Corners" of parameter space (16 kernels total)
    # Subband counts here are randomly generated.

    if not debug_pf_kernels:
        return
    
    kernels = [
        ('fp32', (1,1), 1, 1, 1, 1),
        ('fp32', (5,5,2,1), 1, 1, 1, 32),
        ('fp32', (0,8,2,2,1), 1, 1, 32, 1),
        ('fp32', (7,0,3,1,1), 1, 32, 32, 1),
        ('fp32', (0,2,0,1), 16, 1, 1, 1),
        ('fp32', (1,1), 16, 1, 1, 32),
        ('fp32', (0,1), 16, 1, 32, 1),
        ('fp32', (2,11,1,0,1), 32, 32, 32, 1),
        ('fp16', (1,1), 1, 2, 2, 1),
        ('fp16', (3,6,5,2,1), 1, 2, 2, 32),
        ('fp16', (2,3,1,1), 1, 2, 32, 1),
        ('fp16', (0,3,2,1), 1, 32, 32, 1),
        ('fp16', (3,2,1), 32, 2, 2, 1),
        ('fp16', (2,1), 32, 2, 2, 32),
        ('fp16', (1,1,1), 32, 2, 32, 1),
        ('fp16', (3,4,2,1), 32, 32, 32, 1),
    ]

    # Add some randomly generated kernels.
    # python -m pirate_frb dev random_kernels --pf

    kernels += [
        ('fp32', (3, 1, 0, 1), 4, 1, 2, 1),
        ('fp16', (9, 0, 2, 2, 1), 2, 2, 2, 8),
        ('fp16', (1, 5, 2, 0, 1), 8, 4, 8, 4),
        ('fp32', (6, 3, 2, 1), 1, 2, 8, 4),
        ('fp32', (1, 4, 1, 1), 16, 4, 4, 2),
        ('fp16', (0, 1), 8, 4, 4, 8),
        ('fp32', (3, 1, 1), 1, 8, 16, 1),
        ('fp32', (1, 5, 6, 0, 1), 2, 4, 8, 2),
        ('fp16', (2, 6, 0, 1), 16, 8, 16, 4),
        ('fp32', (8, 11, 1, 1, 1), 1, 1, 4, 2),
        ('fp16', (4, 6, 0, 1), 4, 8, 32, 2),
        ('fp16', (0, 2, 1), 16, 8, 8, 4),
        ('fp16', (5, 3, 2, 1), 2, 16, 32, 2),
        ('fp16', (2, 3, 1), 4, 2, 8, 2),
        ('fp16', (2, 1, 2, 1), 8, 8, 16, 2)
    ]

    for dtype, subband_counts, Wmax, Dcore, Dout, Tinner in kernels:
        fs = cuda_generator.FrequencySubbands(subband_counts = subband_counts)
        yield cuda_generator.PeakFinder(dtype, fs, Wmax, Dcore, Dout, Tinner)

    
# The (dd_rank, subband_counts, et_levels) of every tree in configs/dedispersion/*.yml.
# MODULE SCOPE because two generators need it: autogenerated_cdd2_kernels() compiles the cdd2
# kernels for these trees (only when production_kernels is set), and varmap_sbdd_kernels()
# derives the sbdd kernels 'pirate_frb varmap bf' needs for the same trees (always). The
# second used to be a hand-maintained copy of the first, and drifted -- see the comment there.
#
# Also mirrored in CoalescedDdKernel2::time_selected(), which calls time_one() on the distinct
# subband_counts below. That is a hand-maintained copy too, but a benign one: a missing kernel
# makes time_one() skip with a message rather than silently degrade.

PRODUCTION_TREES = [
    (7, (0,0,0,0,1), [0]),       # chime.yml
    (8, (0,0,0,0,1), [0]),       # chime.yml, chord_sb0.yml
    (7, (0,0,1,2,1), [0]),       # chime_sb1.yml
    (8, (0,0,1,2,1), [0]),       # chime_sb1.yml
    (7, (0,5,7,3,1), [0,1,2,3]), # chime_sb2.yml, chime_sb2_et.yml
    (8, (0,5,7,3,1), [0]),       # chime_sb2.yml, chime_sb2_et.yml
    (8, (1,2,2,2,1), [0]),       # chord_sb1.yml
    (8, (5,9,7,3,1), [0,1,2,3])  # chord_sb2.yml, chord_sb2_et.yml
]


def autogenerated_cdd2_kernels():
    """
    Generates objects of type 'cuda_generator.CoalescedDdKernel2'.
    Duplicates are okay here (they'll be caught later, see 'duplicate_checker' above.)
    """

    # Throughout this function, we represent kernels by tuples
    #   (dtype, dd_rank, Wmax, Tinner, subband_counts, et_levels)
    #
    # There is deliberately NO Dcore or Dout here: both are functions of dd_rank, derived by
    # the CoalescedDdKernel2 constructor. See cuda_generator.cdd2_dout() for why that is an
    # invariant rather than a default.

    # Start with a few "baseline" kernels, so that unit tests can run even if all boolean flags are False.
    # The baseline kernels make a reasonable attempt to test a variety of code paths.
    # Note: dd_rank stays small here, since DedispersionConfig::make_random() draws its base
    # key from dd_rank <= 5 at the default max_toplevel_rank=10 -- see the long comment below.
    # FIXME: Wmax=32 is currently broken in "toy-size" kernels (it works in "production-size" kernels).
    #
    # Note the subband_counts in every list below are a CONFIG's frequency_subband_counts, so
    # they must satisfy pf_rank <= dd_rank1 at the largest dd_rank of their row -- the same
    # constraint DedispersionConfig::validate() imposes (its "check 2"). That is one of
    # several constraints a row can violate; nothing coerces them, and
    # cuda_generator.check_cdd2_params() in the loop at the bottom of this function is what
    # catches every one of them. Use 'pirate_frb dev random_kernels --cdd2' to generate new
    # rows: it calls the same validator, so its output is buildable by construction.

    kernels = [ 
        ('fp32', 6, 16, 2, (2,2,1), [0,1,2]),  # needed for configs/dedispersion/toy.yml
        ('fp32', 6,  8, 2, (2,2,1), [0,1,2]),  # needed for configs/dedispersion/toy.yml
        ('fp32', 6,  4, 2, (2,2,1), [0,1,2]),  # needed for configs/dedispersion/toy.yml
    ]

    # THE SHAPE OF THE LOOPS BELOW IS LOAD-BEARING FOR DedispersionConfig::make_random(), and
    # is not just extra coverage of the peak-finder. Two properties are being bought, and both
    # are properties of the REGISTRY rather than of the random draw:
    #
    #  1. EACH GROUP NEEDS SEVERAL Wmax. validate() requires each downsampled primary tree's
    #     max_width to equal its predecessor's or be HALF of it, so make_random() walks the
    #     chain by re-drawing from the keys whose Wmax is one of those two, within the group
    #     (dtype, dd_rank, subband_counts) of the DOWNSAMPLED tree. A group stocking one Wmax
    #     yields a FLAT chain always, so a config whose max_width -- hence whose nprofiles --
    #     varies across primary trees can never be drawn from it.
    #
    #  2. THE SAME SUBBAND VECTOR MUST APPEAR AT CONSECUTIVE dd_rank. make_random() draws
    #     toplevel_tree_rank from {2*dd_rank-1, 2*dd_rank}, so the downsampled group sits at
    #     dd_rank OR dd_rank-1. A row emits (dd_rank0 - e, restrict(subband_counts, e)) for
    #     each early-trigger level e, so the same restricted vector lands one dd_rank lower
    #     only if there is ANOTHER row one dd_rank0 lower. Without that, half the draws find
    #     no key at all and are forced to a single primary tree.
    #
    #  3. SOME VECTOR MUST CLAMP BELOW ITS TOP LEVEL UNDER RESTRICTION. This is what makes an
    #     early-trigger tree's multiplet map NON-CONTIGUOUS -- i.e. not the prefix [0..M_c) --
    #     which is the only case in which a wrong gather in restrict_fine_vector() (or in
    #     anything else that maps a parent tree's rows onto a child's) is visible at all.
    #
    #     restrict_subband_counts() drops the top et levels and then clamps each surviving
    #     level to its new maximum. If the clamp bites ONLY at the top of the restricted
    #     vector, the survivors are still a prefix. It has to bite at a level that still has
    #     populated levels ABOVE it. (2,2,1) and (2,3,1) both restrict to [2,1] clamping only
    #     level 1, which IS their new top; (2,3,1,1) does not clamp at all. So before (4,2,1)
    #     was added below, NO gpu_valid draw could produce a non-contiguous map -- measured
    #     0 out of 439 (parent, child) pairs -- while both shipped early-trigger configs are
    #     full of them: chord_sb2_et.yml (5,9,7,3,1) -> [5,7,3,1] clamps levels 1,2,3 and has
    #     a non-contiguous map in 5 of its 6 pairs, and chime_sb2_et.yml likewise.
    #
    #     (4,2,1) is the cheapest fix that has no interior zeros: M = 12, the same as the
    #     (2,3,1) already stocked, and it restricts to [2,1] clamping level 0 with level 1
    #     surviving above it. It is also exactly the vector test_apply_restriction() picks by
    #     hand for this property.
    #
    # Both matter only for the rows make_random() can actually draw from: it takes its base
    # key from dd_rank <= max_stage2_rank, which is 5 at the default max_toplevel_rank=10, so
    # the production rows below are too big and these baseline rows decide the rate on their
    # own. Measured with 'pirate_frb dev coverage' -- run it after changing anything here:
    #
    # fraction of make_random() draws whose max_width varies across primary trees:
    #
    #                              float32     float16
    #     one Wmax, no ladder        12%         18%      (24% / 13% at production_kernels=False)
    #     as written below           31%         29%
    #
    # (The "as written" row was re-measured after the Dout invariant landed -- 109/352 and
    # 129/448 of an 800-draw run -- and is unchanged from the 30%/30% measured before it,
    # which is the expected result: the invariant moves which Dout each dd_rank gets, not
    # which Wmax values a group stocks. The "one Wmax" counterfactual was not re-measured.)
    #
    # It costs 33 cdd2 kernels (87 -> 120), all at dd_rank <= 6 and so among the cheapest in
    # the build.
    #
    # Wmax=32 is deliberately absent: see the FIXME above about toy-size kernels.

    for Wmax in [16, 8, 4]:
        kernels += [
            ('fp32', 4, Wmax, 1, (2,2,1),   [0,1]),
            ('fp32', 5, Wmax, 1, (2,2,1), [0,1,2]),
        ]

    for Wmax in [16, 8, 4]:
        kernels += [
            ('fp16', 4, Wmax, 2, (2,3,1),   [0,1]),   # et 2 would give dd_rank 2, which is not two-stage
            ('fp16', 5, Wmax, 2, (2,3,1), [0,1,2]),
            ('fp16', 6, Wmax, 2, (2,3,1), [0,1,2]),
        ]

    # The non-contiguous-multiplet-map ladders; see point 3 above. Same shape as the two
    # ladders they sit beside, so that they keep properties 1 and 2 as well: several Wmax per
    # group, and the same vector at consecutive dd_rank. BOTH dtypes: the two halves of the
    # registry are stocked separately and 'pirate_frb dev coverage' reports them separately, so
    # an fp32-only ladder leaves the fp16 half at 0%.
    for Wmax in [16, 8, 4]:
        kernels += [
            ('fp32', 4, Wmax, 1, (4,2,1),   [0,1]),
            ('fp32', 5, Wmax, 1, (4,2,1), [0,1,2]),
        ]

    for Wmax in [16, 8, 4]:
        kernels += [
            ('fp16', 4, Wmax, 2, (4,2,1),   [0,1]),
            ('fp16', 5, Wmax, 2, (4,2,1), [0,1,2]),
            ('fp16', 6, Wmax, 2, (4,2,1), [0,1,2]),
        ]

    # (2,3,1,1) is the only baseline row with pf_rank = 3, so it stays even though it is off
    # the ladder above (its restriction chain is {2,3,1,1} -> {2,3,1} -> {2,1}, which lands a
    # DIFFERENT subband vector at each dd_rank and so cannot supply a downsampled partner).
    for Wmax in [8, 4]:
        kernels += [ ('fp16', 5, Wmax, 2, (2,3,1,1), [0,1,2]) ]

    if production_kernels:
        # Bare minimum kernels needed for configs/dedispersion/*.yml. See PRODUCTION_TREES
        # above; note CoalescedDdKernel2::time() mirrors its subband_counts by hand.

        for dd_rank, subband_counts, et_levels in PRODUCTION_TREES:
            # Values common to all chime/chord kernels.
            for Wmax in [32,16,8,4]:
                kernels += [ ('fp16', dd_rank, Wmax, 1, subband_counts, et_levels) ]

        # The production configs above are all float16, but CoalescedDdKernel2::time_selected()
        # also times float32, via DedispersionConfig::make_mini_chord(float32). That config has
        # toplevel_tree_rank=16 (hence dd_rank=8) and max_width=16 in every primary tree, so
        # (dd_rank=8, Wmax=16) covers every float32 kernel it needs. Without these, the float32
        # half of 'pirate_frb time --cdd2' prints "no cdd2 kernel in this build" and is skipped.
        # Each costs ~14 sec of compile time, so this is cheap; delete the loop if that changes.

        for dd_rank, subband_counts, et_levels in PRODUCTION_TREES:
            if dd_rank == 8:
                kernels += [ ('fp32', dd_rank, 16, 1, subband_counts, [0]) ]

    if debug_cdd2_kernels or debug_gpu_dd:
        # Add some randomly generated kernels.
        # python -m pirate_frb dev random_kernels --cdd2

        kernels += [
            # (dtype, dd_rank, Wmax, Tinner, subband_counts, et_levels)
('fp32', 3, 4, 4, [4, 1, 1], [0]),
('fp32', 6, 16, 1, [2, 5, 3, 1], [0]),
('fp32', 7, 16, 1, [2, 5, 3, 1], [0, 1]),     # continuation
('fp32', 3, 4, 2, [3, 1, 1], [0]),
('fp16', 5, 16, 1, [3, 1, 0, 1], [0, 2]),
('fp16', 6, 16, 1, [3, 1, 0, 1], [0]),     # continuation
('fp32', 6, 4, 2, [3, 7, 0, 1], [0, 2, 3]),
('fp32', 7, 4, 2, [3, 7, 0, 1], [0, 2]),     # continuation
('fp16', 4, 2, 1, [1, 3, 1], [0, 1]),
('fp16', 5, 2, 1, [1, 3, 1], [0]),     # continuation
('fp32', 7, 8, 2, [15, 10, 5, 1, 1], [0, 2, 3]),
('fp32', 8, 8, 2, [15, 10, 5, 1, 1], [0, 4, 1]),     # continuation
('fp32', 3, 16, 4, [4, 1, 1], [0]),
('fp16', 7, 1, 4, [15, 1, 1, 3, 1], [0, 2, 1]),
('fp16', 8, 1, 4, [15, 1, 1, 3, 1], [0, 4, 1]),     # continuation
        ]


    # ------------------------------------------------------------------------------
    #
    # Kernels with pf_rank < dd_rank1. These used to be a separate generator,
    # xdm_cdd2_kernels(), behind an 'xdm_kernels' flag; both are gone and these rows
    # are emitted unconditionally, like the baseline rows at the top.
    #
    # Widens 'python -m pirate_frb test --cdd2' coverage of the pf_rank < dd_rank1 code path
    # (see cuda_generator/Dedisperser.emit_subband_extraction()) to cells the lists above do
    # not reach.
    #
    # Those lists reach the path on their own: every early-trigger row does. Between them
    # they cover xdm_rank 1 and 2, in both dtypes, at dd_rank 3..7, including pf_rank == 0
    # (where every register's compile-time lag is zero). What they do NOT cover, and the seven
    # below do:
    #
    #   - dd_rank == 8 with xdm_rank > 0 -- the largest geometry, both stages of rank 4 (six
    #     of the seven);
    #   - xdm_rank >= 3;
    #   - dd_rank == 7 in float32 with xdm_rank > 0.
    #
    # A cdd2 compile is expensive, so the rest of the (dd_rank, pf_rank) grid is behind
    # debug_cdd2_kernels. (The sbdd half of the same feature IS swept exhaustively in every
    # build -- see xdm_sbdd_kernels() -- so the "extra DM" lag logic, which sbdd and cdd2
    # share via class Dedisperser, always has full coverage. What these seven add on top is
    # the peak-finder half: the m_ext = (m << xdm_rank) | mu input indexing.)
    #
    # This list used to carry two more rows -- fp32 (dd_rank 5, (2,1)) and (dd_rank 4, (1,))
    # -- whose stated purpose was to pair a nonzero xdm_rank with (Dcore, Dout, Tinner)
    # values the always-on lists never use. The Dout invariant deletes that purpose, so they
    # were removed. They were NOT redundant: each contributed one unique registry key, and
    # the pair cost 4 .cu files. So this list no longer reaches dd_rank < 7, and fp32
    # xdm_rank coverage at dd_rank 4 and 5 now comes only from the early-trigger rows of the
    # ladders in autogenerated_cdd2_kernels(). Re-add them (at Dout = 2^dd_rank1) if that
    # turns out to matter.

    kernels += [
        # dtype  dd  Wmax Tinner subband_counts  et_levels        (pf_rank, xdm_rank, M_ext)
        ('fp32', 8, 16,  1,     (3,2,1),        [0]),  # (2,2,44) canonical case, omits two bands
        ('fp16', 8,  8,  2,     (3,2,1),        [0]),  # (2,2,44) float16 at dd_rank 8: odd lags
                                                       #          take _advance1()'s f16_align path
        ('fp32', 8, 16,  1,     (1,),           [0]),  # (0,4,16) max xdm_rank, every lambda zero
        ('fp16', 8,  8,  2,     (2,1),          [0]),  # (1,3,32) odd lags, small M
        ('fp32', 8, 16,  1,     (3,3,2,1),      [0]),  # (3,1,50) largest M_ext
        ('fp32', 7, 16,  1,     (3,2,1),        [0]),  # (2,2,44) unequal stage ranks (3,4)
        ('fp32', 8, 16,  1,     (1,2,1),        [0]),  # (2,2,36) subband_counts[0]=1, so this
                                                       #          searches the same band set as the
                                                       #          shipped (0,0,1,2,1) kernel,
                                                       #          differently indexed
    ]

    # Every row above has dd_rank 7 or 8, hence dd_rank1 = 4, Dout = 16 and Dcore = 8. Every
    # M_ext except 16 is therefore a non-multiple of Dcore, which is what exercises
    # PeakFinder.process_pf_input()'s "dummy pfx registers for M <= m < Mpad" path.

    if debug_cdd2_kernels:
        # The rest of the grid: every (dd_rank, pf_rank) cell with pf_rank < dd_rank1, in both
        # dtypes. Cycle through subband_counts[0] = 0, 1, max as the cell varies, since that
        # is the parameter which decides how many bands the kernel omits relative to the
        # pf_rank == dd_rank1 kernel a caller would otherwise have to use.
        shapes = {
            0: [ (1,) ],
            1: [ (0,1), (1,1), (2,1) ],
            2: [ (0,2,1), (1,2,1), (3,2,1) ],
            3: [ (0,3,2,1), (1,3,2,1), (3,3,2,1) ]
        }

        for dd_rank in range(3, 9):
            dd_rank1 = dd_rank - (dd_rank // 2)
            for pf_rank in range(dd_rank1):
                s = shapes[pf_rank]
                sc = s[(dd_rank + pf_rank) % len(s)]
                kernels += [ ('fp32', dd_rank, 16, 1, sc, [0]) ]
                kernels += [ ('fp16', dd_rank,  8, 2, sc, [0]) ]

        # A few (Wmax, Tinner) variants, to vary the peak-finder's internal blocking against
        # a fixed M_ext. (Dcore and Dout used to vary here too; the Dout invariant ties both
        # to dd_rank, so Wmax and Tinner are what is left.)
        kernels += [
            ('fp32', 8,  4, 1, (3,2,1), [0]),
            ('fp32', 8,  1, 1, (3,2,1), [0]),
            ('fp16', 8, 32, 4, (3,2,1), [0]),
            ('fp16', 6,  4, 4, (2,2,1), [0]),
        ]


    for dtype, dd_rank0, Wmax, Tinner, subband_counts, et_levels in kernels:
        for et_level in et_levels:
            dd_rank = dd_rank0 - et_level

            # NOTE Dout and Dcore are not chosen here, or anywhere else in this file: the
            # CoalescedDdKernel2 constructor derives both from dd_rank. See
            # cuda_generator.cdd2_dout() for why that is an invariant rather than a default.
            sbc = cuda_generator.FrequencySubbands.restrict_subband_counts(subband_counts, et_level)

            # Every constraint a row can violate, checked in one place. Reported here rather
            # than left to the generator, which would raise a bare AssertionError naming no
            # kernel. 'pirate_frb dev random_kernels --cdd2' calls the same function, so a
            # freshly generated row cannot land here and fail.
            err = cuda_generator.check_cdd2_params(dtype, dd_rank, sbc, Wmax, Tinner)
            if err is not None:
                raise RuntimeError(f"autogenerated_cdd2_kernels: row (dtype={dtype},"
                                   f" dd_rank={dd_rank0}, Wmax={Wmax}, Tinner={Tinner},"
                                   f" subband_counts={tuple(subband_counts)}, et_levels={et_levels})"
                                   f" is not usable: {err}")

            fs = cuda_generator.FrequencySubbands(subband_counts = sbc)
            cdd2 = cuda_generator.CoalescedDdKernel2(dtype, dd_rank, fs, Wmax, Tinner)
            yield cdd2


def autogenerated_sbdd_kernels():
    """
    Generates objects of type 'cuda_generator.SbDedisperser'.
    Duplicates are okay here (they'll be caught later, see 'duplicate_checker' above.)
    """

    # One sbdd kernel per cdd2 kernel, so that sbdd coverage automatically tracks cdd2
    # coverage (and the two lists can't drift). The correspondence is total: SbDedisperser
    # requires (dd_rank >= 3) and (fs.pf_rank <= dd.rank1), which are exactly the constraints
    # CoalescedDdKernel2 enforces on the same two arguments (both via Dedisperser).
    #
    # Note that the sbdd registry key is only (dd_rank, subband_counts) -- no dtype, Wmax,
    # Dcore, Dout or Tinner -- so the float16 and float32 cdd2 variants of a tree, and all
    # of its Wmax values, collapse onto a single sbdd kernel. Currently this yields 89
    # objects, which dedupe to 29 distinct kernels.
    #
    # (There is deliberately no 'debug_sbdd_kernels' flag: debug_cdd2_kernels already widens
    # both. The two loops below are where sbdd-only coverage goes -- kernels with no cdd2
    # counterpart, which is how to widen sbdd without paying for the much more expensive
    # cdd2 compiles.)

    for cdd2 in autogenerated_cdd2_kernels():
        yield cuda_generator.SbDedisperser(cdd2.dd_rank, cdd2.frequency_subbands)

    # The sbdd-only loops anticipated above.
    if varmap_kernels:
        for sbdd in varmap_sbdd_kernels():
            yield sbdd

    for sbdd in xdm_sbdd_kernels():
        yield sbdd


def xdm_sbdd_kernels():
    """
    Generates objects of type 'cuda_generator.SbDedisperser', with pf_rank < dd_rank1.

    Duplicates (with each other, or with autogenerated_sbdd_kernels()) are okay here.
    """

    # An sbdd kernel with pf_rank < dd_rank1 emits (dd_rank1 - pf_rank) "extra DM" bits per
    # warp, and applies a compile-time lag to each register to convert the shared memory
    # ringbuf's lag into the one ReferenceTree wants (see
    # Dedisperser.emit_subband_extraction()). That lag logic is what
    # 'python -m pirate_frb test --sbdd' checks against ReferenceTree.
    #
    # We sweep the whole grid -- every pf_rank below dd_rank1, at every dd_rank the two-stage
    # dedisperser supports -- which is 18 cells, or 30 kernels with the two shapes below.
    # That is affordable because an sbdd compile is much cheaper than the cdd2 compile for the
    # same shape; the corresponding cdd2 grid is sampled instead (see the pf_rank < dd_rank1
    # section of autogenerated_cdd2_kernels()).
    # The production configs reach only a handful of these cells, all at pf_rank >= 1.
    #
    # Two shapes per cell, at the two ends of the subband_counts[0] range. Taking it as large
    # as the shape allows maximizes the number of level-0 ("unstaggered") outputs the kernel
    # must stagger against the extra-DM index; taking it to be zero is the opposite extreme,
    # where the kernel emits no level-0 outputs at all.

    shapes = {
        0: [ [1] ],
        1: [ [2,1], [0,1] ],
        2: [ [3,2,1], [0,2,1] ],
        3: [ [3,3,2,1], [0,3,2,1] ]
    }

    for dd_rank in range(3, 9):
        dd_rank1 = dd_rank - (dd_rank // 2)

        for pf_rank in range(dd_rank1):
            for subband_counts in shapes[pf_rank]:
                fs = cuda_generator.FrequencySubbands(subband_counts = subband_counts)
                yield cuda_generator.SbDedisperser(dd_rank, fs)


def varmap_sbdd_kernels():
    """
    Generates objects of type 'cuda_generator.SbDedisperser', for 'pirate_frb varmap bf'.

    Duplicates (with each other, or with autogenerated_sbdd_kernels()) are okay here.
    """

    # The variance map A (notes/variance_map.tex, section "The variance map") is computed
    # by sweeping one-hot inputs through the dedispersion stages. That needs an sbdd kernel for
    # the config's (dd_rank, subband_counts), and nothing else -- in particular no cdd2 kernel,
    # which is why this list can be much wider than the one in autogenerated_cdd2_kernels()
    # without a comparable compile-time cost.
    #
    # Coverage is a small ladder in "how subbanded" the tree is, at every dd_rank that
    # 'variance_map' can be pointed at. Absent this, the tool silently falls back to its CPU
    # sweep, which is ~60x slower (13 s vs 0.2 s at tree rank 10, 400 channels) and becomes
    # hours at production rank -- so a missing kernel does not fail loudly, it just makes a
    # region of parameter space too slow to explore.
    #
    # dd_rank 3..8 covers tree rank 5..16 (dd_rank = ceil(r/2) with no early trigger), i.e.
    # subscale through CHIME (r=15) and CHORD (r=16).

    for dd_rank in range(3, 9):
        # SbDedisperser requires len(subband_counts) == pf_rank+1, and the last entry to be 1.
        pf_rank = (dd_rank+1) // 2

        # The ladder, in units of "levels below pf_rank that carry subbands". Entry 0 is the
        # no-subband case N=1 (M = 2^pf_rank), which is the one 'variance_map' uses most --
        # the variance map tex notes' first milestone is stated for a single unsubbanded tree. The rest
        # bracket the shipped configs: at pf_rank=4 they are N = 1, 2, 5, 9 against N = 3 for
        # chime_sb1, 16 for chime_sb2 and 25 for chord_sb2.
        shapes = [ [0]*pf_rank + [1] ]

        if pf_rank >= 1:
            shapes += [ [0]*(pf_rank-1) + [1,1] ]
        if pf_rank >= 2:
            shapes += [ [0]*(pf_rank-2) + [2,2,1] ]
        if pf_rank >= 3:
            shapes += [ [0]*(pf_rank-3) + [3,3,2,1] ]

        for subband_counts in shapes:
            fs = cuda_generator.FrequencySubbands(subband_counts = subband_counts)
            yield cuda_generator.SbDedisperser(dd_rank, fs)

    # Every tree of every shipped config, so that 'varmap bf' runs on
    # configs/dedispersion/*.yml regardless of whether production_kernels is set. These are
    # duplicates when production_kernels=True, which is harmless.
    #
    # DERIVED from PRODUCTION_TREES rather than hand-copied. The hand-copied version drifted:
    # it was missing (1,2,2,2,1) entirely (chord_sb1.yml), and it approximated the
    # early-trigger trees as "dd_rank in [7,8]", which misses every tree of chime_sb2_et.yml
    # and chord_sb2_et.yml below dd_rank 7. Since a missing sbdd kernel does not fail loudly
    # -- it silently falls back to the ~60x slower CPU sweep -- that drift was invisible.
    #
    # The restriction below is the same tree rule autogenerated_cdd2_kernels() applies, so
    # this set is exactly the sbdd half of what production_kernels would have compiled.

    for dd_rank, subband_counts, et_levels in PRODUCTION_TREES:
        for et_level in et_levels:
            sbc = cuda_generator.FrequencySubbands.restrict_subband_counts(subband_counts, et_level)
            fs = cuda_generator.FrequencySubbands(subband_counts = sbc)
            yield cuda_generator.SbDedisperser(dd_rank - et_level, fs)


def autogenerated_pf_weight_reader_kernels():
    """
    Generates objects of type 'cuda_generator.PfWeightReader'.
    Duplicates are okay here (they'll be caught later, see 'duplicate_checker' above.)
    """

    if not debug_pfwr_kernels:
        return
    
    # Add some randomly generated kernels.
    # python -m pirate_frb dev random_kernels --pfwr

    # (dtype, subband_counts, Dcore, P, Tinner)
    kernels = [
        ('fp32', (2,1,1), 1, 14, 16),
        ('fp16', (7,6,2,1), 8, 10, 2),
        ('fp32', (0,2,1), 1, 1, 4),
        ('fp16', (4,0,1,1), 2, 5, 1),
        ('fp32', (3,2,1), 1, 5, 32),
        ('fp16', (14,4,4,0,1), 8, 3, 2),
        ('fp16', (13,7,3,0,1), 4, 3, 4),
        ('fp16', (3,2,1), 2, 7, 32),
        ('fp32', (6,5,1,1,1), 4, 2, 4),
        ('fp32', (4,3,1,1), 2, 2, 8),
        ('fp32', (3,2,1), 8, 5, 4),
        ('fp16', (1,1,1), 4, 2, 1),
        ('fp32', (9,4,0,2,1), 16, 8, 1),
        ('fp32', (0,2,1), 1, 8, 2),
        ('fp32', (3,0,1), 1, 6, 1)
    ]

    for (dtype, subband_counts, Dcore, P, Tinner) in kernels:
        fs = cuda_generator.FrequencySubbands(subband_counts = subband_counts)
        yield cuda_generator.PfWeightReader(fs, dtype, Dcore, P, Tinner)


def autogenerated_pf_output_kernels():
    """
    Generates objects of type 'cuda_generator.PfOutput'.
    Duplicates are okay here (they'll be caught later, see 'duplicate_checker' above.)
    """

    # In this case, we can enumerate all valid parameter choices
    # (i.e. no need to randomly generate kernels).

    if not debug_pfo_kernels:
        return
    
    for (dtype,Lmin) in [ ('float',0), ('__half',1) ]:
        for L in range(Lmin, 6):
            yield cuda_generator.PfOutput(dtype, Dout=2**L)


####################################################################################################


if __name__ == '__main__':
    main()
