# This Makefile will be invoked by the python build system (e.g. via 'pip install'),
# but you can also build individual targets by invoking 'make' directly.

# A note on how to add new source files:
#
#   include/pirate/.*hpp            -> add to HFILES below (only needed for pip/pypi)
#   src_lib/*.cu                    -> add to LIB_SRCFILES below
#   pirate_frb/*.py                 -> add to PYFILES below (only needed for pip/pypi)
#   pirate_frb/cuda_generator/*.py  -> add to CUDAGEN_PYFILES below
#
# Autogenerated kernels (src_lib/autogenerated_kernels/*.cu) are not listed in the Makefile.
# Instead, see 'makefile_helper.py', which procedurally generates all autogenerated kernels
# (by filename), and passes the list of filenames to the Makefile.

# Disable built-in rules and variables (must be first).
MAKEFLAGS += --no-builtin-rules 
MAKEFLAGS += --no-builtin-variables

# Default target 'all' must be first target in Makefile.
# The 'lib' target builds the C++ library lib/libpirate.so, and the python extension pirate_frb/pirate_pybind11...so.
# The 'build_wheel' and 'build_sdist' targets are invoked by 'pip' (or 'make all').
all: lib build_wheel build_sdist

.PHONY: all lib build_wheel build_sdist autogenerated_kernels clean


####################################################################################################
#
# Variables encoding configuration: PYTHON, NVCC, NVCC_ARCH, NVCC_DEPFLAGS.
#
# FIXME some day I'll define a configure-script mechanism for setting these variables.
# For now, if you want to change the defaults, just edit the Makfile.

PYTHON ?= python3
NVCC ?= nvcc -std=c++17 -m64 -O3 -lineinfo --use_fast_math --compiler-options -Wall,-fPIC,-march=x86-64-v3

# If using a conda env, add -I$(CONDA_PREFIX)/include to nvcc flags.
ifneq ($(CONDA_PREFIX),)
CONDA_INCFLAGS = -I$(CONDA_PREFIX)/include
endif

# Extra nvcc flags needed to build Makefile dependencies
#   -MMD create dep file, omitting "system" headers
#   -MP add phony target for each header in dep file (makes error reporting less confusing)
# Note: we don't need "-MT $@", since we use in-tree object filenames (x.cu -> x.o).
# Note: we don't need "-MT $*.d", since we use in-tree depfile names (x.cu -> x.d).
NVCC_DEPFLAGS ?= -MMD -MP

# NVIDIA archictecture.
DEFAULT_NVCC_ARCH = -gencode arch=compute_80,code=sm_80
DEFAULT_NVCC_ARCH += -gencode arch=compute_86,code=sm_86
DEFAULT_NVCC_ARCH += -gencode arch=compute_89,code=sm_89
# DEFAULT_ARCH += -gencode arch=compute_90,code=sm_90
NVCC_ARCH ?= $(DEFAULT_NVCC_ARCH)


####################################################################################################
#
# "Derived" config variables:
#   - PYTHON_INCDIR
#   - NUMPY_INCDIR
#   - PYBIND11_INCDIR
#   - PYEXT_SUFFIX
#   - KSGPU_DIR
#   - AUTOGENERATED_KERNELS
#
# These are autogenerated by makefile_helper.py, and cached in makefile_helper.out.
# PYEXT_SUFFIX is something like .cpython-312-x86_64-linux-gnu.so.


ifneq ($(MAKECMDGOALS),clean)
  include makefile_helper.out
endif

makefile_helper.out: makefile_helper.py Makefile
	$(PYTHON) makefile_helper.py


####################################################################################################


# The main output of the build process is these two libraries.
# Reminder: PYEXT_SUFFIX is something like .cpython-312-x86_64-linux-gnu.so.
PIRATE_LIB := lib/libpirate.so
PIRATE_PYEXT := pirate_frb/pirate_pybind11$(PYEXT_SUFFIX)

# These get compiled into lib/libpirate.so.
LIB_SRCFILES = \
  src_lib/BandwidthTracker.cu \
  src_lib/CasmBeamformer.cu \
  src_lib/ChimeDedisperser.cu \
  src_lib/DedispersionBuffer.cu \
  src_lib/DedispersionConfig.cu \
  src_lib/DedispersionKernelParams.cu \
  src_lib/DedispersionPlan.cu \
  src_lib/FakeCorrelator.cu \
  src_lib/FakeServer.cu \
  src_lib/GpuDedisperser.cu \
  src_lib/GpuDedispersionKernel.cu \
  src_lib/GpuLaggedDownsamplingKernel.cu \
  src_lib/LaggedDownsamplingKernelParams.cu \
  src_lib/PeakFindingKernel.cu \
  src_lib/ReferenceDedisperser.cu \
  src_lib/ReferenceDedispersionKernel.cu \
  src_lib/ReferenceLagbuf.cu \
  src_lib/ReferenceLaggedDownsamplingKernel.cu \
  src_lib/ReferenceTree.cu \
  src_lib/RingbufCopyKernel.cu \
  src_lib/TreeGriddingKernel.cu \
  src_lib/YamlFile.cu \
  src_lib/file_utils.cu \
  src_lib/network_utils.cu \
  src_lib/system_utils.cu \
  src_lib/test_gpu_peak_finding_kernel.cu \
  src_lib/time_gpu_dedispersion_kernels.cu \
  src_lib/time_gpu_lagged_downsampling_kernels.cu \
  src_lib/time_gpu_peak_finding_kernels.cu \
  src_lib/utils.cu \
  src_lib/loose_ends/cpu_downsample.cu \
  src_lib/loose_ends/gpu_downsample.cu \
  src_lib/loose_ends/gpu_transpose.cu \
  src_lib/loose_ends/test_avx256_m64_outbuf.cu \
  src_lib/loose_ends/test_cpu_downsampler.cu \
  src_lib/loose_ends/test_gpu_downsample.cu \
  src_lib/loose_ends/test_gpu_reduce2.cu \
  src_lib/loose_ends/test_gpu_transpose.cu \
  src_lib/loose_ends/time_cpu_downsample.cu \
  src_lib/loose_ends/time_gpu_downsample.cu \
  src_lib/loose_ends/time_gpu_transpose.cu \
  src_lib/autogenerated_kernels/debug.cu

# These get compiled into pirate_frb/pirate_pybind11....so.
PYEXT_SRCFILES = \
  src_pybind11/pirate_pybind11.cu

# Must list all python source files here.
# (Otherwise they won't show up in 'pip install' or pypi.)
PYFILES = \
  pirate_frb/__init__.py \
  pirate_frb/__main__.py \
  pirate_frb/CasmReferenceBeamformer.py \
  pirate_frb/Dense1dBeamformer.py \
  pirate_frb/FakeCorrelator.py \
  pirate_frb/FakeServer.py \
  pirate_frb/Hardware.py

# Python source files in the 'pirate_frb.cuda_generator' submodule are listed separately.
# Any changes to these files will trigger recompilation of all autogenerated kernels!
# FIXME it would be nice to have more granular dependencies for autogenerated kernels.

CUDAGEN_PYFILES = \
  pirate_frb/cuda_generator/__init__.py \
  pirate_frb/cuda_generator/Dedisperser.py \
  pirate_frb/cuda_generator/FrequencySubbands.py \
  pirate_frb/cuda_generator/Kernel.py \
  pirate_frb/cuda_generator/PeakFinder.py \
  pirate_frb/cuda_generator/PeakFinder2.py \
  pirate_frb/cuda_generator/Ringbuf.py \
  pirate_frb/cuda_generator/utils.py

# Must list all header files here.
# (Otherwise they won't show up in 'pip install' or pypi.)
HFILES = \
  include/pirate/CasmBeamformer.hpp \
  include/pirate/Dedisperser.hpp \
  include/pirate/DedispersionBuffer.hpp \
  include/pirate/DedispersionConfig.hpp \
  include/pirate/DedispersionKernel.hpp \
  include/pirate/DedispersionPlan.hpp \
  include/pirate/FakeCorrelator.hpp \
  include/pirate/FakeServer.hpp \
  include/pirate/KernelRegistry.hpp \
  include/pirate/LaggedDownsamplingKernel.hpp \
  include/pirate/ReferenceLagbuf.hpp \
  include/pirate/ReferenceTree.hpp \
  include/pirate/RingbufCopyKernel.hpp \
  include/pirate/TreeGriddingKernel.hpp \
  include/pirate/YamlFile.hpp \
  include/pirate/constants.hpp \
  include/pirate/file_utils.hpp \
  include/pirate/inlines.hpp \
  include/pirate/network_utils.hpp \
  include/pirate/system_utils.hpp \
  include/pirate/tests.hpp \
  include/pirate/timing.hpp \
  include/pirate/trackers.hpp \
  include/pirate/utils.hpp \
  include/pirate/loose_ends/avx256_downsample.hpp \
  include/pirate/loose_ends/bitvec.hpp \
  include/pirate/loose_ends/cpu_downsample.hpp \
  include/pirate/loose_ends/DownsampleKernel.hpp \
  include/pirate/loose_ends/gpu_downsample.hpp \
  include/pirate/loose_ends/gpu_transpose.hpp \
  include/pirate/loose_ends/m128_outbuf.hpp \
  include/pirate/loose_ends/m64_outbuf.hpp \
  include/pirate/loose_ends/reduce2.hpp \
  include/pirate/loose_ends/TransposeKernel.hpp

# 'make clean' deletes {*~, *.o, *.d, *.so, *.pyc} from these dirs.
CLEAN_DIRS := . lib src_lib src_lib/loose_ends src_lib/template_instantiations src_lib/autogenerated_kernels src_pybind11 pirate_frb pirate_frb/__pycache__ pirate_frb/cuda_generator/__pycache__ include include/pirate include/pirate/loose_ends include/pirate/cuda_kernels

# Extra files to be deleted by 'make clean'.
# Note that 'pirate_frb/include' and 'pirate_frb/lib' are symlinks, so we put them in CLEAN_FILES, not CLEAN_RMDIRS
CLEAN_FILES := sdist_files.txt wheel_files.txt makefile_helper.out pirate_frb/include pirate_frb/lib $(AUTOGENERATED_KERNELS)

# Directories that should be empty at the end of 'make clean', and can be deleted.
CLEAN_RMDIRS := lib pirate_frb/__pycache__ pirate_frb/cuda_generator/__pycache__

####################################################################################################


LIB_OFILES := $(LIB_SRCFILES:%.cu=%.o) $(AUTOGENERATED_KERNELS:%.cu=%.o)
PYEXT_OFILES := $(PYEXT_SRCFILES:%.cu=%.o)

# Must include all .d files, or build will break!
ALL_SRCFILES := $(LIB_SRCFILES) $(PYEXT_SRCFILES) $(AUTOGENERATED_KERNELS)
DEPFILES := $(ALL_SRCFILES:%.cu=%.d)

# Note that autogenerated .cu files are not included in the sdist.
SDIST_FILES := pyproject.toml Makefile makefile_helper.py autogenerate_kernel.py vendorize.py
SDIST_FILES += $(PYFILES) $(CUDAGEN_PYFILES) $(LIB_SRCFILES) $(PYEXT_SRCFILES) $(HFILES)

# Some symlinks for the wheel:
#  - header file include/%.hpp gets symlinked to pirate_frb/include/%.hpp
#  - library lib/libpirate.so gets symlinked to pirate_frb/lib/libpirate.so
#  - python extension pirate_frb/pirate_pybind11...so does not need to be symlinked/renamed.
WHEEL_FILES := $(PYFILES) $(CUDAGEN_PYFILES) $(PIRATE_PYEXT) pirate_frb/$(PIRATE_LIB)
WHEEL_FILES += $(HFILES:%=pirate_frb/%)

# Phony targets. The special targets 'build_wheel' and 'build_sdist' are needed by pip/pipmake.
lib: $(PIRATE_LIB) $(PIRATE_PYEXT)
build_wheel: wheel_files.txt $(PIRATE_LIB) $(PIRATE_PYEXT)
build_sdist: sdist_files.txt

# Symlink {include,lib} into python directory 'pirate_frb'.
pirate_frb/include:
	ln -sf ../include $@
pirate_frb/lib:
	ln -sf ../lib $@

# Build object files in src_lib/ with default flags.
%.o: %.cu %.d
	$(NVCC) $(NVCC_ARCH) $(NVCC_DEPFLAGS) -I$(KSGPU_DIR)/include $(CONDA_INCFLAGS) -c -o $@ $<

# Build object files in src_pybind11/ with special flags.
src_pybind11/%.o: src_pybind11/%.cu src_pybind11/%.d
	$(NVCC) $(NVCC_ARCH) $(NVCC_DEPFLAGS) -I$(KSGPU_DIR)/include -I$(PYTHON_INCDIR) -I$(NUMPY_INCDIR) -I$(PYBIND11_INCDIR) $(CONDA_INCFLAGS) -c -o $@ $<

# Source files in 'src_lib/autogenerated_kernels' are created using './autogenerate_kernel.py'...
src_lib/autogenerated_kernels/%.cu: autogenerate_kernel.py $(CUDAGEN_PYFILES)
	@mkdir -p src_lib/autogenerated_kernels
	$(PYTHON) autogenerate_kernel.py $@

# ... except for 'src_lib/autogenerated_kernels/debug.cu', which is a "hook" for debugging.
src_lib/autogenerated_kernels/debug.cu:
	touch $@

# Build the C++ library (lib/libpirate.so)
# We want it to automatically pull in the C++ library $(KSGPU_DIR)/lib/libkspgu.so.
#
# The python extension has been built correctly if 'objdump -x' shows the following:
#   NEEDED   libksgpu.so
#   RUNPATH  $(KSGPU_DIR)/lib    # where Makefile var $(KSGPU_DIR) is read from makefile_helper.out
#
# The quoting can be understood by working backwards as follows:
#  - g++ command line should look like:   g++ -Wl,-rpath="$(KSGPU_DIR)/lib"
#  - nvcc command line should look like:  nvcc -Xcompiler '"-Wl,-rpath=$(KSGPU_DIR)/lib"'

$(PIRATE_LIB): $(LIB_OFILES)
	@mkdir -p lib
	$(NVCC) $(NVCC_ARCH) -shared -o $@ $^ -lksgpu -lyaml-cpp -L$(KSGPU_DIR)/lib -Xcompiler '"-Wl,-rpath=$(KSGPU_DIR)/lib"'

# Build the python extension (pirate_frb/pirate_pybind11...so)
# We want it to automatically pull in the C++ library pirate_frb/lib/libpirate.so.
#
# The python extension has been built correctly if 'objdump -x' shows the following:
#   NEEDED   libpirate.so
#   RUNPATH  $ORIGIN/lib
#
# The quoting can be understood by working backwards as follows:
#  - g++ command line should look like:   g++ -Wl,-rpath="\$ORIGIN/lib"
#  - nvcc command line should look like:  nvcc -Xcompiler '"-Wl,-rpath=\\$ORIGIN/lib"'
#  - Makefile line should look like:      nvcc -Xcompiler '"-Wl,-rpath=\\$$ORIGIN/lib"'
#
# Note that we don't link to libksgpu.so or ksgpu_pybind11...so in this step.
# These libraries end up getting imported as follows:
#
#  1. When 'pirate_frb' is imported, we do 'import ksgpu' (in pirate_frb/__init__.py)
#     before 'import pirate_pybind11'.
#
#  2. When 'ksgpu' is imported, we use the "ctypes trick" (see comment in ksgpu/__init__.py)
#     to load the libraries libksgpu.so and ksgpu_pybind11...so with globally visible symbols.

$(PIRATE_PYEXT): $(PYEXT_OFILES) $(PIRATE_LIB) pirate_frb/lib
	$(NVCC) $(NVCC_ARCH) -shared -o $@ $(PYEXT_OFILES) -lpirate -Lpirate_frb/lib -Xcompiler '"-Wl,-rpath=\\$$ORIGIN/lib"'

autogenerated_kernels: $(AUTOGENERATED_KERNELS)

# Needed by pip/pipmake: list of all files that go into the (non-editable) wheel.
wheel_files.txt: Makefile pirate_frb/include pirate_frb/lib
	rm -f $@
	for f in $(WHEEL_FILES); do echo $$f; done >>$@

# Needed by pip/pipmake: list of all files that go into the sdist.
sdist_files.txt: Makefile
	rm -f $@
	for f in $(SDIST_FILES); do echo $$f; done >>$@

clean:
	@for f in $(foreach d,$(CLEAN_DIRS),$(wildcard $d/*~ $d/*.o $d/*.d $d/*.so $d/*.pyc)); do echo rm $$f; rm $$f; done
	@for f in $(wildcard src_lib/autogenerated_kernels/dd_fp*.cu); do echo rm $$f; rm $$f; done
	@for f in $(wildcard src_lib/autogenerated_kernels/pf_weight_reader_test_fp*.cu); do echo rm $$f; rm $$f; done
	@for f in $(wildcard src_lib/autogenerated_kernels/pf_output2_test_fp*.cu); do echo rm $$f; rm $$f; done
	@for f in $(wildcard src_lib/autogenerated_kernels/pf_fp*.cu); do echo rm $$f; rm $$f; done
	@for f in $(wildcard $(CLEAN_FILES)); do echo rm $$f; rm $$f; done
	@for d in $(wildcard $(CLEAN_RMDIRS)); do echo rmdir $$d; rmdir $$d; done

# Specifying .SECONDARY with no prerequisites disables auto-deletion of intermediate files.
.SECONDARY:

# If a depfile is absent, build can still proceed.
$(DEPFILES):

# Include any depfiles which are present.
include $(wildcard $(DEPFILES))
