#!/usr/bin/env python
#
# This script is invoked by the Makefile, to generate "derived" Makefile variables:
#
#   - PYTHON_INCDIR
#   - NUMPY_INCDIR
#   - PYBIND11_INCDIR
#   - PYEXT_SUFFIX
#   - KSGPU_DIR
#   - AUTOGENERATED_KERNELS
#
# Values of these variables are written to makefile_helper.out.


import io
import os
import sys
import sysconfig
import importlib.util

try:
    import pybind11
except:
    raise RuntimeError("Couldn't import pybind11 -- this is a fatal error")

try:
    import numpy
except:
    raise RuntimeError("Couldn't import numpy -- this is a fatal error")


# This way of getting KSGPU_DIR is awkward, but avoids importing 'ksgpu'.
# (This is useful since imports can generate unexpected output.)

ksgpu_spec = importlib.util.find_spec('ksgpu')
if ksgpu_spec is None:
    raise RuntimeError("Couldn't find 'ksgpu' package -- this is a fatal error")


####################################################################################################

        
def generate_kernel_filenames():
    # Dedispersion kernels.
    # (Most of the logic is in generate_dedispersion_kernels(), see below.)
    for (dtype, ilag, irb, orb, nspec) in generate_dedispersion_kernels():
        assert dtype in [ 'fp16', 'fp32' ]
        yield f'src_lib/autogenerated_kernels/dd_{dtype}_ilag{ilag:d}_irb{irb:d}_orb{orb:d}_s{nspec}.cu'

    # Peak-finding kernels.
    # (Most of the logic is in generate_peak_finding_kernels(), see below.)
    for (dtype, M, E, Dout, Dcore, W, BlocksPerSM) in set(generate_peak_finding_kernels()):
        if Dcore is None:
            Dcore = min(Dout, 8)
        yield f'src_lib/autogenerated_kernels/pf_{dtype}_M{M}_E{E}_Dout{Dout}_Dcore{Dcore}_W{W}_B{BlocksPerSM}.cu'


def generate_dedispersion_kernels():
    """
    Generates tuples (dtype, ilag, irb, orb, nspec), where:

       - dtype is 'fp16' or 'fp32'
       - ilag = apply_input_residual_lags
       - irb = input_is_ringbuf
       - orb = output_is_ringbuf
       - nspec = number of spectator indices
    """
    
    # Debug
    # yield ('fp16', True, False, False, 1)
    # return

    for dtype in [ 'fp32', 'fp16' ]:
        for (ilag,orb) in [ (False,False), (True,False), (False,True) ]:    # apply_input_residual_lags, output_is_ringbuf
            irb = False                 # input_is_ringbuf (not supported yet)
            nspec = 1                   # number of spectator indices (not supported yet)
            yield dtype, ilag, irb, orb, nspec

        
def generate_peak_finding_kernels():
    """
    Generates tuples (dtype, M, E, Dout, Dcore, W, BlocksPerSM).
    Duplicates are okay, and Dcore=None is okay.
    """

    # Debug
    # yield ('fp16', 1, 2, 1, 1, 4, 4)   # (M, E, Dout, Dcore, W, BlocksPerSM)
    # return

    W = 4
    BlocksPerSM = 4
    
    for dtype in [ 'fp16', 'fp32' ]:
        # "Corners" of parameter space
        for M in [1,32]:
            for E in [1,32]:
                for Dout in [1,32]:
                    if (M, E, Dout) == (32, 32, 1):
                        continue  # This one is problematic -- huge compile time.
                    yield (dtype, M, E, Dout, None, W, BlocksPerSM)

        # Kernels that we're likely to use in CHIME/CHORD without subbanding
        for M in [1,2,4,8,16]:
            Dout = M
            for E in [ (16//M), (32//M) ]:
                yield (dtype, M, E, Dout, None, W, BlocksPerSM)                

        # These kernels are timed in src_lib/time_gpu_peak_finding_kernels.cu
        yield (dtype, 16, 32, 16, None, W, BlocksPerSM)
        yield (dtype, 50, 32, 16, None, W, BlocksPerSM)

        # Testing these kernels (in addition to those above) should cover
        # all code paths in PfReducer.
        for M in range(1,17):
            yield (dtype, M, 32, 16, 8, W, BlocksPerSM)
            

####################################################################################################


s = io.StringIO()
print("# Autogenerated by makefile_helper.py (which is automatically invoked by the Makefile)\n", file=s)

python_incdir = sysconfig.get_config_var('INCLUDEPY')
print("# Include directory for python headers", file=s)
print("# From sysconfig.get_config_var('INCLUDEPY')", file=s)
print(f"PYTHON_INCDIR = {python_incdir}\n", file=s)

numpy_incdir = numpy.get_include()
print("# Include directory for numpy headers", file=s)
print("# From numpy.get_include()", file=s)
print(f"NUMPY_INCDIR = {numpy_incdir}\n", file=s)

pybind11_incdir = pybind11.get_include()
print("# Include directory for pybind11 headers", file=s)
print("# From pybind11.get_include()", file=s)
print(f"PYBIND11_INCDIR = {pybind11_incdir}\n", file=s)

pyext_suffix = sysconfig.get_config_var('EXT_SUFFIX')
print("# Filename suffix for python extension modules", file=s)
print("# From sysconfig.get_config_var('EXT_SUFFIX')", file=s)
print("# Equivalent to 'python3-config --extension-suffix'", file=s)
print(f"PYEXT_SUFFIX = {pyext_suffix}\n", file=s)

ksgpu_dir = os.path.dirname(ksgpu_spec.origin)
print("# Base directory for 'ksgpu' package", file=s)
print("# From importlib.util.find_spec('ksgpu').origin", file=s)
print(f"KSGPU_DIR = {ksgpu_dir}\n", file=s)

print("# CUDA kernels that will be autogenerated (with ./autogenerate_kernel.py)", file=s)
print('AUTOGENERATED_KERNELS =', end='', file=s)
for k in generate_kernel_filenames():
    print(f' \\\n    {k}', end='', file=s)
print(file=s)

s = s.getvalue()
outfile = 'makefile_helper.out'
print(f'Writing {outfile}')

with open(outfile,'w') as f:
    print(s, file=f, end='')

# Show summary on stdout (for debugging).
if False:
    for line in s.split('\n'):
        if (len(line) > 0) and (line[0] != '#'):
            print('   ', line)
