# This Makefile will be invoked by the python build system (e.g. via 'pip install'),
# but you can also build individual targets by invoking 'make' directly.
#
# A note on how to add new source files:
#
#   include/pirate/.*hpp            -> add to HFILES below (only needed for pip/pypi)
#   src_lib/*.cu                    -> add to LIB_SRCFILES below
#   pirate_frb/*.py                 -> add to PYFILES below (only needed for pip/pypi)
#   pirate_frb/cuda_generator/*.py  -> add to CUDAGEN_PYFILES below
#
# Autogenerated kernels (src_lib/autogenerated_kernels/*.cu) are not listed in the Makefile.
# Instead, see 'makefile_helper.py', which procedurally generates all autogenerated kernels
# (by filename), and passes the list of filenames to the Makefile.

# Disable built-in rules and variables (must be first).
MAKEFLAGS += --no-builtin-rules 
MAKEFLAGS += --no-builtin-variables

# Default target 'all' must be first target in Makefile.
# The 'lib' target builds the C++ library lib/libpirate.so, and the python extension pirate_frb/pirate_pybind11...so.
# The 'build_wheel' and 'build_sdist' targets are invoked by 'pip' (or 'make all').
all: lib build_wheel build_sdist


.PHONY: all lib build_wheel build_sdist clean docs docs-clean docs-serve pybind11 autogenerated_kernels gddk gpfk pfom pfwr cdd2 help grpc

# Help target
help:
	@echo "Pirate Makefile - Available targets:"
	@echo ""
	@echo "Main build targets:"
	@echo "  all              - Build everything (default): lib + wheel + sdist"
	@echo "  lib              - Build C++ library (lib/libpirate.so) and Python extension"
	@echo "  build_wheel      - Build wheel files (called by pip)"
	@echo "  build_sdist      - Build source distribution (called by pip)"
	@echo "  clean            - Remove all build artifacts"
	@echo ""
	@echo "Documentation targets (note that sphinx documentation is currently a placeholder)"
	@echo "  docs             - Build sphinx documentation (HTML)"
	@echo "  docs-clean       - Remove generated documentation"
	@echo "  docs-serve       - Build and serve docs at http://localhost:8000"
	@echo ""
	@echo "Development targets:"
	@echo "  pybind11         - Compile all pybind11 object files (but not final .so)"
	@echo "  grpc             - Generate C++ and Python files from .proto"
	@echo ""
	@echo "Autogenerated kernel targets:"
	@echo "  autogenerated_kernels  - Generate all .cu files for autogenerated kernels"
	@echo "  gddk             - Build dedispersion kernels (dd_fp*.o)"
	@echo "  gpfk             - Build peak-finding kernels (pf_fp*.o)"
	@echo "  pfom             - Build peak-finding output microkernels (pf_output_fp*.o)"
	@echo "  pfwr             - Build peak-finding weight reader microkernels (pf_weight_reader*.o)"
	@echo "  cdd2             - Build coalesced dedisperser + peak-finder kernels (cdd2_fp*.o)"


# Documentation targets
docs:
	$(MAKE) -C docs html

docs-clean:
	rm -rf docs/build docs/source/notes docs/source/configs docs/source/_cli_generated.md

docs-serve: docs
	@echo "Starting documentation server at http://localhost:8000"
	@cd docs/build/html && python3 -m http.server


####################################################################################################
#
# Variables encoding configuration: PYTHON, NVCC, NVCC_ARCH, NVCC_DEPFLAGS.
#
# FIXME some day I'll define a configure-script mechanism for setting these variables.
# For now, if you want to change the defaults, just edit the Makfile.

PYTHON ?= python3

# To time nvcc invocations, prepend: time -f "   %e seconds"
NVCC ?= nvcc -std=c++17 -m64 -O3 -lineinfo --use_fast_math --compiler-options -Wall,-fPIC,-march=x86-64-v3

# If using a conda env, add include and lib paths.
ifneq ($(CONDA_PREFIX),)
CONDA_INCFLAGS = -I$(CONDA_PREFIX)/include
CONDA_LIBFLAGS = -L$(CONDA_PREFIX)/lib
endif

# Extra nvcc flags needed to build Makefile dependencies
#   -MMD create dep file, omitting "system" headers
#   -MP add phony target for each header in dep file (makes error reporting less confusing)
# Note: we don't need "-MT $@", since we use in-tree object filenames (x.cu -> x.o).
# Note: we don't need "-MT $*.d", since we use in-tree depfile names (x.cu -> x.d).
NVCC_DEPFLAGS ?= -MMD -MP

# NVIDIA archictecture.
DEFAULT_NVCC_ARCH = -gencode arch=compute_80,code=sm_80
DEFAULT_NVCC_ARCH += -gencode arch=compute_86,code=sm_86
DEFAULT_NVCC_ARCH += -gencode arch=compute_89,code=sm_89
# DEFAULT_ARCH += -gencode arch=compute_90,code=sm_90
NVCC_ARCH ?= $(DEFAULT_NVCC_ARCH)


####################################################################################################
#
# gRPC code generation.
# The .proto file generates both C++ files (in grpc/) and Python stubs (in pirate_frb/rpc/grpc/).

# For now, there is only one .proto file, but more will be added later.
GRPC_PROTO := grpc/frb_search.proto

# Sentinel files used in build process (convenient for multi-target commands)
GRPC_SENTINELS = $(GRPC_PROTO:%.proto=%.protoc_cpp_sentinel) 
GRPC_SENTINELS += $(GRPC_PROTO:%.proto=%.protoc_python_sentinel) 

# C++ generated files (protobuf message classes + gRPC service stubs)
GRPC_HFILES = $(GRPC_PROTO:%.proto=%.pb.h) 
GRPC_HFILES += $(GRPC_PROTO:%.proto=%.grpc.pb.h) 
GRPC_CCFILES = $(GRPC_PROTO:%.proto=%.pb.cc) 
GRPC_CCFILES += $(GRPC_PROTO:%.proto=%.grpc.pb.cc) 

# Python generated files (protobuf message classes + gRPC service stubs)
GRPC_PYFILES = $(GRPC_PROTO:grpc/%.proto=pirate_frb/rpc/grpc/%_pb2.py)
GRPC_PYFILES += $(GRPC_PROTO:grpc/%.proto=pirate_frb/rpc/grpc/%_pb2_grpc.py)

# FrbServer.cpp includes gRPC headers, so must be generated first
src_lib/FrbServer.o: $(GRPC_HFILES)


####################################################################################################
#
# "Derived" config variables:
#   - PYTHON_INCDIR
#   - NUMPY_INCDIR
#   - PYBIND11_INCDIR
#   - PYEXT_SUFFIX
#   - KSGPU_DIR
#   - AUTOGENERATED_KERNELS
#
# These are autogenerated by makefile_helper.py, and cached in makefile_helper.out.
# PYEXT_SUFFIX is something like .cpython-312-x86_64-linux-gnu.so.


ifneq ($(MAKECMDGOALS),help)
ifneq ($(MAKECMDGOALS),clean)
  include makefile_helper.out
endif
endif

makefile_helper.out: makefile_helper.py Makefile
	$(PYTHON) makefile_helper.py


####################################################################################################


# The main output of the build process is these two libraries.
# Reminder: PYEXT_SUFFIX is something like .cpython-312-x86_64-linux-gnu.so.
PIRATE_LIB := lib/libpirate.so
PIRATE_PYEXT := pirate_frb/pirate_pybind11$(PYEXT_SUFFIX)

# These get compiled into lib/libpirate.so.
# Autogenerated source files (either by pirate_frb/cuda_generator or grpc) aren't listed here.
# Note: .cpp files are pure C++ (or C++ using only CUDA runtime API), compiled by nvcc forwarding to host compiler.
# Note: .cu files contain actual CUDA kernels (__global__ functions) and must be compiled by nvcc's CUDA frontend.

# asdf-cxx source files (Erik Schnetter's ASDF library, compiled directly into libpirate.so)
ASDF_CXX_SRCFILES = \
  asdf-cxx/src/asdf.cxx \
  asdf-cxx/src/byteorder.cxx \
  asdf-cxx/src/config.cxx \
  asdf-cxx/src/datatype.cxx \
  asdf-cxx/src/entry.cxx \
  asdf-cxx/src/io.cxx \
  asdf-cxx/src/ndarray.cxx \
  asdf-cxx/src/reference.cxx \
  asdf-cxx/src/table.cxx

LIB_SRCFILES = \
  src_lib/AssembledFrame.cpp \
  src_lib/Barrier.cpp \
  src_lib/BumpAllocator.cpp \
  src_lib/CasmBeamformer.cu \
  src_lib/CoalescedDdKernel2.cu \
  src_lib/CudaEventRingbuf.cpp \
  src_lib/CudaStreamPool.cpp \
  src_lib/DedispersionBuffer.cpp \
  src_lib/DedispersionConfig.cpp \
  src_lib/DedispersionKernel.cu \
  src_lib/DedispersionPlan.cpp \
  src_lib/HwtestSender.cpp \
  src_lib/Hwtest.cpp \
  src_lib/FakeXEngine.cpp \
  src_lib/FileWriter.cpp \
  src_lib/FrbServer.cpp \
  src_lib/FrequencySubbands.cpp \
  src_lib/GpuDedisperser.cpp \
  src_lib/GpuDequantizationKernel.cu \
  src_lib/GpuLaggedDownsamplingKernel.cu \
  src_lib/LaggedDownsamplingKernelParams.cpp \
  src_lib/MegaRingbuf.cpp \
  src_lib/PeakFindingKernel.cu \
  src_lib/Receiver.cpp \
  src_lib/ReferenceDedisperser.cpp \
  src_lib/ReferenceLagbuf.cpp \
  src_lib/ReferenceLaggedDownsamplingKernel.cpp \
  src_lib/ReferenceTree.cpp \
  src_lib/ResourceTracker.cpp \
  src_lib/RingbufCopyKernel.cu \
  src_lib/TreeGriddingKernel.cu \
  src_lib/YamlFile.cpp \
  src_lib/file_utils.cpp \
  src_lib/network_utils.cpp \
  src_lib/scratch.cu \
  src_lib/SlabAllocator.cpp \
  src_lib/system_utils.cpp \
  src_lib/utils.cpp \
  src_lib/XEngineMetadata.cpp \
  src_lib/loose_ends/cpu_downsample.cpp \
  src_lib/loose_ends/gpu_downsample.cu \
  src_lib/loose_ends/gpu_transpose.cu \
  src_lib/loose_ends/test_avx256_m64_outbuf.cpp \
  src_lib/loose_ends/test_cpu_downsampler.cpp \
  src_lib/loose_ends/test_gpu_downsample.cpp \
  src_lib/loose_ends/test_gpu_reduce2.cu \
  src_lib/loose_ends/test_gpu_transpose.cpp \
  src_lib/loose_ends/time_cpu_downsample.cpp \
  src_lib/loose_ends/time_gpu_downsample.cpp \
  src_lib/loose_ends/time_gpu_transpose.cpp \
  src_lib/autogenerated_kernels/debug.cu

# These get compiled into pirate_frb/pirate_pybind11....so.
PYEXT_SRCFILES = \
  src_pybind11/pirate_pybind11.cpp \
  src_pybind11/pirate_pybind11_core.cpp \
  src_pybind11/pirate_pybind11_kernels.cpp \
  src_pybind11/pirate_pybind11_casm.cpp \
  src_pybind11/pirate_pybind11_loose_ends.cpp

# Must list all python source files here.
# (Otherwise they won't show up in 'pip install' or pypi.)
# Note: gRPC-generated files (frb_search_pb2*.py) are in GRPC_PYFILES, not here.
PYFILES = \
  pirate_frb/__init__.py \
  pirate_frb/__main__.py \
  pirate_frb/HwtestSender.py \
  pirate_frb/Hwtest.py \
  pirate_frb/Hardware.py \
  pirate_frb/pybind11_injections.py \
  pirate_frb/run_server.py \
  pirate_frb/yaml_utils.py \
  pirate_frb/casm/__init__.py \
  pirate_frb/casm/CasmReferenceBeamformer.py \
  pirate_frb/casm/Dense1dBeamformer.py \
  pirate_frb/core/__init__.py \
  pirate_frb/core/AnalyticDedisperser.py \
  pirate_frb/kernels/__init__.py \
  pirate_frb/loose_ends/__init__.py \
  pirate_frb/tests/__init__.py \
  pirate_frb/tests/test_assembled_frame_allocator.py \
  pirate_frb/utils/__init__.py \
  pirate_frb/utils/ThreadAffinity.py \
  pirate_frb/utils/time_cupy_dedisperser.py \
  pirate_frb/utils/show_asdf.py \
  pirate_frb/rpc/__init__.py \
  pirate_frb/rpc/FrbClient.py \
  pirate_frb/rpc/grpc/__init__.py

# Python source files in the 'pirate_frb.cuda_generator' submodule are listed separately.
# Any changes to these files will trigger recompilation of all autogenerated kernels!
# FIXME it would be nice to have more granular dependencies for autogenerated kernels.

CUDAGEN_PYFILES = \
  pirate_frb/cuda_generator/__init__.py \
  pirate_frb/cuda_generator/CoalescedDdKernel2.py \
  pirate_frb/cuda_generator/Dedisperser.py \
  pirate_frb/cuda_generator/Dtype.py \
  pirate_frb/cuda_generator/FrequencySubbands.py \
  pirate_frb/cuda_generator/Kernel.py \
  pirate_frb/cuda_generator/PeakFinder.py \
  pirate_frb/cuda_generator/Ringbuf.py \
  pirate_frb/cuda_generator/utils.py

# Must list all header files here.
# (Otherwise they won't show up in 'pip install' or pypi.)
HFILES = \
  include/pirate/AssembledFrame.hpp \
  include/pirate/Barrier.hpp \
  include/pirate/BumpAllocator.hpp \
  include/pirate/CasmBeamformer.hpp \
  include/pirate/CoalescedDdKernel2.hpp \
  include/pirate/constants.hpp \
  include/pirate/CudaEventRingbuf.hpp \
  include/pirate/CudaStreamPool.hpp \
  include/pirate/Dedisperser.hpp \
  include/pirate/DedispersionBuffer.hpp \
  include/pirate/DedispersionConfig.hpp \
  include/pirate/DedispersionKernel.hpp \
  include/pirate/DedispersionPlan.hpp \
  include/pirate/DedispersionTree.hpp \
  include/pirate/HwtestSender.hpp \
  include/pirate/Hwtest.hpp \
  include/pirate/FakeXEngine.hpp \
  include/pirate/file_utils.hpp \
  include/pirate/FileWriter.hpp \
  include/pirate/FrbServer.hpp \
  include/pirate/FrequencySubbands.hpp \
  include/pirate/GpuDequantizationKernel.hpp \
  include/pirate/inlines.hpp \
  include/pirate/KernelRegistry.hpp \
  include/pirate/LaggedDownsamplingKernel.hpp \
  include/pirate/MegaRingbuf.hpp \
  include/pirate/network_utils.hpp \
  include/pirate/PeakFindingKernel.hpp \
  include/pirate/Receiver.hpp \
  include/pirate/ReferenceLagbuf.hpp \
  include/pirate/ReferenceTree.hpp \
  include/pirate/ResourceTracker.hpp \
  include/pirate/RingbufCopyKernel.hpp \
  include/pirate/SlabAllocator.hpp \
  include/pirate/system_utils.hpp \
  include/pirate/TreeGriddingKernel.hpp \
  include/pirate/utils.hpp \
  include/pirate/XEngineMetadata.hpp \
  include/pirate/YamlFile.hpp \
  include/pirate/loose_ends/avx256_downsample.hpp \
  include/pirate/loose_ends/bitvec.hpp \
  include/pirate/loose_ends/cpu_downsample.hpp \
  include/pirate/loose_ends/DownsampleKernel.hpp \
  include/pirate/loose_ends/gpu_downsample.hpp \
  include/pirate/loose_ends/gpu_transpose.hpp \
  include/pirate/loose_ends/m128_outbuf.hpp \
  include/pirate/loose_ends/m64_outbuf.hpp \
  include/pirate/loose_ends/reduce2.hpp \
  include/pirate/loose_ends/tests.hpp \
  include/pirate/loose_ends/timing.hpp \
  include/pirate/loose_ends/TransposeKernel.hpp

# 'make clean' deletes {*~, *.o, *.d, *.so, *.pyc} from these dirs.
CLEAN_DIRS := . lib src_lib src_lib/loose_ends src_lib/template_instantiations src_lib/autogenerated_kernels src_pybind11 grpc pirate_frb pirate_frb/__pycache__ pirate_frb/casm pirate_frb/casm/__pycache__ pirate_frb/core pirate_frb/core/__pycache__ pirate_frb/kernels pirate_frb/kernels/__pycache__ pirate_frb/loose_ends pirate_frb/loose_ends/__pycache__ pirate_frb/utils pirate_frb/utils/__pycache__ pirate_frb/cuda_generator/__pycache__ pirate_frb/rpc pirate_frb/rpc/__pycache__ pirate_frb/rpc/grpc pirate_frb/rpc/grpc/__pycache__ include include/pirate include/pirate/loose_ends include/pirate/cuda_kernels asdf-cxx/src

# Extra files to be deleted by 'make clean'.
# Note that 'pirate_frb/include' and 'pirate_frb/lib' are symlinks, so we put them in CLEAN_FILES, not CLEAN_RMDIRS
# Note that asdf-cxx/include/asdf/config.hxx is generated from misc/asdf_cxx_config.hxx
CLEAN_FILES := sdist_files.txt wheel_files.txt makefile_helper.out pirate_frb/include pirate_frb/lib $(AUTOGENERATED_KERNELS) $(GRPC_CCFILES) $(GRPC_HFILES) $(GRPC_PYFILES) $(GRPC_SENTINELS) asdf-cxx/include/asdf/config.hxx

# Directories that should be empty at the end of 'make clean', and can be deleted.
# Note: pirate_frb/rpc and pirate_frb/rpc/grpc are not on this list, since they contain __init__.py.
CLEAN_RMDIRS := lib pirate_frb/__pycache__ pirate_frb/casm/__pycache__ pirate_frb/core/__pycache__ pirate_frb/kernels/__pycache__ pirate_frb/loose_ends/__pycache__ pirate_frb/utils/__pycache__ pirate_frb/cuda_generator/__pycache__ pirate_frb/rpc/__pycache__ pirate_frb/rpc/grpc/__pycache__

####################################################################################################


AUTOGENERATED_OFILES := $(AUTOGENERATED_KERNELS:%.cu=%.o)
GRPC_OFILES := $(GRPC_CCFILES:%.cc=%.o)
ASDF_CXX_OFILES := $(ASDF_CXX_SRCFILES:%.cxx=%.o)

# Convert .cu, .cpp, .cc, and .cxx source files to .o object files
LIB_OFILES_CU := $(filter %.cu,$(LIB_SRCFILES))
LIB_OFILES_CPP := $(filter %.cpp,$(LIB_SRCFILES))
LIB_OFILES := $(LIB_OFILES_CU:%.cu=%.o) $(LIB_OFILES_CPP:%.cpp=%.o) $(AUTOGENERATED_OFILES) $(GRPC_OFILES) $(ASDF_CXX_OFILES)

PYEXT_OFILES_CU := $(filter %.cu,$(PYEXT_SRCFILES))
PYEXT_OFILES_CPP := $(filter %.cpp,$(PYEXT_SRCFILES))
PYEXT_OFILES := $(PYEXT_OFILES_CU:%.cu=%.o) $(PYEXT_OFILES_CPP:%.cpp=%.o)

# Must include all .d files, or build will break!
ALL_SRCFILES := $(LIB_SRCFILES) $(PYEXT_SRCFILES) $(AUTOGENERATED_KERNELS) $(GRPC_CCFILES) $(ASDF_CXX_SRCFILES)
ALL_SRCFILES_CU := $(filter %.cu,$(ALL_SRCFILES))
ALL_SRCFILES_CPP := $(filter %.cpp,$(ALL_SRCFILES))
ALL_SRCFILES_CC := $(filter %.cc,$(ALL_SRCFILES))
ALL_SRCFILES_CXX := $(filter %.cxx,$(ALL_SRCFILES))
DEPFILES := $(ALL_SRCFILES_CU:%.cu=%.d) $(ALL_SRCFILES_CPP:%.cpp=%.d) $(ALL_SRCFILES_CC:%.cc=%.d) $(ALL_SRCFILES_CXX:%.cxx=%.d)

# Note that autogenerated files are not included in the sdist.
SDIST_FILES := pyproject.toml Makefile makefile_helper.py autogenerate_kernel.py vendorize.py
SDIST_FILES += $(PYFILES) $(CUDAGEN_PYFILES) $(LIB_SRCFILES) $(PYEXT_SRCFILES) $(HFILES) $(GRPC_PROTO)

# Some symlinks for the wheel:
#  - header file include/%.hpp gets symlinked to pirate_frb/include/%.hpp
#  - library lib/libpirate.so gets symlinked to pirate_frb/lib/libpirate.so
#  - python extension pirate_frb/pirate_pybind11...so does not need to be symlinked/renamed.
WHEEL_FILES := $(PYFILES) $(CUDAGEN_PYFILES) $(GRPC_PYFILES) $(PIRATE_PYEXT) pirate_frb/$(PIRATE_LIB)
WHEEL_FILES += $(HFILES:%=pirate_frb/%)

# Phony targets. The special targets 'build_wheel' and 'build_sdist' are needed by pip/pipmake.
lib: $(PIRATE_LIB) $(PIRATE_PYEXT)
build_wheel: wheel_files.txt $(PIRATE_LIB) $(PIRATE_PYEXT)
build_sdist: sdist_files.txt

# Symlink {include,lib} into python directory 'pirate_frb'.
pirate_frb/include:
	ln -sf ../include $@
pirate_frb/lib:
	ln -sf ../lib $@

# Build object files from .cu files (CUDA kernels)
%.o: %.cu %.d
	$(NVCC) $(NVCC_ARCH) $(NVCC_DEPFLAGS) -Iasdf-cxx/include -I$(KSGPU_DIR)/include $(CONDA_INCFLAGS) -c -o $@ $<

# Build object files from .cpp files (pure C++, forwarded to host compiler by nvcc)
%.o: %.cpp %.d
	$(NVCC) $(NVCC_ARCH) $(NVCC_DEPFLAGS) -x c++ -Iasdf-cxx/include -I$(KSGPU_DIR)/include $(CONDA_INCFLAGS) -c -o $@ $<

# Build object files from .cc files (e.g. protoc-generated gRPC files)
%.o: %.cc %.d
	$(NVCC) $(NVCC_ARCH) $(NVCC_DEPFLAGS) -x c++ -I$(KSGPU_DIR)/include $(CONDA_INCFLAGS) -c -o $@ $<

# Build object files from .cxx files (asdf-cxx library)
%.o: %.cxx %.d
	$(NVCC) $(NVCC_ARCH) $(NVCC_DEPFLAGS) -x c++ -Iasdf-cxx/include -I$(KSGPU_DIR)/include $(CONDA_INCFLAGS) -c -o $@ $<

# Build object files in src_pybind11/ from .cu files with special flags.
src_pybind11/%.o: src_pybind11/%.cu src_pybind11/%.d
	$(NVCC) $(NVCC_ARCH) $(NVCC_DEPFLAGS) -I$(KSGPU_DIR)/include -I$(PYTHON_INCDIR) -I$(NUMPY_INCDIR) -I$(PYBIND11_INCDIR) $(CONDA_INCFLAGS) -c -o $@ $<

# Build object files in src_pybind11/ from .cpp files with special flags.
src_pybind11/%.o: src_pybind11/%.cpp src_pybind11/%.d
	$(NVCC) $(NVCC_ARCH) $(NVCC_DEPFLAGS) -x c++ -I$(KSGPU_DIR)/include -I$(PYTHON_INCDIR) -I$(NUMPY_INCDIR) -I$(PYBIND11_INCDIR) $(CONDA_INCFLAGS) -c -o $@ $<

# Source files in 'src_lib/autogenerated_kernels' are created using './autogenerate_kernel.py'...
src_lib/autogenerated_kernels/%.cu: autogenerate_kernel.py $(CUDAGEN_PYFILES)
	@mkdir -p src_lib/autogenerated_kernels
	$(PYTHON) autogenerate_kernel.py $@

# ... except for 'src_lib/autogenerated_kernels/debug.cu', which is a "hook" for debugging.
src_lib/autogenerated_kernels/debug.cu:
	touch $@

####################################################################################################
#
# asdf-cxx config generation.
# The config.hxx file is generated by copying from misc/asdf_cxx_config.hxx.
# This avoids using cmake to generate the config file.

asdf-cxx/include/asdf/config.hxx: misc/asdf_cxx_config.hxx
	cp $< $@

# All asdf-cxx object files depend on the generated config.hxx
$(ASDF_CXX_OFILES): asdf-cxx/include/asdf/config.hxx

####################################################################################################
#
# gRPC code generation rules (pattern rules for any grpc/*.proto file).
# Generates C++ files in grpc/ and Python stubs in pirate_frb/rpc/grpc/.

# Phony target to regenerate all gRPC files
grpc: $(GRPC_CCFILES) $(GRPC_HFILES) $(GRPC_PYFILES)

# Generate C++ protobuf and gRPC files from .proto
# We use a sentinel file so that protoc runs exactly once, even though it produces 4 output files.
# Note: $* is the stem (the part matched by %).
grpc/%.protoc_cpp_sentinel: grpc/%.proto
	protoc --cpp_out=grpc --grpc_out=grpc \
	  --plugin=protoc-gen-grpc=$$(which grpc_cpp_plugin) \
	  -I grpc $*.proto
	touch $@

# All generated C++ files depend on the sentinel (empty recipe indicates side-effect files)
grpc/%.pb.cc grpc/%.pb.h: grpc/%.protoc_cpp_sentinel ;
grpc/%.grpc.pb.cc grpc/%.grpc.pb.h: grpc/%.protoc_cpp_sentinel ;

# Generate Python protobuf and gRPC stubs from .proto
# We use a sentinel file so that grpc_tools.protoc runs exactly once.
# protoletariat (protol) fixes imports to use relative imports within the package.
grpc/%.protoc_python_sentinel: grpc/%.proto
	@mkdir -p pirate_frb/rpc/grpc
	$(PYTHON) -m grpc_tools.protoc \
	  -I grpc \
	  --python_out=pirate_frb/rpc/grpc \
	  --grpc_python_out=pirate_frb/rpc/grpc \
	  $*.proto
	protol --create-package --in-place --python-out pirate_frb/rpc/grpc protoc --proto-path grpc $*.proto
	touch $@

# All generated Python files depend on the sentinel (empty recipe indicates side-effect files)
pirate_frb/rpc/grpc/%_pb2.py: grpc/%.protoc_python_sentinel ;
pirate_frb/rpc/grpc/%_pb2_grpc.py: grpc/%.protoc_python_sentinel ;

####################################################################################################

# Build the C++ library (lib/libpirate.so)
# We want it to automatically pull in the C++ library $(KSGPU_DIR)/lib/libkspgu.so.
#
# The python extension has been built correctly if 'objdump -x' shows the following:
#   NEEDED   libksgpu.so
#   RUNPATH  $(KSGPU_DIR)/lib    # where Makefile var $(KSGPU_DIR) is read from makefile_helper.out
#
# The quoting can be understood by working backwards as follows:
#  - g++ command line should look like:   g++ -Wl,-rpath="$(KSGPU_DIR)/lib"
#  - nvcc command line should look like:  nvcc -Xcompiler '"-Wl,-rpath=$(KSGPU_DIR)/lib"'

# Note: depends on makefile_helper.out so that adding/removing autogenerated kernels triggers a relink.
# Libraries: ksgpu, yaml-cpp, grpc++, protobuf (asdf-cxx uses yaml-cpp which is already linked)
$(PIRATE_LIB): $(LIB_OFILES) $(GRPC_SENTINELS) makefile_helper.out
	@mkdir -p lib
	$(NVCC) $(NVCC_ARCH) -shared -o $@ $(LIB_OFILES) -lksgpu -lyaml-cpp -lgrpc++ -lprotobuf -L$(KSGPU_DIR)/lib $(CONDA_LIBFLAGS) -Xcompiler '"-Wl,-rpath=$(KSGPU_DIR)/lib"'

# Build the python extension (pirate_frb/pirate_pybind11...so)
# We want it to automatically pull in the C++ library pirate_frb/lib/libpirate.so.
#
# The python extension has been built correctly if 'objdump -x' shows the following:
#   NEEDED   libpirate.so
#   RUNPATH  $ORIGIN/lib
#
# The quoting can be understood by working backwards as follows:
#  - g++ command line should look like:   g++ -Wl,-rpath="\$ORIGIN/lib"
#  - nvcc command line should look like:  nvcc -Xcompiler '"-Wl,-rpath=\\$ORIGIN/lib"'
#  - Makefile line should look like:      nvcc -Xcompiler '"-Wl,-rpath=\\$$ORIGIN/lib"'
#
# Note that we don't link to libksgpu.so or ksgpu_pybind11...so in this step.
# These libraries end up getting imported as follows:
#
#  1. When 'pirate_frb' is imported, we do 'import ksgpu' (in pirate_frb/__init__.py)
#     before 'import pirate_pybind11'.
#
#  2. When 'ksgpu' is imported, we use the "ctypes trick" (see comment in ksgpu/__init__.py)
#     to load the libraries libksgpu.so and ksgpu_pybind11...so with globally visible symbols.

$(PIRATE_PYEXT): $(PYEXT_OFILES) $(PIRATE_LIB) pirate_frb/lib
	$(NVCC) $(NVCC_ARCH) -shared -o $@ $(PYEXT_OFILES) -lpirate -Lpirate_frb/lib -Xcompiler '"-Wl,-rpath=\\$$ORIGIN/lib"'

# Special targets for autogenerated kernels
#   - autogenerated kernels -> all .cu files
#   - gddk -> dd_fp*.o              (dedispersion kernels)
#   - gpfk -> pf_fp*.o              (peak-finding kernels)
#   - pfom -> pf_output_fp*.o       (peak-finding output microkernels)
#   - pfwr -> pf_weight_reader*.o   (peak-finding weight reader microkernels)
#   - cdd2 -> cdd2_fp*.o            (coalesced dedisperser + peak-finder kernels)

autogenerated_kernels: $(AUTOGENERATED_KERNELS)
gddk: $(filter src_lib/autogenerated_kernels/dd_fp%.o, $(AUTOGENERATED_OFILES))
gpfk: $(filter src_lib/autogenerated_kernels/pf_fp%.o, $(AUTOGENERATED_OFILES))
pfom: $(filter src_lib/autogenerated_kernels/pf_output_fp%.o, $(AUTOGENERATED_OFILES))
pfwr: $(filter src_lib/autogenerated_kernels/pf_weight_reader%.o, $(AUTOGENERATED_OFILES))
cdd2: $(filter src_lib/autogenerated_kernels/cdd2_fp%.o, $(AUTOGENERATED_OFILES))

# Special target for pybind11: compile all pybind11 .o files (but not the final .so)
pybind11: $(PYEXT_OFILES)

# Needed by pip/pipmake: list of all files that go into the (non-editable) wheel.
wheel_files.txt: Makefile pirate_frb/include pirate_frb/lib
	rm -f $@
	for f in $(WHEEL_FILES); do echo $$f; done >>$@

# Needed by pip/pipmake: list of all files that go into the sdist.
sdist_files.txt: Makefile
	rm -f $@
	for f in $(SDIST_FILES); do echo $$f; done >>$@

clean:
	@for f in $(foreach d,$(CLEAN_DIRS),$(wildcard $d/*~ $d/*.o $d/*.d $d/*.so $d/*.pyc)); do echo rm $$f; rm $$f; done
	@for f in $(wildcard src_lib/autogenerated_kernels/dd_fp*.cu); do echo rm $$f; rm $$f; done
	@for f in $(wildcard src_lib/autogenerated_kernels/pf_weight_reader_fp*.cu); do echo rm $$f; rm $$f; done
	@for f in $(wildcard src_lib/autogenerated_kernels/pf_output_fp*.cu); do echo rm $$f; rm $$f; done
	@for f in $(wildcard src_lib/autogenerated_kernels/pf_fp*.cu); do echo rm $$f; rm $$f; done
	@for f in $(wildcard src_lib/autogenerated_kernels/cdd2_fp*.cu); do echo rm $$f; rm $$f; done
	@for f in $(wildcard $(CLEAN_FILES)); do echo rm $$f; rm $$f; done
	@for d in $(wildcard $(CLEAN_RMDIRS)); do echo rmdir $$d; rmdir $$d; done

# Specifying .SECONDARY with no prerequisites disables auto-deletion of intermediate files.
.SECONDARY:

# If a depfile is absent, build can still proceed.
$(DEPFILES):

# Include any depfiles which are present.
include $(wildcard $(DEPFILES))
