#!/usr/bin/env python3

"""
This script was generated by the following prompt:

Please write a simple "vendorization" script which reads an input C++ file,
and writes an output C++ file which has been modified as follows:

  - A comment of the form "//i REST_OF_LINE" is replaced by "REST_OF_LINE"
    (the 'i' stands for "include" and means that the rest-of-line text is
    included in the output, but will be commented out in the input)

  - If "//x" appears on a line, then the entire line (including the part
    preceding the comment) does not appear in the output (the "x" stands
    for "exclude" and means that the line is excluded in the output)

  - If "//xbegin" appears, then all lines of text are omitted from the
    output, until "//xend" is reached. (The entire lines containing
    "//xbegin" and "//xend" are omitted from the output, as well as
    anything in between.)
"""

import sys

def vendorize(infile, outfile):
    skipping = False   # inside //xbegin ... //xend block?

    for line in infile:
        stripped = line.strip()

        # --- Handle xbegin/xend blocks ---
        if "//xbegin" in stripped:
            skipping = True
            continue    # omit this line entirely

        if "//xend" in stripped:
            skipping = False
            continue    # omit this line entirely

        if skipping:
            continue    # skip everything until xend

        # --- Handle //x — exclude entire line ---
        if "//x" in stripped:
            # BUT ignore //xbegin and //xend cases (already handled)
            # and ensure not to trigger on "//x" that comes from include lines
            # For simplicity, treat any "//x" as "exclude"
            continue

        # --- Handle //i INCLUDE behavior ---
        # Find a comment that starts with //i
        idx = line.find("//i")
        if idx != -1:
            # Include the rest of the line *after* the "//i "
            # Everything after "//i" (plus one space if present) is emitted.
            # Example:
            #   //i #include <something>
            # → #include <something>
            text_after = line[idx+3:]     # text after "//i"
            text_after = text_after[1:] if text_after.startswith(' ') else text_after
            outfile.write(text_after)
            continue

        # --- Default case: write line unchanged ---
        outfile.write(line)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: vendorize.py <input.cpp>")
        sys.exit(1)

    with open(sys.argv[1], "r", encoding="utf-8") as infile:
        vendorize(infile, sys.stdout)
        
