#ifndef _PIRATE_AVX2_UTILS_HPP
#define _PIRATE_AVX2_UTILS_HPP

// Note: this header is deliberately free of <immintrin.h> (and any AVX intrinsics), so it can be
// safely #included from .cu translation units. The AVX2 implementation lives in avx2_utils.cpp,
// which is compiled by the host compiler (nvcc's CUDA frontend chokes on <immintrin.h>).

namespace pirate {
#if 0
}  // editor auto-indent
#endif


// Simulates Gaussian random noise with rms=2.5 (this is the rms of the pre-quantized Gaussian;
// the int4 quantization and the [-7,7] clamp perturb the actual output rms slightly, to ~2.51).
// Quantizes to int4, clamped to [-7,7], i.e. the value -8 is not allowed.
// Quantization is +/- symmetric, i.e. 4-bit output value 0x1 corresponds to range [0.5,1.5].
// Packs the result into (nelts_4bit/2) bytes, or equivalently (nelts_4bit/8) uints.
// Throws an exception if nelts_4bit is not a multiple of 64 (convenient for simd alignment).
//
// Thread-safe: the rng state is per-thread (thread_local), initialized once per thread from
// std::random_device.

void avx2_simulate_4bit_noise(unsigned int *dst, long nelts_4bit);


// The rms of the PRE-quantization Gaussian generated by avx2_simulate_4bit_noise() (i.e. the
// noise is quantize_int4(avx2_4bit_prequant_noise_rms * g), g ~ N(0,1)). Callers that add a
// signal before quantizing (e.g. AssembledFrame::randomize with a SinglePulse) use this as the
// noise rms. Single source of truth for the "2.5" the generator's thresholds are built from.
constexpr float avx2_4bit_prequant_noise_rms = 2.5f;

// Returns the rms of the (post-quantization, clamped) int4 output of avx2_simulate_4bit_noise(),
// computed exactly from the quantization thresholds. Slightly larger than avx2_4bit_prequant_noise_rms
// (the int4 quantization adds variance ~1/12, partly offset by the [-7,7] clamp). Not for hot loops --
// recomputed from a length-15 sum (plus a sqrt) on each call.
double avx2_4bit_postquant_noise_rms();


// Unit test (dispatched from 'python -m pirate_frb test --sim'): generates noise, unpacks it, and
// checks the level histogram against the quantized-Gaussian(rms=2.5) distribution (and that the
// -8 sentinel never occurs). Throws on failure. Since seeding is from std::random_device, this
// checks the distribution statistically, not exact bytes.
void test_avx2_simulate_4bit_noise();

// Timing (dispatched from 'python -m pirate_frb time --sim'): reports avx2_simulate_4bit_noise()
// throughput for 1 thread and for 'nthreads' threads (as total and per-thread).
void time_avx2_simulate_4bit_noise(long nthreads);


}  // namespace pirate

#endif  // _PIRATE_AVX2_UTILS_HPP
