tree_rank: 16
num_downsampling_levels: 4
time_samples_per_chunk: 2048
uncompressed_dtype: float16
compressed_dtype: int8
early_triggers:
  - {ds_level: 1, tree_rank: 14}
  - {ds_level: 2, tree_rank: 13}
  - {ds_level: 2, tree_rank: 14}
  - {ds_level: 3, tree_rank: 12}
  - {ds_level: 3, tree_rank: 13}
  - {ds_level: 3, tree_rank: 14}
beams_per_gpu: 128
beams_per_batch: 2
num_active_batches: 2
gmem_nbytes_per_gpu: 34359738368  # 32 GB
