tree_rank: 15
num_downsampling_levels: 5
time_samples_per_chunk: 2048
uncompressed_dtype: float16
compressed_dtype: float16
early_triggers:
  - {ds_level: 1, tree_rank: 13}
  - {ds_level: 2, tree_rank: 12}
  - {ds_level: 2, tree_rank: 13}
  - {ds_level: 3, tree_rank: 11}
  - {ds_level: 3, tree_rank: 12}
  - {ds_level: 3, tree_rank: 13}
  - {ds_level: 4, tree_rank: 10}
  - {ds_level: 4, tree_rank: 11}
  - {ds_level: 4, tree_rank: 12}
  - {ds_level: 4, tree_rank: 13}
beams_per_gpu: 128
beams_per_batch: 2
num_active_batches: 2
gmem_nbytes_per_gpu: 34359738368  # 32 GB
