#!/usr/bin/env python3
"""Reproduce the real-time RFI mask saved in a CHIME acquisition, using the old pipeline.

    misc/chimefrb/01-reproduce-rfimask.py <acqdir> <rfi_chain.json> [-p PRESCALE] [--nfiles N] [-v]

    acqdir          directory of chunk_NNNNNNNN.msg files written by the CHIME L1 server,
                    e.g. /scratch/tweiss_rfi/frb_B0037+56_down3_2026-05-22-09-26/beam_3146
    rfi_chain.json  the jsonized RFI transform chain that the L1 server ran, e.g.
                    misc/chimefrb/configs/21-03-07-low-latency-uniform-badchannel-mask-noplot.json

Each file holds 1024 samples of raw 16K-channel intensity data, plus the RFI mask that the
L1 server computed from that data in real time, at the 1K resolution of the chain's
sub-pipeline.  This script runs the same chain, built from the same json by the old CHIME
code (rebuilt for this machine by misc/chimefrb/build_oldpipe.sh), on the raw data, and
compares the mask it gets with the saved one.  It prints the percentage of mask samples in
each of the four (saved, new) x (masked, unmasked) combinations.

The L1 server ran the chain in 4096-sample chunks aligned to ichunk % 4 == 0, so the
files are used in groups of four with that alignment: files at either end that do not
complete a group are dropped (and named), and the file sequence must have no gaps.

Needs the old pipeline built (misc/chimefrb/build_oldpipe.sh).  The work happens under the
old pipeline's python 2.7; invoked from python 3, the script re-executes itself there and
says so.  No pirate code is involved.

Exit status: 0 if the masks are identical, 2 if they differ, 1 for a usage or data error.
"""

from __future__ import print_function, division

import argparse
import json
import os
import re
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))          # misc/chimefrb
OLDPIPE = os.path.join(HERE, 'oldpipe')                    # the old-pipeline build, gitignored

NT = 1024                    # samples per file (ch_frb_io::constants::nt_per_assembled_chunk)
FILES_PER_RFI_CHUNK = 4      # the L1 server's RFI chunk is 4096 samples ('nt_align' in its config)
REALTIME_PRESCALE = 1.0e-4   # 'intensity_prescale' in ch_frb_l1/l1_configs/l1_production_8beam.yaml

FILENAME_RE = re.compile(r'^chunk_(\d{8})\.msg$')

# Positions in the 21-element array of a version-2 assembled_chunk msgpack file
# (ch_frb_io/assembled_chunk_msgpack.hpp).
MSG_NFIELDS = 21
MSG_VERSION = 1
MSG_BEAM_ID = 4
MSG_NUPFREQ = 5
MSG_FPGA_COUNTS_PER_SAMPLE = 7
MSG_FPGA_BEGIN = 11
MSG_BINNING = 13
MSG_NRFIFREQ = 18
MSG_HAS_RFI_MASK = 19
MSG_RFI_MASK = 20


def die(msg):
    print('ERROR: ' + msg, file=sys.stderr)
    sys.exit(1)


# -------------------------------------------------------------------------------------------------
#
# Stage 1 (python 3): hand over to the old pipeline's python 2.7.


def reexec_under_old_pipeline():
    """Replaces this process with the old pipeline's python 2.7 running the same command line.

    Does not return.  The old rf_pipelines exists only as a python 2.7 extension, so the real
    work must happen there, with oldpipe/env.sh sourced so that its libraries are found.
    """

    envsh = os.path.join(OLDPIPE, 'env.sh')
    if not os.path.exists(envsh):
        die("no old-pipeline build found at %s.\n"
            "       Run misc/chimefrb/build_oldpipe.sh first (about a minute)." % OLDPIPE)

    conda_env = None
    with open(envsh) as f:
        for line in f:
            m = re.match(r'export CHIMEFRB_ENV=(\S+)', line)
            if m:
                conda_env = m.group(1)
    if conda_env is None:
        die("could not find CHIMEFRB_ENV in %s; was it generated by build_oldpipe.sh?" % envsh)

    python2 = os.path.join(conda_env, 'bin', 'python')
    if not os.path.exists(python2):
        die("the old pipeline's conda env is missing (%s).\n"
            "       See 'Prerequisites' in misc/chimefrb/README.md." % conda_env)

    script = os.path.abspath(__file__)
    print("This script does its work under the old pipeline's python 2.7.  Re-executing as\n"
          "    . %s && %s %s ...\n" % (envsh, python2, script))
    sys.stdout.flush()

    # Lets stage 2 notice if the re-exec somehow did not land in python 2, instead of looping.
    os.environ['REPRODUCE_RFIMASK_REEXEC'] = '1'

    # In 'bash -c CMD ARG0 ARG1 ...', $0 is ARG0 and "$@" is ARG1 onwards.
    os.execvp('bash', ['bash', '-c', '. "$0" && exec "$@"', envsh, python2, script] + sys.argv[1:])


# -------------------------------------------------------------------------------------------------
#
# Stage 2 (python 2.7): imports.


def import_old_pipeline():
    """Imports numpy, msgpack and the old rf_pipelines, diagnosing whatever is missing."""

    global np, msgpack, rf_pipelines

    if not os.environ.get('OLDPIPE'):
        die("run this script with python 3 (it will re-execute itself under the old pipeline's\n"
            "       python 2.7), or source misc/chimefrb/oldpipe/env.sh first.")
    try:
        import numpy as np
        import msgpack
    except ImportError as e:
        die("%s.\n       The old pipeline's conda env is incomplete; see 'Prerequisites' in\n"
            "       misc/chimefrb/README.md." % e)
    try:
        import rf_pipelines
    except ImportError as e:
        die("import rf_pipelines failed: %s.\n"
            "       The build in %s looks stale or incomplete; rerun misc/chimefrb/build_oldpipe.sh." % (e, OLDPIPE))


# The two transforms below subclass the old rf_pipelines.wi_transform, which exists only in
# stage 2.  Stage 1 never instantiates them, so there they get a placeholder base class.
if sys.version_info[0] == 2:
    import_old_pipeline()
    _transform_base = rf_pipelines.wi_transform
else:
    _transform_base = object


# -------------------------------------------------------------------------------------------------
#
# The two transforms added to the chain.


class prescale_transform(_transform_base):
    """Multiplies the intensity by a constant, as the L1 server's network stream does when decoding.

    The old file stream has no prescale option, so the L1 server's 'intensity_prescale' (1e-4 in
    production) is applied here instead, one step later, as a separate transform.  The chain's
    mask does not depend on the intensity scale mathematically; this exists to keep the
    floating-point arithmetic in the same regime as the real-time run.
    """

    def __init__(self, prescale):
        rf_pipelines.wi_transform.__init__(self, 'prescale_transform')
        self.nt_chunk = NT
        self.prescale = np.float32(prescale)

    def _process_chunk(self, intensity, weights, pos):
        intensity *= self.prescale


class mask_comparator(_transform_base):
    """Compares (weights > 0) with the saved masks, one saved file per call, and accumulates counts.

    This goes right after the chain's last mask_counter, inside the 1K sub-pipeline, so that it
    sees exactly the weights that the L1 server's mask_counter packed into the saved files.
    With nt_chunk = 1024 at the sub-pipeline's native time resolution, call number i is saved
    file number i.

    After the run: 'counts' is the 2x2 array of sample counts indexed [saved][new], with 0 =
    masked and 1 = unmasked, and 'disagreements' lists (name, nsamples, nrows) for each file
    whose masks differ, nrows being the number of 1024-sample rows that differ in every sample.
    """

    def __init__(self, names, saved_masks, verbose):
        rf_pipelines.wi_transform.__init__(self, 'mask_comparator')
        self.nt_chunk = NT
        self.names = names
        self.saved_masks = saved_masks
        self.verbose = verbose
        self.ncalls = 0
        self.counts = np.zeros((2, 2), dtype=np.int64)
        self.disagreements = []
        self.t0 = time.time()

    def _process_chunk(self, intensity, weights, pos):
        if pos % NT != 0:
            raise RuntimeError('mask_comparator: pos=%d is not a multiple of %d' % (pos, NT))
        i = pos // NT
        if i >= len(self.names):
            raise RuntimeError('mask_comparator: the chain produced more chunks than there are saved files (%d)' % len(self.names))

        saved = unpack_mask(self.saved_masks[i])
        new = (weights > 0.0)
        if new.shape != saved.shape:
            raise RuntimeError('mask_comparator: shape mismatch, saved %s vs new %s' % (saved.shape, new.shape))

        n11 = np.count_nonzero(saved & new)
        n10 = np.count_nonzero(saved & ~new)
        n01 = np.count_nonzero(~saved & new)
        n00 = saved.size - n11 - n10 - n01
        self.counts += np.array([[n00, n01], [n10, n11]], dtype=np.int64)

        if n10 + n01 > 0:
            nrows = int(np.count_nonzero((saved != new).all(axis=1)))
            self.disagreements.append((self.names[i], n10 + n01, nrows))

        self.ncalls += 1
        if self.verbose:
            print('    %s: %d samples disagree (%d whole rows), unmasked fraction saved %.4f new %.4f'
                  % (self.names[i], n10 + n01, self.disagreements[-1][2] if n10 + n01 else 0, saved.mean(), new.mean()))
        elif self.ncalls % 200 == 0:
            print('    %d / %d files, %.0f s' % (self.ncalls, len(self.names), time.time() - self.t0))
            sys.stdout.flush()


def unpack_mask(packed):
    """(nfreq, NT/8) packed bytes -> (nfreq, NT) bool, True = unmasked.

    Bit i of byte j is sample 8j+i: rf_kernels::mask_counter packs least significant bit first,
    while numpy unpacks most significant bit first (numpy 1.16 has no bitorder= argument), so
    each byte's eight bits are reversed.
    """

    bits = np.unpackbits(packed[:, :, np.newaxis], axis=2)[:, :, ::-1]
    return bits.reshape(packed.shape[0], NT).astype(bool)


# -------------------------------------------------------------------------------------------------
#
# Inputs: the file list, the saved masks, the chain.


def list_files(acqdir):
    """Sorted (name, ichunk) pairs for the chunk_NNNNNNNN.msg files in acqdir; dies if any ichunk is skipped."""

    if not os.path.isdir(acqdir):
        die('%s is not a directory' % acqdir)

    pairs = []
    for name in sorted(os.listdir(acqdir)):
        m = FILENAME_RE.match(name)
        if m:
            pairs.append((name, int(m.group(1))))
    if not pairs:
        die('no chunk_NNNNNNNN.msg files in %s' % acqdir)

    for (n0, i0), (n1, i1) in zip(pairs[:-1], pairs[1:]):
        if i1 != i0 + 1:
            die('files are not consecutive: %s is followed by %s (%d chunks missing)' % (n0, n1, i1 - i0 - 1))

    return pairs


def trim_to_rfi_chunks(pairs, nfiles):
    """Drops the files at either end that do not belong to a complete 4096-sample RFI chunk.

    The L1 server aligned its 4096-sample RFI chunks to ichunk % 4 == 0, so the offline stream
    must start on such a file and end on one with ichunk % 4 == 3; otherwise the chain's
    4096-sample transforms would see different chunk boundaries than the real-time run did.
    """

    n = FILES_PER_RFI_CHUNK
    starts = [k for k, (_, i) in enumerate(pairs) if i % n == 0]
    ends = [k for k, (_, i) in enumerate(pairs) if i % n == n - 1]
    if not starts or not ends or ends[-1] < starts[0]:
        die('no complete rfi chunk: need %d consecutive files, the first with ichunk %% %d == 0' % (n, n))

    k0, k1 = starts[0], ends[-1] + 1
    for where, dropped in (('start', pairs[:k0]), ('end', pairs[k1:])):
        if dropped:
            print('Trimmed %d file(s) at the %s, to align with the 4096-sample rfi chunks: %s'
                  % (len(dropped), where, ' '.join(name for name, _ in dropped)))

    kept = pairs[k0:k1]
    return kept[:nfiles] if nfiles else kept


def read_saved_masks(acqdir, pairs, sub):
    """Reads and checks the header and saved RFI mask of every file.

    Returns (header, masks): the header fields shared by all files, and one (nrfifreq, NT/8)
    uint8 array per file.  'sub' is the wi_sub_pipeline json, used to check that the masks are
    at the resolution the chain's sub-pipeline runs at.
    """

    print('Reading the headers and saved masks of %d files ...' % len(pairs))
    t0 = time.time()
    header = None
    masks = []

    for name, ichunk in pairs:
        path = os.path.join(acqdir, name)
        with open(path, 'rb') as f:
            arr = next(msgpack.Unpacker(f))

        if len(arr) != MSG_NFIELDS or arr[MSG_VERSION] != 2:
            die('%s: not a version-2 assembled_chunk msgpack file' % path)

        h = {'beam_id': arr[MSG_BEAM_ID],
             'nupfreq': arr[MSG_NUPFREQ],
             'fpga_counts_per_sample': arr[MSG_FPGA_COUNTS_PER_SAMPLE],
             'nrfifreq': arr[MSG_NRFIFREQ]}

        nfreq = h['nupfreq'] * 1024
        nrfifreq_expected = sub['nfreq_out'] if sub['nfreq_out'] else nfreq // sub['Df']

        if arr[MSG_BINNING] != 1:
            die('%s: binning=%d.  This chunk was time-downsampled by the L1 ring buffer, so its mask\n'
                '       was combined from other chunks rather than computed by the RFI chain.' % (path, arr[MSG_BINNING]))
        if h['nrfifreq'] == 0 or not arr[MSG_HAS_RFI_MASK]:
            die('%s: no RFI mask saved (nrfifreq=%d, has_rfi_mask=%s).  The L1 server that wrote this\n'
                '       acquisition was not saving masks (nrfifreq: 0 in its config).' % (path, h['nrfifreq'], arr[MSG_HAS_RFI_MASK]))
        if h['nrfifreq'] != nrfifreq_expected:
            die("%s: the saved mask has %d channels, but the chain's sub-pipeline runs at %d channels"
                % (path, h['nrfifreq'], nrfifreq_expected))
        if arr[MSG_FPGA_BEGIN] != ichunk * NT * h['fpga_counts_per_sample']:
            die('%s: fpga_begin=%d does not match the ichunk in the filename (expected %d)'
                % (path, arr[MSG_FPGA_BEGIN], ichunk * NT * h['fpga_counts_per_sample']))
        if header is None:
            header = h
        elif h != header:
            die('%s: header %r differs from the first file %r' % (path, h, header))

        packed = np.frombuffer(arr[MSG_RFI_MASK], dtype=np.uint8)
        if packed.size != h['nrfifreq'] * NT // 8:
            die('%s: rfi_mask has %d bytes, expected %d' % (path, packed.size, h['nrfifreq'] * NT // 8))
        masks.append(packed.reshape(h['nrfifreq'], NT // 8).copy())

    print('    done in %.0f s: beam_id %d, %d channels, %d fpga counts per sample, masks at %d channels'
          % (time.time() - t0, header['beam_id'], nfreq, header['fpga_counts_per_sample'], header['nrfifreq']))
    return header, masks


def load_chain(path):
    """Splits the jsonized chain into the pieces the pipeline is built from.

    Returns (head, sub, inner, dropped): the outer elements before the wi_sub_pipeline, the
    wi_sub_pipeline's own json, its inner elements, and the class names of the outer elements
    after it, which are not run.  Dies unless the chain has the layout this script assumes:
    exactly one wi_sub_pipeline, at the native time resolution, whose last element is a
    mask_counter -- the transform whose input the L1 server saved as the mask.
    """

    try:
        with open(path) as f:
            j = json.load(f)
    except (IOError, ValueError) as e:
        die('%s: %s' % (path, e))

    if not isinstance(j, dict) or j.get('class_name') != 'pipeline' or not isinstance(j.get('elements'), list):
        die('%s: expected a jsonized rf_pipelines pipeline (class_name "pipeline" with an "elements" list)' % path)

    outer = j['elements']
    ks = [k for k, e in enumerate(outer) if e.get('class_name') == 'wi_sub_pipeline']
    if len(ks) != 1:
        die('%s: expected exactly one wi_sub_pipeline among the outer elements, found %d' % (path, len(ks)))

    k = ks[0]
    sub = outer[k]
    inner = sub.get('sub_pipeline', {}).get('elements')
    if not isinstance(inner, list) or not inner:
        die('%s: the wi_sub_pipeline has no sub_pipeline elements' % path)
    if sub.get('nds_out') != 1:
        die('%s: the wi_sub_pipeline has nds_out=%r; this script assumes the mask is at the native\n'
            '       time resolution (nds_out == 1)' % (path, sub.get('nds_out')))

    last = inner[-1]
    if last.get('class_name') != 'mask_counter':
        die("%s: the last element of the sub-pipeline is %r, not a mask_counter.  The L1 server saves\n"
            "       the mask at the chain's last mask_counter, and this script assumes it is there."
            % (path, last.get('class_name')))
    if last.get('nt_chunk') != NT:
        die('%s: the last mask_counter has nt_chunk=%r; the L1 server fills one %d-sample file per\n'
            '       mask_counter call, so it must be %d' % (path, last.get('nt_chunk'), NT, NT))

    dropped = [e.get('class_name') for e in outer[k+1:]]
    return outer[:k], sub, inner, dropped


# -------------------------------------------------------------------------------------------------


def build_pipeline(paths, head, sub, inner, prescale, comparator):
    """The chain from the json, element by element, with three changes.

    A prescale_transform after the stream (omitted when prescale is 1), the comparator after
    the sub-pipeline's last mask_counter, and nothing after the sub-pipeline.
    """

    from_json = rf_pipelines.pipeline_object.from_json

    try:
        stream = rf_pipelines.chime_frb_stream_from_filename_list(paths, nt_chunk=NT)
    except Exception as e:
        if 'ch_frb_io' in str(e):
            die('the old rf_pipelines was built without ch_frb_io (%s).  build_oldpipe.sh sets\n'
                '       HAVE_CH_FRB_IO=y, so rebuild.' % e)
        raise

    elements = [stream]
    if prescale != 1.0:
        elements.append(prescale_transform(prescale))
    elements += [from_json(e) for e in head]

    inner_pipeline = rf_pipelines.pipeline([from_json(e) for e in inner] + [comparator])
    elements.append(rf_pipelines.wi_sub_pipeline(inner_pipeline, w_cutoff=sub['w_cutoff'],
                                                 nt_chunk=sub.get('nt_chunk', 0), nfreq_out=sub['nfreq_out'],
                                                 nds_out=sub['nds_out'], Df=sub['Df'], Dt=sub['Dt']))
    return rf_pipelines.pipeline(elements)


def print_report(comparator, nfiles, prescale, run_time):
    c = comparator.counts
    total = float(c.sum())

    print()
    print('Compared %d files (%d rfi chunks), %d mask samples, chain run time %.0f s'
          % (nfiles, nfiles // FILES_PER_RFI_CHUNK, int(total), run_time))
    # The count is printed too: a few hundred differing samples out of 1e9 is 0.0000%.
    for label, n in (('Unmasked in both saved files and new run  ', c[1, 1]),
                     ('Masked in both saved files and new run    ', c[0, 0]),
                     ('Unmasked in saved files, masked in new run', c[1, 0]),
                     ('Masked in saved files, unmasked in new run', c[0, 1])):
        print('  %s = %11.6f%%  (%d samples)' % (label, 100.0 * n / total, n))

    d = comparator.disagreements
    if not d:
        print('  The masks are identical.')
    else:
        print('  The masks differ in %d of %d files.' % (len(d), nfiles))
        listed = d if len(d) <= 10 else sorted(d, key=lambda x: -x[1])[:10]
        for name, nsamples, nrows in listed:
            print('    %s: %d samples, of which %d whole 1024-sample rows' % (name, nsamples, nrows * NT))
        if len(d) > 10:
            print('    (the 10 worst; -v lists every file)')
        print('  (Whole rows point at std_dev_clipper decisions, scattered samples at intensity_clippers or detrenders.)')

    print()
    print('prescale used in this run: %g  (the real-time pipeline used intensity_prescale = %g)'
          % (prescale, REALTIME_PRESCALE))


def parse_args():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('acqdir', help='directory of chunk_NNNNNNNN.msg files')
    p.add_argument('rfi_chain_json', help='jsonized rf_pipelines RFI chain')
    p.add_argument('-p', '--prescale', type=float, default=1.0,
                   help='multiply the intensity by this before the chain (default 1; the real-time pipeline used %g)' % REALTIME_PRESCALE)
    p.add_argument('--nfiles', type=int, default=0, metavar='N',
                   help='after trimming, use only the first N files (a multiple of %d), for a quick run' % FILES_PER_RFI_CHUNK)
    p.add_argument('-v', '--verbose', action='store_true', help='one line per file, and chattier rf_pipelines')
    args = p.parse_args()
    if args.nfiles < 0 or args.nfiles % FILES_PER_RFI_CHUNK != 0:
        p.error('--nfiles must be a non-negative multiple of %d' % FILES_PER_RFI_CHUNK)
    return args


def main():
    args = parse_args()

    if sys.version_info[0] >= 3:
        if os.environ.get('REPRODUCE_RFIMASK_REEXEC'):
            die('re-executing under the old pipeline did not land in python 2; check %s' % os.path.join(OLDPIPE, 'env.sh'))
        reexec_under_old_pipeline()

    head, sub, inner, dropped = load_chain(args.rfi_chain_json)
    pairs = trim_to_rfi_chunks(list_files(args.acqdir), args.nfiles)
    names = [name for name, _ in pairs]
    paths = [os.path.join(args.acqdir, name) for name in names]
    print('Using %d files (%d rfi chunks): %s .. %s' % (len(names), len(names) // FILES_PER_RFI_CHUNK, names[0], names[-1]))

    header, saved_masks = read_saved_masks(args.acqdir, pairs, sub)

    if dropped:
        print('Not running the json elements after the wi_sub_pipeline, which cannot affect the mask: ' + ', '.join(dropped))
    comparator = mask_comparator(names, saved_masks, args.verbose)
    pipeline = build_pipeline(paths, head, sub, inner, args.prescale, comparator)

    print('Running the RFI chain%s ...' % ('' if args.prescale == 1.0 else ' with prescale %g' % args.prescale))
    sys.stdout.flush()
    t0 = time.time()
    pipeline.run(outdir=None, verbosity=(2 if args.verbose else 1))
    run_time = time.time() - t0

    if comparator.ncalls != len(names):
        die('the chain produced %d chunks for %d files' % (comparator.ncalls, len(names)))

    print_report(comparator, len(names), args.prescale, run_time)
    return 0 if not comparator.disagreements else 2


if __name__ == '__main__':
    sys.exit(main())
