#!/bin/bash
#
# Build the old CHIME FRB pipeline (the ~10 repos in ../extern) into a prefix that
# spot tests can call.  The build lands inside this directory, so it is per-worktree.
#
#   ./build_oldpipe.sh [repo ...]      # default: all repos, in dependency order
#
# Inputs:
#   ../extern/<repo>        pristine reference clones -- never modified
#   chimefrb/patches/*.patch  source fixes, applied to the working copy only
#   $CHIMEFRB_ENV           conda env supplying python2.7 + the old C/C++ libraries
#
# Outputs:
#   $OLDPIPE/src/<repo>     working copy (rsync of extern + patches); safe to delete
#   $OLDPIPE/prefix         bin/ lib/ include/ and the python2.7 site-packages
#   $OLDPIPE/env.sh         source this to use the result
#   $OLDPIPE/driver_flags.json  compiler flags, read by harness.py to build a driver
#   $OLDPIPE/BUILD_MANIFEST.txt
#
# The build is pinned to -march=haswell rather than -march=native: golden files
# produced here have to reproduce on a different machine.

set -e -o pipefail

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

CHIMEFRB_ENV=${CHIMEFRB_ENV:-/home/kmsmith/miniforge3/envs/chimefrb}
EXTERN=${EXTERN:-/home/kmsmith/ch/extern}
# Inside the worktree, so each worktree gets its own build and agents working in
# parallel cannot trip over each other.  Gitignored.
OLDPIPE=${OLDPIPE:-$HERE/oldpipe}
PATCHDIR=$HERE/patches

# Dependency order.  Do not reorder without checking the -l flags in each Makefile.
ALL_REPOS="simd_helpers sp_hdf5 rf_kernels simpulse spshuff pyclops bonsai ch_frb_io rf_pipelines ch_frb_rfi ch_frb_l1"
REPOS=${*:-$ALL_REPOS}

[ -d "$CHIMEFRB_ENV" ] || { echo "no conda env at $CHIMEFRB_ENV (see chimefrb/README.md)" >&2; exit 1; }

PREFIX=$OLDPIPE/prefix
PYDIR=$PREFIX/lib/python2.7/site-packages
PYTHON_INCDIR=$CHIMEFRB_ENV/include/python2.7
NUMPY_INCDIR=$CHIMEFRB_ENV/lib/python2.7/site-packages/numpy/core/include
mkdir -p "$PREFIX"/{bin,lib,include} "$PYDIR" "$OLDPIPE"/{src,log}

ARCH=-march=haswell
CPP="g++ -std=c++11 -pthread -Wall -fPIC -Wno-literal-suffix -O3 $ARCH -ffast-math -funroll-loops"

# HDF5 comes from the conda env, and the env's hdf5 must be 1.10 or newer:
# sp_hdf5-01-hdf5-110-api.patch ports sp_hdf5 to the 1.10+ C++ API, and the 1.8
# builds on conda-forge predate its move to the C++11 string ABI (they export
# std::basic_string where jsoncpp and yaml-cpp export std::__cxx11::basic_string,
# so no binary can link both).  Do NOT substitute the system hdf5: it is new-ABI,
# but it needs the system libcurl, which shares the env copy's libcurl.so.4 SONAME
# and carries a different symbol-version node, so the two collide.
HAVE_HDF5=${HAVE_HDF5:-y}

INC="-I. -I$PREFIX/include -I$CHIMEFRB_ENV/include -I$PYTHON_INCDIR -I$NUMPY_INCDIR"
# -rpath-link is not redundant with -rpath: several of these Makefiles link an
# executable with just -lbonsai (say) and rely on the linker following that
# library's own NEEDED entries.  Modern binutils will not use a library's RPATH
# for that search, so without -rpath-link the transitive deps come up undefined.
LIB="-L. -L$PREFIX/lib -L$CHIMEFRB_ENV/lib"
LIB="$LIB -Wl,-rpath,$PREFIX/lib -Wl,-rpath,$CHIMEFRB_ENV/lib"
LIB="$LIB -Wl,-rpath-link,$PREFIX/lib -Wl,-rpath-link,$CHIMEFRB_ENV/lib"

# The builds shell out to 'cython' and 'python', which must be the env's python2.7 --
# the env supplies no compiler, so g++/make/ld still come from the system.
#
# Deliberately NOT setting LD_LIBRARY_PATH here: it would apply to every tool the
# build runs (rsync, patch, make), and the env's libzstd/libcurl/... are old enough
# to break the system copies.  Everything we link gets -Wl,-rpath instead, so the
# built binaries find their libraries without it.
export PATH=$CHIMEFRB_ENV/bin:$PREFIX/bin:$PATH
export PYTHONPATH=$PYDIR

cat > "$OLDPIPE/env.sh" <<EOF
# Generated by build_oldpipe.sh -- source to use the old pipeline.
export CHIMEFRB_ENV=$CHIMEFRB_ENV
export OLDPIPE=$OLDPIPE
export PATH=$CHIMEFRB_ENV/bin:$PREFIX/bin:\$PATH
export LD_LIBRARY_PATH=$PREFIX/lib:$CHIMEFRB_ENV/lib
export PYTHONPATH=$PYDIR
# A function, not an alias: aliases are not expanded in non-interactive shells, so a
# script that sources this file could not call it.
oldpython() { "$CHIMEFRB_ENV/bin/python" "\$@"; }
EOF

# Everything harness.py needs to compile a spot-test driver against this build.
cat > "$OLDPIPE/driver_flags.json" <<EOF
{
  "cxx": "g++",
  "cxxflags": "-std=c++11 -pthread -Wall -fPIC -Wno-literal-suffix -O3 $ARCH -ffast-math -funroll-loops",
  "incflags": "$INC",
  "libflags": "$LIB",
  "python": "$CHIMEFRB_ENV/bin/python",
  "prefix": "$PREFIX",
  "have_hdf5": "$HAVE_HDF5"
}
EOF

sync_and_patch() {
    local r=$1
    rsync -a --delete --exclude='.git' "$EXTERN/$r/" "$OLDPIPE/src/$r/"
    for p in "$PATCHDIR/$r"-*.patch; do
        [ -e "$p" ] || continue
        patch -s -d "$OLDPIPE/src/$r" -p1 < "$p" || { echo "$r: patch $(basename "$p") failed" >&2; exit 1; }
        echo "    applied $(basename "$p")"
    done
}

# Each repo's Makefile.local, keyed by repo name.  These are the machine-dependent
# variables each Makefile requires; see the comment block at the top of each one.
write_makefile_local() {
    local r=$1 f=$OLDPIPE/src/$1/Makefile.local
    case $r in
      simd_helpers|sp_hdf5)
        printf 'INCDIR=%s\nLIBDIR=%s\nCPP=%s %s %s\n' "$PREFIX/include" "$PREFIX/lib" "$CPP" "$INC" "$LIB" > "$f" ;;
      rf_kernels)
        printf 'INCDIR=%s\nLIBDIR=%s\nCPP=%s %s %s\n' "$PREFIX/include" "$PREFIX/lib" "$CPP" "$INC" "$LIB" > "$f" ;;
      simpulse)
        printf 'INCDIR=%s\nLIBDIR=%s\nPYDIR=%s\nCPP=%s %s %s\n' \
            "$PREFIX/include" "$PREFIX/lib" "$PYDIR" "$CPP" "$INC" "$LIB" > "$f" ;;
      pyclops)
        printf 'INCDIR=%s\nLIBDIR=%s\nPYDIR=%s\nCPP=%s %s\nCPP_LFLAGS=%s\n' \
            "$PREFIX/include" "$PREFIX/lib" "$PYDIR" "$CPP" "$INC" "$LIB" > "$f" ;;
      bonsai)
        cat > "$f" <<EOF
HAVE_SIMPULSE=y
HAVE_PNG=y
HAVE_HDF5=$HAVE_HDF5
HAVE_JSONCPP=y
BINDIR=$PREFIX/bin
LIBDIR=$PREFIX/lib
INCDIR=$PREFIX/include
PYDIR=$PYDIR
CPP=$CPP --param inline-unit-growth=10000 $INC $LIB
EOF
        ;;
      ch_frb_io)
        printf 'INCDIR=%s\nLIBDIR=%s\nBINDIR=%s\nCPP=%s %s\nCPP_LFLAGS=%s\n' \
            "$PREFIX/include" "$PREFIX/lib" "$PREFIX/bin" "$CPP" "$INC" "$LIB" > "$f" ;;
      rf_pipelines)
        cat > "$f" <<EOF
HAVE_SPSHUFF=y
HAVE_PSRFITS=n
HAVE_CH_FRB_IO=y
HAVE_SIMPULSE=y
HAVE_BONSAI=y
HAVE_HDF5=$HAVE_HDF5
HAVE_PNG=y
LIBDIR=$PREFIX/lib
INCDIR=$PREFIX/include
BINDIR=$PREFIX/bin
PYDIR=$PYDIR
PYTHON_INCDIR=$PYTHON_INCDIR
NUMPY_INCDIR=$NUMPY_INCDIR
CPP=$CPP $INC $LIB
EOF
        ;;
      ch_frb_rfi)
        printf 'PYDIR=%s\n' "$PYDIR" > "$f" ;;
      ch_frb_l1)
        cat > "$f" <<EOF
LIBDIR=$PREFIX/lib
INCDIR=$PREFIX/include
BINDIR=$PREFIX/bin
PYDIR=$PYDIR
PYTHON_INCDIR=$PYTHON_INCDIR
NUMPY_INCDIR=$NUMPY_INCDIR
CPP=$CPP
CPP_CFLAGS := $INC
CPP_LFLAGS := $LIB
CC=gcc -pthread -fPIC -Wall -O3 $ARCH -ffast-math -funroll-loops
EOF
        ;;
      *) echo "no Makefile.local recipe for $r" >&2; exit 1 ;;
    esac
}

for r in $REPOS; do
    echo "==> $r"
    sync_and_patch "$r"

    # spshuff is the odd one out: a python package with no Makefile.  All we need from
    # it is one header -- rf_pipelines does #include <spshuff.hpp> and nothing links
    # -lspshuff -- so install that and move on.  Note it is NOT on spshuff's master
    # branch; see chimefrb/README.md for which branches carry it.
    if [ "$r" = spshuff ]; then
        h=$OLDPIPE/src/spshuff/src/spshuff.hpp
        [ -e "$h" ] || { echo "    no src/spshuff.hpp in $EXTERN/spshuff (wrong branch?)"; exit 1; }
        cp -f "$h" "$PREFIX/include/"
        echo "    ok (header only)"
        continue
    fi

    write_makefile_local "$r"
    log=$OLDPIPE/log/$r.log
    # ch_frb_rfi is python-only, so its 'make all' is a no-op.  sp_hdf5 is header-only
    # and its 'all' target builds examples that link -lhdf5_cpp, so it is install-only
    # whenever HAVE_HDF5=n.
    skip_all=n
    [ "$r" = ch_frb_rfi ] && skip_all=y
    [ "$r" = sp_hdf5 ] && [ "$HAVE_HDF5" = n ] && skip_all=y
    if [ "$skip_all" = n ]; then
        make -C "$OLDPIPE/src/$r" -j "$(nproc)" > "$log" 2>&1 \
            || { echo "    BUILD FAILED -- see $log"; grep -iE "error:" "$log" | head -10; exit 1; }
    fi
    make -C "$OLDPIPE/src/$r" install >> "$log" 2>&1 \
        || { echo "    INSTALL FAILED -- see $log"; tail -10 "$log"; exit 1; }
    echo "    ok"
done

{
    echo "old CHIME pipeline build"
    echo "date:     $(date -Is)"
    echo "host:     $(hostname)"
    echo "compiler: $(g++ --version | head -1)"
    echo "arch:     $ARCH"
    echo "env:      $CHIMEFRB_ENV (python $("$CHIMEFRB_ENV/bin/python" --version 2>&1 | awk '{print $2}'))"
    echo "HAVE_HDF5=$HAVE_HDF5"
    echo
    echo "extern repo revisions:"
    for r in $ALL_REPOS; do
        printf "  %-14s %s\n" "$r" "$(git -C "$EXTERN/$r" rev-parse --short HEAD 2>/dev/null || echo '?')"
    done
} > "$OLDPIPE/BUILD_MANIFEST.txt"

echo
echo "done -- source $OLDPIPE/env.sh to use it"
