import os
import re
import numpy as np

from . import utils

from .Dtype import Dtype
from .Kernel import Kernel
from .Ringbuf import Ringbuf
from .FrequencySubbands import FrequencySubbands
from .Dedisperser import Dedisperser, MultiDedisperser
from .PeakFinder import PeakFinder


####################################################################################################
#
# Validating cdd2 parameter "rows".
#
# makefile_helper.py chooses which cdd2 kernels to compile from lists of parameter tuples,
# and 'pirate_frb dev random_kernels --cdd2' generates fresh tuples to paste into them. A row
# has to satisfy several constraints that live in three different places -- the Dedisperser
# and PeakFinder constructors below, FrequencySubbands.restrict_subband_counts(), and the
# build-wide Dout invariant -- and a row violating any of them either fails at
# makefile-generation time with a bare AssertionError naming no kernel, or compiles a kernel
# no DedispersionConfig can ask for.
#
# So the constraints live HERE, once, and both the generator of rows and the consumer of rows
# call in. Do not re-derive any of them at a call site.


def cdd2_dout(dd_rank):
    """The build-wide Dout invariant: a cdd2 kernel's Dout is 2^dd_rank1, and nothing else.

    Dout = (nt_in / nt_out) is a cdd2 registry KEY field, and it is set by the producing
    tree's DedispersionTree::time_downsampling, which the tree constructor pins to
    pow2(dd_rank1). It is not a config field, so no DedispersionConfig can ask for any other
    value and a kernel compiled at one would be unreachable. See the long comment in
    makefile_helper.autogenerated_cdd2_kernels().
    """
    return 2 ** ((dd_rank + 1) // 2)


def cdd2_dcore(dd_rank):
    """The Dcore that goes with cdd2_dout(dd_rank).

    Dcore is a registry VALUE, not a key field -- a caller adopts whatever the compiled
    kernel has -- so unlike Dout this is a choice rather than a constraint. We make the same
    choice everywhere, which is what keeps Dcore a function of dd_rank.
    """
    return min(cdd2_dout(dd_rank), 8)


def max_cdd2_tinner(dtype, dd_rank):
    """Largest Tinner for which a cdd2 kernel at this dd_rank can be built.

    PeakFinder requires Dout*Tinner <= 32*SW, and cdd2_dout() pins Dout, so this is a bound
    on Tinner alone -- a tight one at large dd_rank (fp32 dd_rank 8 admits only Tinner <= 2).
    Returns 0 if no Tinner works, which cannot happen for dd_rank <= 8.

    Note DedispersionConfig::make_random() enforces the same bound, spelled
    'xdiv(1024, dtype.nbits) / Dout' -- 1024/nbits is identically 32*SW. It gets there from
    wt_time_downsampling rather than from the weight-reader's register layout; the two
    derivations coincide.
    """
    return (32 * Dtype(dtype).simd_width) // cdd2_dout(dd_rank)


def check_cdd2_params(dtype, dd_rank, subband_counts, Wmax, Tinner):
    """Returns None if a CoalescedDdKernel2 with these parameters can be BUILT and is
    REACHABLE from a DedispersionConfig; otherwise a one-line string saying why not.

    'subband_counts' is the kernel's own vector, i.e. already restricted by any early-trigger
    level (use check_cdd2_row() to check a whole makefile_helper row instead). Dout and Dcore
    are not arguments: they follow dd_rank, see cdd2_dout().
    """

    dtype = Dtype(dtype)
    sc = tuple(subband_counts)
    ctx = (f'(dtype={dtype.fname}, dd_rank={dd_rank}, subband_counts={sc},'
           f' Wmax={Wmax}, Tinner={Tinner})')

    if not (1 <= dd_rank <= 8):
        return f'dd_rank={dd_rank} is outside the supported range 1..8 {ctx}'

    # Dedisperser.two_stage; cdd2 has no single-stage form.
    if dd_rank < 3:
        return f'dd_rank={dd_rank} < 3, so the dedisperser is not two-stage {ctx}'

    try:
        fs = FrequencySubbands(subband_counts = list(sc))
    except Exception as e:
        return f'subband_counts={sc} is not a valid FrequencySubbands ({e}) {ctx}'

    # CoalescedDdKernel2 asserts this, and it is also what makes the kernel reachable: a
    # config's frequency_subband_counts become the et_level=0 tree's verbatim.
    dd_rank1 = (dd_rank + 1) // 2
    if fs.pf_rank > dd_rank1:
        return (f'pf_rank={fs.pf_rank} exceeds dd_rank1={dd_rank1}, so no DedispersionConfig'
                f' can ask for this kernel {ctx}')

    if not utils.is_power_of_two(Wmax):
        return f'Wmax={Wmax} is not a power of two {ctx}'
    if Wmax > 32:
        return f'Wmax={Wmax} exceeds the peak-finder maximum of 32 {ctx}'
    if not utils.is_power_of_two(Tinner):
        return f'Tinner={Tinner} is not a power of two {ctx}'

    tmax = max_cdd2_tinner(dtype, dd_rank)
    if Tinner > tmax:
        return (f'Tinner={Tinner} exceeds {tmax}: PeakFinder requires Dout*Tinner <= 32*SW,'
                f' and Dout={cdd2_dout(dd_rank)} is pinned by dd_rank {ctx}')

    return None


def check_cdd2_row(dtype, dd_rank, Wmax, Tinner, subband_counts, et_levels):
    """As check_cdd2_params(), for a whole makefile_helper.py row.

    Checks every early-trigger level: 'subband_counts' here is a CONFIG's
    frequency_subband_counts, and et_level e yields a kernel at dd_rank - e whose vector is
    restrict_subband_counts(subband_counts, e). Both the restriction and the resulting
    pf_rank can fail.
    """

    sc = tuple(subband_counts)

    for et_level in et_levels:
        try:
            rsc = FrequencySubbands.restrict_subband_counts(list(sc), et_level)
        except Exception as e:
            return (f'et_level={et_level} is not usable with subband_counts={sc} ({e})')

        err = check_cdd2_params(dtype, dd_rank - et_level, rsc, Wmax, Tinner)
        if err is not None:
            return f'at et_level={et_level} (subband_counts={sc} restricts to {tuple(rsc)}): {err}'

    return None


####################################################################################################


class CoalescedDdKernel2:
    def __init__(self, dtype, dd_rank, frequency_subbands, Wmax, Tinner):
        """Coalesced Dedisperser + PeakFinder.

        We currently assume apply_input_residual_lags == input_is_ringbuf == True.

        NOTE Dout and Dcore are NOT arguments: they are derived from dd_rank, and this is
        their one definition anywhere. See cdd2_dout(). (The PeakFinder built below still
        takes both as free parameters -- the constraint is on the cdd2 combination, not on
        the peak-finder.)
        """

        self.dtype = dtype = Dtype(dtype)
        self.frequency_subbands = frequency_subbands                                            
        self.dd_rank = dd_rank
        self.Tinner = Tinner
        self.Dcore = cdd2_dcore(dd_rank)
        self.Dout = cdd2_dout(dd_rank)
        self.Wmax = Wmax

        self.dt32 = dtype.simd32
        self.SW = dtype.simd_width
        self.rb = Ringbuf(self.dt32)  # simd dtype, not scalar dtype

        self.dd = Dedisperser(
            dtype = dtype,
            rank = dd_rank,
            apply_input_residual_lags = True,
            input_is_ringbuf = True,
            output_is_ringbuf = False,
            nspec = 1,
            ringbuf = self.rb   # note that ringbuf is shared between Dedisperser and PeakFinder
        )

        self.xdm_rank = K = self.dd.xdm_rank(frequency_subbands)   # (dd.rank1 - fs.pf_rank)

        # The peak-finder sees one input per (multiplet, "extra DM") pair, indexed by
        # m_ext = (m << xdm_rank) | mu -- see Dedisperser.emit_subband_extraction(). Prepending
        # 'xdm_rank' zeros to the subband counts gives a FrequencySubbands whose multiplet index
        # IS m_ext: same N, same band ordering, and each band owns a run of 2^xdm_rank times as
        # many consecutive multiplets. That is all the peak-finder layer uses, so it needs no
        # notion of 'mu' at all.
        #
        # WARNING: the two FrequencySubbands objects describe different band sets. Only the
        # compact one is geometrically meaningful (prepending zeros turns the "unstaggered"
        # level-0 bands into half-overlapping level-K bands, so n_to_flo/n_to_fhi and m_to_d
        # both change). The dedisperser, the registry key and the C++ side all use the compact
        # one; only 'self.pf' uses the extended one.
        #
        # Note this is purely a codegen technique, invisible in any C++ interface: the C++
        # peak-finding kernels take K as PeakFindingKernelParams::xdm_rank instead (they read
        # a (ndm_out << K, M) input array and fold 'mu' in as they go), and the generated
        # kernel is keyed on the compact counts either way.
        self.pf_frequency_subbands = FrequencySubbands([0]*K + list(frequency_subbands.subband_counts))

        self.pf = PeakFinder(
            dtype = dtype,
            frequency_subbands = self.pf_frequency_subbands,
            Wmax = Wmax,
            Dcore = self.Dcore,
            Dout = self.Dout,
            Tinner = Tinner,
            ringbuf = self.rb   # note that ringbuf is shared between Dedisperser and PeakFinder
        )

        # These restrictions may be relaxed in the future.
        assert self.dd.two_stage
        assert self.frequency_subbands.pf_rank <= self.dd.rank1
        assert self.pf_frequency_subbands.pf_rank == self.dd.rank1

        # From Dedisperser
        self.warps_per_threadblock = self.dd.warps_per_threadblock
        self.shmem_nbytes = self.dd.shmem_nbytes
        self.nt_per_segment = self.dd.nt_per_segment

        # From PeakFinder
        self.P = self.pf.P
        self.M_ext = self.pf.M   # = 2^xdm_rank * fs.M (emitted as 'constexpr int M', see emit_kernel)
        self.Minner = self.pf.Minner
        self.weight_layout = self.pf.weight_layout

        # Typical kernel name: cdd2_fp32_r7_n11_n6_n3_n1_W16_Tinner1
        # No Dcore/Dout in the name: both are functions of dd_rank, which is already here.
        self.kernel_name = f'cdd2_{dtype.fname}_r{dd_rank}_{frequency_subbands.fstr}_W{Wmax}_Tinner{Tinner}'
        self.kernel_basename = self.kernel_name + '.cu'

        # For testing: if a peak-finding kernel is precompiled, we also precompile unit tests
        # for the associated sub-kernels. (In the case of the dedispersion sub-kernel, we precompile
        # the MultiDedisperser that contains the sub-kernel.)

        mdd = MultiDedisperser(
            dtype = self.dd.dtype,
            apply_input_residual_lags = self.dd.apply_input_residual_lags, 
            input_is_ringbuf = self.dd.input_is_ringbuf, 
            output_is_ringbuf = self.dd.output_is_ringbuf, 
            nspec = self.dd.nspec
        )

        self.all_kernel_basenames = [ self.kernel_basename, mdd.kernel_basename ] + self.pf.all_kernel_basenames


    def emit_kernel(self, k):
        """Emits the complete kernel, including prologue, body, and registry registration."""
        
        assert isinstance(k, Kernel)

        # ---------------  Prologue  ---------------
        
        k.emit('#include "../../include/pirate/CoalescedDdKernel2.hpp"')
        k.emit('#include "../../include/pirate/FrequencySubbands.hpp"')
        k.emit('#include "../../include/pirate/inlines.hpp"')
        k.emit('#include <ksgpu/device_fp16.hpp>   // f16_perm(), f16_align()')
        k.emit()
        k.emit('using namespace std;')
        k.emit('using namespace ksgpu;')
        k.emit()
        k.emit('namespace pirate {')
        k.emit('#if 0')
        k.emit('}  // editor auto-indent')
        k.emit('#endif')
        k.emit()

        # ---------------  CUDA kernel  ---------------
        
        # launch_bounds
        lb_warps = self.warps_per_threadblock
        lb_blocks = utils.xdiv(16, lb_warps)

        k.emit(f'// Autogenerated by pirate_frb.cuda_generator')
        k.emit()
        k.emit(f'// Launch with {{ 32, {self.warps_per_threadblock} }} threads/warp')
        k.emit(f'// Launch with {{ Namb, Nbeams }} threadblocks')
        k.emit()

        k.emit(f'__global__ void __launch_bounds__({32 * lb_warps}, {lb_blocks})')
        k.emit(f'{self.kernel_name}(')
        k.emit(f'    void *grb_base_, uint *grb_quads_, long grb_frame0,    // dedisperser input (ring buffer)')
        k.emit(f'    void *out_max_, uint *out_argmax, const void *wt_,     // peak-finder output')
        k.emit(f'    uint out_max_bstride32, uint out_argmax_bstride32,     // output beam-strides (multiples of 32 bits)')
        k.emit(f'    void *pstate_, int ntime,                              // shared between dedisperser and peak-finder')
        k.emit(f'    ulong nt_cumul, bool is_downsampled_tree,              // dedisperser')
        k.emit(f'    uint ndm_out_per_wt, uint nt_in_per_wt)                // peak-finder')
        k.emit('{')
        k.emit(f'constexpr int M = {self.M_ext};')
        k.emit(f'constexpr int Dout = {self.Dout};')
        k.emit(f'constexpr int Dcore = {self.Dcore};')
        k.emit(f'constexpr int Minner = {self.Minner};')
        k.emit(f'constexpr int Tinner = {self.Tinner};')
        k.emit(f'constexpr int wt_touter_stride32 = {utils.xdiv(self.pf.wt_touter_byte_stride,4)};')
        k.emit()

        self.dd._emit_rsqrt2(k)

        if self.Wmax > 1:
            k.emit(f'const {self.dt32} pf_a = {self.dtype.from_float("0.5f")};')
            k.emit()

        self.dd._apply_inbuf_offsets(k)    # operates on grb* pointers, since self.dd.input_is_ringbuf == True

        # No call to self.dd._apply_outbuf_offsets() in coalesced kernel,
        # Instead, call self._apply_pfout_offsets(), which operates on out_max, out_argmax, wt pointers.
        self._apply_pfout_offsets(k)

        # No-ops if self.two_stage == False.
        self.dd._init_srb(k)

        # PfWeightReader.top() is currently a placeholder that does not emit any code.
        self.pf.pf_weight_reader.top(k, 'wt')

        # Save splice, for code to load pstate.
        # This code must be emitted near the end, after the ring buffer layout is finalized.
        # Note that pstate is managed by the dedispersion kernel.
        k_pstate = k.splice()

        k.emit(f'for (int itime = 0; itime < ntime; itime += {self.nt_per_segment}) {{')

        self.dd._load_input_data(k)              # behaves differently, depending on self.input_is_ringbuf
        self.dd._apply_input_residual_lags(k)    # no-ops if (self.apply_input_residual_lags) is False

        k.emit()
        k.emit("// The rest of this loop body is the second half of the dedispersion transform,")
        k.emit("// with the peak-finding logic interleaved into it.")
        k.emit("// FIXME I'm a bit worried that this way of doing it will lead to register pressure")
        k.emit("// I made a note to revisit this later.")
        k.emit()

        # Dedisperser.emit_subband_extraction() emits the entire second stage, and yields one
        # (register name, multiplet index, "extra DM" index) triple per peak-finder input.
        # Note that it must be fully consumed -- see its docstring, and the 'sbx_complete'
        # assert below.

        for rname, m, mu in self.dd.emit_subband_extraction(k, self.frequency_subbands):
            self.pf.process_pf_input(k, rname, (m << self.xdm_rank) | mu)

        assert self.dd.sbx_complete

        # No call to self.dd._save_output_data() in coalesced kernel.
        # Instead, call self.pf.process_pf_outputs()
        self.pf.pf_output.apply_outer(k, 'out_max', 'out_argmax', 'itime', 'ntime')
        self.pf.pf_weight_reader.bottom(k, 'itime', 'nt_in_per_wt')

        self.dd._advance_rrb(k)
        self.dd._advance_srb(k)      # no-ops if (self.two_stage) is False
        self.dd._advance_inbuf(k)    # behaves differently, depending on self.input_is_ringbuf
        # No call to self.dd._advance_outbuf() in coalesced kernel.
        
        k.emit('}   // outer time loop')

        # Now that 'self.rrb' has been finalized, we can sort out the pstate.
        self.dd._lay_out_pstate(k_pstate)    # initializes some members, including self.dd.pstate32_per_small_tree
        self.dd._load_pstate(k_pstate)
        self.dd._save_pstate(k)

        k.emit('    // placeholder')
        k.emit('}  // end of cuda kernel')
        

    def emit_registration(self, k):
        fs = self.frequency_subbands
        wl = self.weight_layout
        sb_counts = ', '.join(str(int(x)) for x in fs.subband_counts)
        m_to_n = ', '.join(str(int(n)) for n,d in fs.m_to_nd)
        m_to_d = ', '.join(str(int(d)) for n,d in fs.m_to_nd)
        n_to_flo = ', '.join(str(int(flo)) for flo,fhi in fs.n_to_frange)
        n_to_fhi = ', '.join(str(int(fhi)) for flo,fhi in fs.n_to_frange)

        k.emit('\n// Boilerplate to register the kernel when the library is loaded.')
        k.emit('namespace {')
        k.emit('struct register_hack {')
        k.emit('register_hack() {')
        k.emit('CoalescedDdKernel2::RegistryKey k;')
        k.emit(f'k.dtype = ksgpu::Dtype::native<{self.dtype.scalar}>();')
        k.emit(f'k.dd_rank = {self.dd_rank};')
        k.emit(f'k.subband_counts = {{ {sb_counts} }};')
        k.emit(f'k.Tinner = {self.Tinner};')
        k.emit(f'k.Wmax = {self.Wmax};')
        k.emit()
        k.emit('CoalescedDdKernel2::RegistryValue v;')
        k.emit(f'v.cuda_kernel = {self.kernel_name};')
        k.emit(f'v.Dcore = {self.Dcore};')
        k.emit()
        # The two compile-time coarse-graining factors this kernel was built with, reported
        # so the pipeline can cross-check them against DedispersionTree::{dm,time}_downsampling.
        # DELIBERATELY FROM TWO DIFFERENT SOURCES: the DM factor is the Dedisperser's
        # second-stage register geometry, the time factor is the PeakFinder's output cadence.
        # They are equal today, and nothing asserts that they are -- see the plan.
        k.emit(f'v.dm_downsampling = {2**self.dd.rank1};')
        k.emit(f'v.time_downsampling = {self.Dout};')
        k.emit(f'v.shmem_nbytes = {self.shmem_nbytes};')
        k.emit(f'v.warps_per_threadblock = {self.warps_per_threadblock};')
        k.emit(f'v.pstate32_per_small_tree = {self.dd.pstate32_per_small_tree};')
        k.emit(f'v.nt_per_segment = {self.nt_per_segment};')
        k.emit()
        k.emit(f'v.pf_weight_layout.dtype = ksgpu::Dtype::native<{self.dtype.scalar}>();')
        k.emit(f'v.pf_weight_layout.N = {fs.N};')
        k.emit(f'v.pf_weight_layout.P = {self.P};')
        k.emit(f'v.pf_weight_layout.Pouter = {wl.Pouter};')
        k.emit(f'v.pf_weight_layout.Pinner = {wl.Pinner};')
        k.emit(f'v.pf_weight_layout.Tinner = {self.Tinner};')
        k.emit(f'v.pf_weight_layout.touter_byte_stride = {wl.touter_byte_stride};')
        k.emit(f'v.pf_weight_layout.validate();  // throws an exception if anything is wrong')
        k.emit()
        k.emit('// Checks consistency of python/C++ FrequencySubbands')
        k.emit(f'FrequencySubbands fs({{ {sb_counts} }});')
        k.emit(f'xassert_eq(fs.N, {fs.N});')
        k.emit(f'xassert_eq(fs.M, {fs.M});')
        k.emit(f'xassert(vec_equal(fs.m_to_n, {{ {m_to_n} }}));')
        k.emit(f'xassert(vec_equal(fs.m_to_d, {{ {m_to_d} }}));')
        k.emit(f'xassert(vec_equal(fs.n_to_flo, {{ {n_to_flo} }}));')
        k.emit(f'xassert(vec_equal(fs.n_to_fhi, {{ {n_to_fhi} }}));')
        k.emit()
        k.emit('bool debug = false;')
        k.emit('CoalescedDdKernel2::registry().add(k, v, debug);')
        k.emit('} // register_hack constructor')
        k.emit('}; // struct register_hack')
        k.emit('register_hack hack;')
        k.emit('} // anonymous namespace')
        k.emit()
        k.emit('}   // namespace pirate')


    @classmethod
    def _idiv(cls, var, n):
        """Helper for _apply_pfout_offsets()."""
        return f'({var} >> {utils.integer_log2(n)})' if (n != 1) else var


    def _apply_pfout_offsets(self, k):
        dt32, SW, Dout = self.dt32, self.dtype.simd_width, self.Dout

        k.emit(f'// CoalescedDdKernel2._apply_outbuf_offsets() starts here.')
        k.emit(f"// Add per-warp pointer offsets (but not per-lane offsets) to 'out_max, 'out_argmax', and 'wt'.")
        k.emit(f'// This is tricky because the block/warp indices correspond to bit-reversed DMs, but the output')
        k.emit(f'// arrays are not bit-reversed.')
        k.emit()

        k.emit(f'const {dt32} *wt = (const {dt32} *) wt_;')
        k.emit(f'{dt32} *out_max = ({dt32} *) out_max_;')

        nt_out = self._idiv('ntime', Dout)
        nt_out32 = self._idiv('ntime', Dout*SW)

        k.emit(f'// FIXME could optimize out integer divisions')
        k.emit(f'uint ndm_out = blockDim.y * gridDim.x;')
        k.emit(f'uint lg2_ndm_out = __ffs(ndm_out) - 1;')
        k.emit(f'uint pf_beam = blockIdx.y;  // beam index is not bit-reversed')
        k.emit(f'uint dm_out_brev = threadIdx.y * gridDim.x + blockIdx.x;  // dm is bit-reversed')
        k.emit(f'uint dm_out = __brev(dm_out_brev) >> (32 - lg2_ndm_out);')
        k.emit(f'uint bd_out = pf_beam * ndm_out + dm_out;       // combined (beam,dm) index in out_max + out_argmax arrays')
        k.emit(f'uint bd_wt = bd_out / ndm_out_per_wt;           // combined (beam,dm) index in weight array')
        k.emit(f'uint Touter = ntime / (Tinner * nt_in_per_wt);  // see PfWeightLayout')
        k.emit()
        
        k.emit(f"// Add per-warp pointer offsets (but not per-lane offsets) to 'out_max, 'out_argmax', and 'wt'.")
        k.emit(f'out_max += bd_out * {nt_out32};                  // shape (beams, dm_out, ntime/Dout)')
        k.emit(f'out_argmax += bd_out * {nt_out};                 // shape (beams, dm_out, ntime/Dout)')
        k.emit(f'wt += bd_wt * Touter * wt_touter_stride32;     // shape (beams, ndm_wt, Touter,...)') 
        k.emit(f'// CoalescedDdKernel2._apply_outbuf_offsets() ends here.')
        k.emit()


    @classmethod
    def write_kernel(cls, filename):
        """Called from 'autogenerate_kernel.py' in the toplevel pirate directory."""
        
        basename = os.path.basename(filename)

        # Typical basename: cdd2_fp32_r7_n11_n6_n3_n1_W16_Tinner1
        m = re.fullmatch(r'cdd2_(fp\d+)_r(\d+)_((?:n\d+_)*n\d+)_W(\d+)_Tinner(\d+)\.cu', basename)
        if not m:
            raise RuntimeError(f"Couldn't match filename '{filename}'")
        
        dtype = Dtype(m.group(1))
        dd_rank = int(m.group(2))
        frequency_subbands = FrequencySubbands.from_fstr(m.group(3))
        Wmax, Tinner = int(m.group(4)), int(m.group(5))

        cdd2_kernel = cls(dtype, dd_rank, frequency_subbands, Wmax, Tinner)

        if cdd2_kernel.kernel_basename != basename:
            raise RuntimeError("CoalescedDdKernel2.write_kernel(): internal error: expected "
                               + f" {cdd2_kernel.kernel_basename=} and {basename=} to be equal")
                
        k = Kernel()
        cdd2_kernel.emit_kernel(k)
        cdd2_kernel.emit_registration(k)

        k.write_file(filename)
        
