import re
import os

from . import utils

from .Dtype import Dtype
from .Kernel import Kernel
from .Ringbuf import Ringbuf



####################################################################################################


class Dedisperser:
    def __init__(self, dtype, rank, apply_input_residual_lags, input_is_ringbuf, output_is_ringbuf, nspec, ringbuf = None):
        """Generator for the tree-dedispersion cuda kernel.

        We distinguish notationally between three ring buffers:
           - grb: global ring buffer, used if {input,output}_is_ringbuf == True
           - srb: shared memory ring buffer, used if self.two_stage == True
           - rrb: per-warp register ring buffer (always used).
        """
        
        dtype = Dtype(dtype)
        assert isinstance(rank, int)

        # Same bound as DedispersionKernelParams::validate(), and the cap on max_rank in
        # MultiDedisperser.emit_kernel(). It lives here so that the subbanded generators
        # (SbDedisperser, CoalescedDdKernel2) inherit it, and so that an out-of-range rank is
        # reported as one. Without it, rank 9 fails either in static_asserts() below (float32,
        # on the shared memory control word) or much further downstream in the caller
        # (float16, where the Dedisperser itself is legal but no kernel is emitted for it).
        assert 1 <= rank <= 8

        self.dtype = dtype
        self.dt32 = dtype.simd32
        self.nbits = dtype.nbits
        self.rank = rank
        self.apply_input_residual_lags = apply_input_residual_lags
        self.input_is_ringbuf = input_is_ringbuf
        self.output_is_ringbuf = output_is_ringbuf
        self.nt_per_segment = utils.xdiv(1024, self.nbits * nspec)
        self.nspec = nspec
        
        self.kernel_name = f'dd_fp{self.nbits}'
        self.kernel_name += f'_r{rank}'
        self.kernel_name += f'_ilag{int(apply_input_residual_lags)}'
        self.kernel_name += f'_irb{int(input_is_ringbuf)}'
        self.kernel_name += f'_orb{int(output_is_ringbuf)}'
        self.kernel_name += f'_s{nspec}'
        
        self.rrb = ringbuf if (ringbuf is not None) else Ringbuf(self.dt32)   # simd dtype, not scalar dtype

        # Set by emit_subband_extraction() when it runs to completion. See its docstring.
        self.sbx_complete = False

        # This simple rule works and gives good performance, for a reasonable
        # range of 'nspec' values.
        self.two_stage = (rank >= 3)

        if self.two_stage:
            self.rank0 = (rank // 2)
            self.rank1 = rank - self.rank0
            self.warps_per_threadblock = 2**self.rank0
            self.shmem_nbytes = 4 * self.srb_base(2**self.rank0, 0)
            self.ndd = 2**(self.rank1)   # dedispersion "data" registers per thread
            self.static_asserts()
        else:
            # FIXME single-stage kernel should use 4 warps/threadblock
            self.warps_per_threadblock = 1
            self.shmem_nbytes = 0
            self.ndd = 2**(self.rank)    # dedispersion "data" registers per thread

    
    def emit_global(self, k):
        assert isinstance(k, Kernel)
        
        W = self.warps_per_threadblock
        B = utils.xdiv(16, W)   # threadblocks per SM (FIXME rethink?)

        k.emit(f'// Autogenerated by pirate_frb.cuda_generator')
        k.emit()
        k.emit(f'// Launch with {{ 32, {W} }} threads/warp')
        k.emit(f'// Launch with {{ Namb, Nbeams }} threadblocks')
        k.emit()

        if False:   # debug
            self._show_shmem_layout_in_comment(k)

        # Kernel args depend on whether input/output is a ring buffer.
        rb_args = 'void *grb_base_, uint *grb_quads_, long grb_frame0'
        in_args = rb_args if self.input_is_ringbuf else 'void *inbuf_, long beam_istride32, int amb_istride32, int act_istride32'
        out_args = rb_args if self.output_is_ringbuf else 'void *outbuf_, long beam_ostride32, int amb_ostride32, int act_ostride32'
        
        k.emit(f'__global__ void __launch_bounds__({32*W},{B})')
        k.emit(f'{self.kernel_name}({in_args},')
        k.emit(f'       {out_args},')
        k.emit(f'       void *pstate_, int ntime, ulong nt_cumul, bool is_downsampled_tree)')
        k.emit('{')

        self._emit_rsqrt2(k)
        self._apply_inbuf_offsets(k)    # behaves differently, depending on self.input_is_ringbuf
        self._apply_outbuf_offsets(k)   # behaves differently, depending on self.output_is_ringbuf
        self._init_srb(k)               # no-ops if (self.two_stage) is False

        # Save splice, for code to load pstate.
        # This code must be emitted near the end, after the ring buffer layout is finalized.
        k_pstate = k.splice()
        
        k.emit(f'for (int itime = 0; itime < ntime; itime += {self.nt_per_segment}) {{')

        self._load_input_data(k)              # behaves differently, depending on self.input_is_ringbuf
        self._apply_input_residual_lags(k)    # no-ops if (self.apply_input_residual_lags) is False
        self._dedispersion_core(k)            # behaves differently, depending on self.two_stage
        self._save_output_data(k)             # behaves differently, depending on self.output_is_ringbuf

        self._advance_rrb(k)
        self._advance_srb(k)      # no-ops if (self.two_stage) is False
        self._advance_inbuf(k)    # behaves differently, depending on self.input_is_ringbuf
        self._advance_outbuf(k)   # behaves differently, depending on self.output_is_ringbuf
        
        k.emit('}   // outer time loop')

        # Now that 'self.rrb' has been finalized, we can sort out the pstate.
        self._lay_out_pstate(k_pstate)    # initializes some members, including self.pstate32_per_small_tree
        self._load_pstate(k_pstate)
        self._save_pstate(k)
        
        k.emit('}   // kernel')

        
    def _emit_rsqrt2(self, k):
        rhs = self.dtype.from_float("0.7071067811865476f")
        k.emit(f'const {self.dt32} rsqrt2 = {rhs};')


    def _load_input_data(self, k):
        if self.input_is_ringbuf:
            k.emit('// Load data from input ringbuf into registers.')
            k.emit('// Reminder: grb_quads is indexed by (tseg, dm_amb, f)')

            gso = self._emit_grb_quads(k, 0)

            for i in range(self.ndd):
                ix = self._grb_ix(k, gso, i)
                k.emit(f'{self.dt32} dd{i} = grb_base[{ix}];')

        else:
            k.emit('// Load data from global memory into registers')
            for i in range(self.ndd):
                s = f'{i} * act_istride32' if (i > 0) else '0'
                k.emit(f'{self.dt32} dd{i} = inbuf[{s}];')
        
        k.emit()
        

    def _save_output_data(self, k):
        # To convert a register index to a dmbr index, apply this shift.
        dshift = self.rank0 if self.two_stage else 0

        if self.output_is_ringbuf:
            k.emit('\n//Store data from registers to output ringbuf')
            k.emit('// Reminder: grb_quads is indexed by (tseg, f, dmbr)')

            gso = self._emit_grb_quads(k, dshift)

            for i in range(self.ndd):
                ix = self._grb_ix(k, gso, i)
                k.emit(f'grb_base[{ix}] = dd{i};')

        else:
            k.emit('\n//Store data from registers to global memory')
            for i in range(self.ndd):
                k.emit(f'outbuf[({i} * act_ostride32) << {dshift}] = dd{i};')
        
        k.emit()


    def _emit_grb_quads(self, k, dshift):
        """Emit the per-register-index part of the ring buffer address computation.

        Called once per time segment by _load_input_data() / _save_output_data(), before their
        loop over the register index 0 <= i < ndd.

        The work is distributed across the warp: lane 'i' processes the quadruple for register
        index i, so the whole computation -- including the modulo, which is expensive -- is
        done once per warp rather than once per register. (Previously every lane looped over i
        and redundantly repeated the identical computation ndd times.) Lanes i >= ndd repeat
        some other lane's work harmlessly; masking the index with (ndd-1) keeps their loads
        in-bounds, which matters at the end of the quadruples array.

        Returns the name of a register holding 'global_segment_offset' for register index
        (laneId % ndd). The per-i values are broadcast back to the warp by _grb_ix() below.
        """

        # Assumed below: one lane per register index. (ndd = 2^rank1 <= 16 in the two-stage
        # case, and 2^rank <= 4 in the single-stage case, so this is not a real constraint.)
        assert self.ndd <= 32

        q, gso, frame_offset_within_zone, frames_in_zone, segments_per_frame = k.get_tmp_rname(5)

        lane = f'(threadIdx.x & {self.ndd-1})' if (self.ndd < 32) else 'threadIdx.x'
        qix = f'{lane} << {dshift}' if (dshift > 0) else lane

        k.emit(f'// Ring buffer address computation, one register index per lane (see Dedisperser._emit_grb_quads)')
        k.emit(f'uint4 {q} = grb_quads[{qix}];   // lane i reads the quadruple for register index i')
        k.emit(f'uint {gso} = {q}.x;  // global_segment_offset, in segments not bytes')
        k.emit(f'uint {frame_offset_within_zone} = {q}.y;   // frame_offset_within_zone: index of (time chunk, beam) pair, relative to current pair')
        k.emit(f'uint {frames_in_zone} = {q}.z;     // frames_in_zone: number of (time chunk, beam) pairs in ringbuf (same as Ringbuf::frames_in_zone)')
        k.emit(f'uint {segments_per_frame} = {q}.w;    // segments_per_frame: number of segments per (time chunk, beam)')
        k.emit(f'{frame_offset_within_zone} = (grb_frame0 + {frame_offset_within_zone}) % {frames_in_zone};   // updated frame_offset_within_zone')
        k.emit(f'{gso} += ({frame_offset_within_zone} * {segments_per_frame});      // updated global_segment_offset')

        return gso


    def _grb_ix(self, k, gso, i):
        """Helper, called by _load_input_data() and _save_output_data().

        Broadcasts lane i's 'global_segment_offset' (computed by _emit_grb_quads() above) to
        the whole warp, and forms the per-lane address. Note that the shuffle's source lane is
        a compile-time constant.
        """

        g, ix = k.get_tmp_rname(2)

        k.emit(f'uint {g} = __shfl_sync(0xffffffff, {gso}, {i});   // global_segment_offset for register index {i}')
        k.emit(f'long {ix} = (long({g}) << 5) + threadIdx.x;  // index relative to rb_base')
        return ix


    
    def _dedispersion_core(self, k):
        if self.two_stage:
            self._two_stage_dedispersion_core(k)
        else:
            self._single_stage_dedispersion_core(k)

    
    def _single_stage_dedispersion_core(self, k):
        assert not self.two_stage

        for i in range(self.rank):
            self._dedispersion_pass(k, i)

        
    def _two_stage_dedispersion_core(self, k, *, return_early=False):
        """If 'return_early' is True, we stop after the shared memory read, i.e. we emit the
        first (rank0) dedispersion passes and the shmem transpose, but not the remaining
        (rank1) passes. Only used by emit_subband_extraction(), which emits those remaining
        passes itself, interleaved with the subband outputs."""

        assert self.two_stage

        for i in range(self.rank0):
            self._dedispersion_pass(k, i)

        k.emit()
        k.emit('__syncthreads();')
        k.emit()
        k.emit('// Write dd registers to shared memory')

        for i in range(self.ndd):
            s = self._srb_loc(k, i)
            k.emit(f'shmem[{s}] = dd{i};')

        k.emit()
        k.emit('__syncthreads();')
        k.emit()
            
        k.emit('// Read dd registers from shared memory')

        for i in range(self.ndd):
            s = self._srb_loc(k, 16+i)
            k.emit(f'dd{i} = shmem[{s}];')

        # One-sample lags are needed in the float16 case.
        self._apply_one_sample_lags(k)
        
        if return_early:
            return

        for i in range(self.rank1):
            self._dedispersion_pass(k, i)

    
    def emit_subband_extraction(self, k, fs):
        """Generator: emit the second stage of dedispersion, yielding one (rname, m, e)
        triple per (multiplet, "extra DM") pair.

        Used by cuda_generator.CoalescedDdKernel2 (whose consumer feeds the peak-finder)
        and cuda_generator.SbDedisperser (whose consumer stores to global memory).

        Args:
          k   Kernel, to emit into.
          fs  FrequencySubbands, with 0 <= fs.pf_rank <= self.rank1 (see xdm_rank()).

        Yields (rname, m, e): the name of the register holding multiplet 0 <= m < fs.M at
        "extra DM" 0 <= e < 2^K, where K = self.xdm_rank(fs). The subband array's DM index is

            d_pf = d' * 2^K + e      (where 0 <= d' < 2^rank0 is the warp's coarse DM)

        i.e. 'e' is the low K bits of the DM index of the shape (2^(rank-pf_rank), M, ntime)
        subband array, and each warp produces 2^K output DMs rather than one. When K == 0
        (fs.pf_rank == self.rank1), 'e' is always zero.

        THE GENERATOR MUST BE FULLY CONSUMED. It emits the remaining dedispersion passes
        *between* yields, so a consumer which breaks out early produces a kernel which
        compiles but computes the wrong thing. As a guard, this sets self.sbx_complete to
        False on entry and True on normal completion; callers should assert it after their
        loop. (For the same reason, calling this method without iterating it emits nothing
        at all.)

        PRECONDITION: the caller must have emitted _load_input_data() and
        _apply_input_residual_lags() for this time segment, and nothing else -- this method
        emits the whole second stage, starting with

            self._two_stage_dedispersion_core(k, return_early=True)

        (the first rank0 dedispersion passes, then the shared memory transpose). After that,
        registers dd0 .. dd{2^rank1 - 1} hold the data read back from the shared memory ring
        buffer, with register assignment

            register:  f       <->  coarse frequency 0 <= f < 2^rank1
            warp:      w       <->  bit-reversed coarse DM 0 <= d'_brev < 2^rank0
            thread:    t4..t0  <->  time (one sample per lane)

        and each register f carries the shmem ringbuf lag d' * (2^rank1 - 1 - f).

        POSTCONDITION: all rank1 dedispersion passes have been emitted, so dd0..dd{N-1}
        hold the full-band dedispersion output, with a bit-reversed fine DM in the register
        index.

        THE THREE STEPS. Write R = fs.pf_rank and K = rank1 - R, and split the register index
        as f = F * 2^K + u, where 0 <= F < 2^R is the "coarse-pf" frequency channel. Subband
        extraction needs each register to carry the time lag that ReferenceTree::final_lagbuf
        assigns, namely (2^R - fhi(m)) * d_pf, where fhi(m) is the subband's upper coarse-pf
        edge. The shmem lag above supplies this for the d' part of d_pf = d'*2^K + e only, so
        the second stage is emitted in three steps:

          1. Dedispersion passes 0 .. K-1, i.e. DD(K) within each group of 2^K registers.
             The shmem lag exceeds what DD(K) wants by 2^K * (2^R-1-F), which is independent
             of u and therefore commutes with these passes. Afterwards register (F,e) of warp
             d' holds coarse-pf channel F's own dedispersion output at DM index d_pf, lagged
             by 2^K * (2^R-1-F) * d'.

          2. Apply the compile-time lag

                 lambda(F,e) = e * (2^R-1-F)

             to each register. Step 1's leftover lag plus lambda is (2^R-1-F) * d_pf, which
             is exactly the input contract of a rank-R second stage. (For K == 0 every
             lambda is zero and this step emits nothing, which is why the pf_rank == rank1
             kernel needs no lag logic at all.)

          3. Run the ordinary rank-R subband extraction independently on each of the 2^K
             register groups { i : (i & (2^K-1)) == bit_reverse(e,K) }. Its own dedispersion
             passes then supply the (2^R - fhi) * d_pf subband lag for free.

        Step 3's passes must use GROUP-LOCAL lags (_dedispersion_pass()'s 'group_lsb'
        argument): the lag of group-local pass p is bit_reverse(j',p), computed from register
        index bits [K, K+p), not the bit_reverse(j, K+p) that a plain pass would use. The two
        agree at F = 2^R-1, so the full-band output -- and hence the POSTCONDITION above --
        is the same either way; only the subband outputs need the distinction.

        For the underlying math, see the "Subbanded dedispersion" and "The splitting
        identity" sections of notes/dedispersion.tex.

        REGISTER INDEX. After step 1's K passes plus l passes of step 3, the register holding
        coarse frequency f_hi, fine DM 0 <= d_lo < 2^l, and extra DM e is

            i = f_hi * 2^(l+K)  +  bit_reverse(d_lo,l) * 2^K  +  bit_reverse(e,K)

        i.e. 'e' is bit-reversed in the register index, and plain everywhere else (lags, DM
        indices, output array addresses).

        YIELD ORDER is increasing ((m << K) | e): pf_level, then band, then fine DM, then e.
        That matters: PeakFinder builds its transposes incrementally and bails out via
        'if (m & mbit) == 0: return', so it requires its input index to arrive in order (see
        PeakFinder.pfx_register_ready()). It is also availability order, since all 2^K
        registers of a multiplet are ready at the same moment. A consumer which does not care
        (e.g. a plain store) could take the odd-pfs multiplets earlier, in step 1 below, which
        would shorten the live range of the pfodd_* registers -- a possible future
        optimization.
        """

        assert self.two_stage

        R = fs.pf_rank      # subband granularity: the coarse-pf frequency axis has 2^R channels
        K = self.xdm_rank(fs)   # "extra DM" bits (also asserts 0 <= fs.pf_rank <= self.rank1)
        nxdm = 2**K         # number of "extra DM" values per multiplet

        self.sbx_complete = False   # see "MUST BE FULLY CONSUMED" above

        def ddname(ig, e):
            """Register holding group-local index 'ig' in the e-th register group."""
            return f'dd{(ig << K) + utils.bit_reverse(e,K)}'

        def pfodd_name(pf_level, pfs, pfd, e):
            """Register holding an odd-'pfs' multiplet, computed one dedispersion step early."""
            s = f'pfodd_l{pf_level}_s{pfs}_d{pfd}'
            return (s + f'_e{e}') if (K > 0) else s

        # First half of the second stage: rank0 dedispersion passes, then the shared memory
        # transpose. The remaining rank1 passes are emitted below (the first K in step 1, the
        # rest interleaved with the subband outputs in step 3).
        self._two_stage_dedispersion_core(k, return_early=True)

        dt32 = self.dt32
        sc = fs.subband_counts
        mcurr = 0

        # ---------------- Step 1: dedispersion passes 0 .. K-1 ----------------
        #
        # Ordinary passes: their register pairs and their lags live entirely in the low K
        # bits of the register index. (See "THE THREE STEPS" in the docstring.)

        for i in range(K):
            self._dedispersion_pass(k, i)

        # ---------------- Step 2: the lambda(F,e) lags ----------------

        lam = [ (F, e, e * (2**R - 1 - F)) for F in range(2**R) for e in range(nxdm) ]
        lam = [ (F,e,lag) for (F,e,lag) in lam if (lag != 0) ]

        if len(lam) > 0:
            k.emit()
            k.emit(f'// Apply the per-register lag lambda(F,e) = e * ({2**R-1} - F), where the')
            k.emit(f'// register index is (F * {nxdm} + bit_reverse(e,{K})). This converts the shmem')
            k.emit(f"// ringbuf lag, which is quantized in the warp's coarse DM d', into the lag")
            k.emit(f'// wanted by the pf_rank={R} subband extraction below, which is quantized in the')
            k.emit(f"// output DM d_pf = d'*{nxdm} + e. (See Dedisperser.emit_subband_extraction.)")
            k.emit()

            for F, e, lag in lam:
                rname = ddname(F, e)
                k.emit(f'// lambda: lag {rname} by {lag} time samples (F={F}, e={e})')
                self._advance1(k, rname, lag)

        # ---------------- Step 3, pf_level 0 ----------------
        #
        # Level 0 is a special case, because its bands are "unstaggered": each one is a
        # single coarse-pf channel, i.e. exactly one register per group, with a single
        # (trivial) fine DM. See the comments in FrequencySubbands.cpp.

        k.emit()
        k.emit(f'// Create {sc[0]} subband output(s) at pf_level 0. This is a special case,')
        k.emit(f'// because the bands are "unstaggered" (see comments in FrequencySubbands.cpp).')
        k.emit()

        for pfs in range(sc[0]):
            fs.check_m(mcurr, pfs, pfs+1, 0)     # (m, flo, fhi, fine_dm)
            for e in range(nxdm):
                yield (ddname(pfs, e), mcurr, e)
            mcurr += 1

        # ---------------- Step 3, pf_level 1 .. R ----------------
        #
        # On entry to iteration 'pf_level', the group-local register index decomposes as
        #
        #     ig = f_coarse * 2^(pf_level-1) + bit_reverse(fine_dm, pf_level-1)
        #
        # i.e. (pf_level-1) group-local dedispersion passes have been applied. A band at this
        # level spans coarse-pf range [pfs, pfs+2) * 2^(pf_level-1), so:
        #
        #   - even pfs: the band is "aligned" -- it is the group f_coarse = pfs/2 AFTER one
        #     more dedispersion pass, so we get it for free from step 2.
        #   - odd pfs: the band is "half-aligned", straddling groups pfs and pfs+1. It is
        #     one dedispersion step away from the registers we hold, so step 1 computes it
        #     into dedicated pfodd_* registers BEFORE the pass overwrites them.

        for pf_level in range(1, R+1):
            n_odd = len(range(1, sc[pf_level], 2))

            k.emit()
            k.emit(f'// pf_level {pf_level}: create {sc[pf_level]} "staggered" subband output(s).')
            k.emit(f'// Step 1: compute the {n_odd} odd value(s) of "pfs" into pfodd_* registers,')
            k.emit(f'// before step 2 overwrites the dd* registers they are built from.')
            k.emit()

            for pfs in range(1, sc[pf_level], 2):
                for pfd2 in range(2**(pf_level-1)):
                    for e in range(nxdm):
                        # Generate the multiplet pair (pfs, 2*pfd2) and (pfs, 2*pfd2+1) from the
                        # two half-bands, via one dedispersion step:
                        #     out[2*d]   = (in[lo, t-d] + in[hi, t]) / sqrt(2)
                        #     out[2*d+1] = (in[lo, t-d-1] + in[hi, t]) / sqrt(2)
                        isrc = pfs * 2**(pf_level-1) + utils.bit_reverse(pfd2, pf_level-1)
                        src0 = ddname(isrc, e)                        # lower half-band (needs the lag)
                        src1 = ddname(isrc + 2**(pf_level-1), e)      # upper half-band (defines t)
                        dst0 = pfodd_name(pf_level, pfs, 2*pfd2, e)
                        dst1 = pfodd_name(pf_level, pfs, 2*pfd2+1, e)
                        lag = pfd2

                        k.emit(f'// Sum with lag=({lag},{lag+1}): src=({src0},{src1}), dst=({dst0},{dst1})')

                        # _advance2() returns (src0 lagged by lag+1, src0 lagged by lag).
                        # It behaves differently for float32 vs float16 (see _advance2).
                        tmp0, tmp1 = self._advance2(k, src0, lag)

                        k.emit(f'{dt32} {dst0} = rsqrt2 * ({tmp1} + {src1});')
                        k.emit(f'{dt32} {dst1} = rsqrt2 * ({tmp0} + {src1});')

            k.emit()
            k.emit(f'// pf_level {pf_level}: Step 2 -- one dedispersion pass. Afterwards the')
            k.emit(f'// register index is  f_coarse * 2^{pf_level} + bit_reverse(fine_dm, {pf_level}).')

            if K > 0:
                k.emit(f'// (That is the GROUP-LOCAL register index -- the full register index is')
                k.emit(f'//  (group-local index) * {nxdm} + bit_reverse(e,{K}).)')

            k.emit()

            self._dedispersion_pass(k, pf_level-1, group_lsb=K)

            k.emit()
            k.emit(f'// pf_level {pf_level}: Step 3 -- yield every multiplet to the consumer,')
            k.emit(f'// in order of increasing m. Even "pfs" come from step 2, odd from step 1.')
            k.emit()

            for pfs in range(sc[pf_level]):
                for pfd in range(2**pf_level):
                    fs.check_m(mcurr, pfs * 2**(pf_level-1), (pfs+2) * 2**(pf_level-1), pfd)

                    for e in range(nxdm):
                        if pfs % 2:
                            name = pfodd_name(pf_level, pfs, pfd, e)
                        else:
                            isrc = (pfs//2) * 2**pf_level + utils.bit_reverse(pfd, pf_level)
                            name = ddname(isrc, e)

                        yield (name, mcurr, e)

                    mcurr += 1

        assert mcurr == fs.M
        self.sbx_complete = True


    def xdm_rank(self, fs):
        """Returns the number of "extra DM" bits in the second stage: (rank1 - fs.pf_rank).

        Each warp of the subbanded kernels produces 2^xdm_rank output DMs, whose indices are
        the low bits of the subband array's DM axis. See emit_subband_extraction() for the
        full story, and for why xdm_rank must be >= 0.
        """

        assert self.two_stage
        assert 0 <= fs.pf_rank <= self.rank1
        return self.rank1 - fs.pf_rank


    def _dedispersion_pass(self, k, i, group_lsb=0):
        """Emit one dedispersion pass, pairing registers whose indices differ in bit (group_lsb+i).

        If 'group_lsb' is nonzero, the low 'group_lsb' bits of the register index are
        spectators: the pass acts independently on each of the 2^group_lsb interleaved
        register groups, and the time lag comes from the group-local index bits
        [group_lsb, group_lsb+i) alone. With group_lsb=0 this is an ordinary dedispersion
        pass over all 2^rank1 registers. (See emit_subband_extraction(), the only caller
        that passes group_lsb > 0, for why the group-local lag is the correct one.)
        """

        nreg = utils.integer_log2(self.ndd)
        assert 0 <= group_lsb <= nreg
        assert 0 <= i < (nreg - group_lsb)

        gs = f' (group_lsb={group_lsb})' if (group_lsb > 0) else ''

        k.emit()
        k.emit(f'// dedispersion_pass: pass {i}{gs} starts here')

        # Outer loop is a spectator index (register index bits above group_lsb+i).
        # Inner loop is the other spectator index (register index bits below group_lsb).
        for s in range(0, self.ndd, 2**(group_lsb+i+1)):
            for j in range(2**i):
                for g in range(2**group_lsb):
                    x0 = f'dd{s + (j << group_lsb) + g}'
                    x1 = f'dd{s + ((j + 2**i) << group_lsb) + g}'
                    lag = utils.bit_reverse(j,i)

                    k.emit(f'// dedisperse {x0}, {x1} with time lag {lag} (not accounting for nbits, nspec)')
                    tmp0, tmp1 = self._advance2(k, x0, lag)
                    k.emit(f'{x0} = rsqrt2 * ({tmp1} + {x1});')
                    k.emit(f'{x1} = rsqrt2 * ({tmp0} + {x1});')

        k.emit(f'// dedispersion_pass: pass {i}{gs} ends here')


    def _advance2(self, k, x0, lag):
        """Lag is in time samples, and does not account for nbits, nspec."""
        
        lag32a = (lag * self.nbits * self.nspec) // 32
        lag32b = (self.nbits * self.nspec) // 32

        if lag32b > 0:
            # Case 1: one time sample corresponds to an integer number of 32-bit registers.
            tmp0, tmp1 = self.rrb.advance2(k, x0, lag32a, lag32b)
        else:
            # Case 2 (contrary case): should only get here if dtype==float16 and nspec==1.
            assert (self.dtype.scalar == '__half') and (self.nspec == 1)
            tmp0, tmp1 = self.rrb.advance2(k, x0, lag32a, 1)
            tdst = tmp1 if (lag % 2) else tmp0
            k.emit(f'{tdst} = ksgpu::f16_align({tmp0}, {tmp1});')
        
        return tmp0, tmp1
        

    def _advance1(self, k, x0, lag):
        """Apply a time lag to register 'x0', in place.

        Single-register analogue of _advance2() (which applies a pair of consecutive lags, and
        returns them in temporaries). Lag is in time samples, and does not account for nbits,
        nspec.
        """

        if lag == 0:
            return

        lag32a = (lag * self.nbits * self.nspec) // 32
        lag32b = (self.nbits * self.nspec) // 32

        if (lag32b > 0) or ((lag % 2) == 0):
            # Case 1: the lag is an integer number of 32-bit registers, either because one
            # time sample is (lag32b > 0), or because the lag is an even number of float16
            # half-samples.
            assert (lag32b > 0) or ((self.dtype.scalar == '__half') and (self.nspec == 1))
            self.rrb.advance(k, x0, lag32a)
        else:
            # Case 2 (contrary case): float16 with nspec==1, and an odd lag. The ring buffer
            # can only lag by whole 32-bit registers (= 2 time samples), so we take the two
            # neighboring lags and combine their halves, as in _advance2().
            assert (self.dtype.scalar == '__half') and (self.nspec == 1)
            tmp0, tmp1 = self.rrb.advance2(k, x0, lag32a, 1)   # lagged by (lag+1), (lag-1) samples
            k.emit(f'{x0} = ksgpu::f16_align({tmp0}, {tmp1});')


    def _apply_input_residual_lags(self, k):
        if not self.apply_input_residual_lags:
            return

        k.emit(f'// Apply input "residual" lags.')
        k.emit(f'//')
        k.emit(f'// Context: consider the second stage in a two-stage dedisperser.')
        k.emit(f'// The ambient index corresponds to a bit-reversed DM 0 <= dm_brev < 2^(ambient_rank).')
        k.emit(f'// Each input register corresponds to a coarse frequency 0 <= f < 2^(dd_rank).')
        k.emit(f'//')
        k.emit(f'// Between the two stages of the tree, we want to apply the following lag:')
        k.emit(f'//    lag = dm * frev')
        k.emit(f'//')
        k.emit(f'// where:')
        k.emit(f'//    dm = bit_reverse(dm_brev) + (is_downsampled_tree ? 2^ambient_rank : 0)')
        k.emit(f'//    frev = 2^dd_rank - 1 - f')
        k.emit(f'//')
        k.emit(f'// However, due to cache-alignment constraints, we are only able to apply (lag % T),')
        k.emit(f'// where T = self.nt_per_segment.  To address this, the dedispersion kernel is')
        k.emit(f'// responsible for applying the "residual" lag:')
        k.emit(f'//    rlag = lag % T')
        k.emit(f'//')
        k.emit(f'// FIXME: poorly optimized, especially in float16 case')
        k.emit()
        
        T = self.nt_per_segment
        B = self.nspec * self.nbits
        assert T*B == 1024
        
        k.emit(f'uint rlag_f0 = threadIdx.y << {utils.integer_log2(self.ndd)};         // 0 <= rlag_f0 < 2^(dd_rank)')
        k.emit(f'uint rlag_dm = __brev(blockIdx.x) >> (33U - __ffs(gridDim.x));   // 0 <= rlag_dm < 2^(ambient rank)')
        k.emit(f'rlag_dm += (is_downsampled_tree ? gridDim.x : 0);')

        for i in range(self.ndd):
            rlag = k.get_tmp_rname()
            k.emit(f'uint {rlag} = (rlag_dm * ({2**self.rank-1-i} - rlag_f0)) & {T-1};   // rlag to be applied to dd{i}')

            if (B % 32) == 0:
                # Case 1: one time sample corresponds to an integer number of 32-bit registers.
                if B > 32:
                    k.emit(f'{rlag} <<= {utils.integer_log2(B//32)};   // convert rlag (time samples) -> (32-bit registers)')
                
                tmp = k.get_tmp_rname()
                k.emit(f'{self.dt32} {tmp} = ((threadIdx.x + {rlag}) >= 32) ? dd_rlag{i} : dd{i};')
                k.emit(f'dd_rlag{i} = dd{i};')
                k.emit(f'dd{i} = __shfl_sync(0xffffffff, {tmp}, threadIdx.x - {rlag});   // rlag has now been applied to dd{i}')

            else:
                # Case 2 (contrary case): should only get here if dtype==float16 and nspec==1.
                assert (self.nbits == 16) and (self.nspec == 1)
                rlag2, tmp, tmp2 = k.get_tmp_rname(3)
                k.emit(f'uint {rlag2} = {rlag} >> 1;   // (rlag // 2)')

                k.emit(f'if ({rlag} & 1) {{')
                k.emit(f'    {self.dt32} {tmp} = ((threadIdx.x + {rlag2} + 1) >= 32) ? dd_rlag{i} : dd{i};')
                k.emit(f'    {self.dt32} {tmp2} = ((threadIdx.x + {rlag2}) >= 32) ? dd_rlag{i} : dd{i};')
                k.emit(f'    dd_rlag{i} = dd{i};')
                k.emit(f'    {tmp} = __shfl_sync(0xffffffff, {tmp}, threadIdx.x - {rlag2} - 1);')
                k.emit(f'    {tmp2} = __shfl_sync(0xffffffff, {tmp2}, threadIdx.x - {rlag2});')
                k.emit(f'    dd{i} = ksgpu::f16_align({tmp}, {tmp2});')
                k.emit(f'}}')
                k.emit(f'else {{')
                k.emit(f'    {self.dt32} {tmp} = ((threadIdx.x + {rlag2}) >= 32) ? dd_rlag{i} : dd{i};')
                k.emit(f'    dd_rlag{i} = dd{i};')
                k.emit(f'    dd{i} = __shfl_sync(0xffffffff, {tmp}, threadIdx.x - {rlag2});')
                k.emit(f'}}     // rlag has now been applied to dd{i}')

    
    def _apply_one_sample_lags(self, k):
        if (self.nbits != 16) or (self.nspec != 1) or (self.rank0 == 0):
            return

        k.emit(f'// Apply one-sample lags (float16 nspec=1 only)')
        k.emit(f'// A one-sample lag is needed if:')
        k.emit(f'//    - register index is even (equivalent to odd frev)')
        k.emit(f'//    - (warpId & {2**(self.rank0-1)}) is 1 (equivalent to odd dm)')
        k.emit(f'//')
        k.emit(f'// FIXME: suboptimal approach, should coalesce with dd1')
        k.emit()
        
        sel = k.get_tmp_rname()
        k.emit(f'uint {sel} = (threadIdx.y & {2**(self.rank0-1)}) ? 0x5432 : 0x7654;')

        for i in range(0, self.ndd, 2):  # even registers
            xprev = k.get_tmp_rname()
            k.emit(f'__half2 {xprev};   // will hold result of Ringbuf.advance(dd{i},1)')
            self.rrb.advance(k, f'dd{i}', 1, dst=xprev)
            k.emit(f'dd{i} = ksgpu::f16_perm({xprev}, dd{i}, {sel});  // dd{i} has now been lagged by one sample, if needed')
        
        k.emit()
        

    def _apply_inbuf_offsets(self, k):
        k.emit('// Dedisperser._apply_inbuf_offsets() starts here.')
        
        if self.input_is_ringbuf:
            wshift = self.rank1 if self.two_stage else self.rank
            self._apply_grb_offsets(k, wshift)

        else:
            # Non-ringbuf case
            k.emit(f'// Apply per-thread offsets to inbuf (including laneId offset).')
            k.emit(f'{self.dt32} *inbuf = ({self.dt32} *) inbuf_;')
            k.emit(f'inbuf += long(beam_istride32) * long(blockIdx.y);   // beam = blockIdx.y')
            k.emit(f'inbuf += long(amb_istride32) * long(blockIdx.x);    // ambient = blockIdx.x')
        
            if self.two_stage:
                k.emit(f'inbuf += {2**self.rank1} * long(act_istride32) * long(threadIdx.y);   // warpId = threadIdx.y')
            
            k.emit(f'inbuf += threadIdx.x;   // laneId')

        k.emit('// Dedisperser._apply_inbuf_offsets() ends here.')
        k.emit()


    def _apply_outbuf_offsets(self, k):
        if self.output_is_ringbuf:
            self._apply_grb_offsets(k, 0)
            return

        # Non-ringbuf case follows.
        k.emit(f'// Apply per-thread offsets to outbuf (including laneId offset).')
        k.emit(f'{self.dt32} *outbuf = ({self.dt32} *) outbuf_;')
        k.emit(f'outbuf += long(beam_ostride32) * long(blockIdx.y);   // beam = blockIdx.y')
        k.emit(f'outbuf += long(amb_ostride32) * long(blockIdx.x);    // ambient = blockIdx.x')
        
        if self.two_stage:
            k.emit(f'outbuf += long(act_ostride32) * long(threadIdx.y);   // warpId = threadIdx.y')
            
        k.emit(f'outbuf += threadIdx.x;   // laneId')
        k.emit()


    def _apply_grb_offsets(self, k, wshift):
        wshift = f' << {wshift}' if (wshift > 0) else ''
        
        k.emit(f'// Apply per-thread offsets to global memory ring buffer')
        k.emit(f'// Note: grb_quads is indexed by (tseg, amb, active_ix)')
        k.emit(f'// where active_ix = (freq for input ringbuf, or dmbr for output ringbuf)')

        k.emit(f'{self.dt32} *grb_base = ({self.dt32} *) grb_base_;')
        k.emit(f'uint4 *grb_quads = (uint4 *) (grb_quads_);')
        k.emit(f'grb_quads += (blockIdx.x << {self.rank});   // dm_amb = blockIdx.x')
        k.emit(f'grb_quads += threadIdx.y{wshift};   // warpId')
        k.emit(f'grb_frame0 += blockIdx.y;    // beam = blockIdx.y')

    
    def _init_srb(self, k):
        if not self.two_stage:
            k.emit('// Dedisperser._init_srb() called, but is a no-op, since two_stage == False.')
            return
        
        rank0, rank1 = self.rank0, self.rank1
        B = self.nspec * self.nbits
        
        k.emit('// Dedisperser._init_srb() starts here.')
        k.emit('// Init control words for two-stage kernel.')
        k.emit('// A ring buffer "control word" consists of:')
        k.emit('//')
        k.emit('//   uint15 srb_base;   // base shared memory location of ring buffer (in 32-bit registers)')
        k.emit('//   uint9  srb_pos;    // current position, satisfying 0 <= srb_pos < (srb_lag + 32)')
        k.emit('//   uint8  srb_lag;    // ring buffer lag (in 32-bit registers), note that capacity = lag + 32.')
        k.emit('//')
        k.emit('// Depending on context, srb_pos may point to either the end of the buffer')
        k.emit('// (writer thread context), or be appropriately lagged (reader thread context).')
        k.emit('//')
        k.emit(f'// Lanes [0:{2**rank1}] hold control words for registers in the first pass:')
        k.emit(f'//')
        k.emit(f'//   - registers form a ({2**(rank1-rank0)}, {2**rank0}) array, where first index is a "fast"')
        k.emit(f'//     frequency 0 <= ff < {2**(rank1-rank0)} and second index is 0 <= dm_brev < {2**rank0}')
        k.emit(f'//   - warpId is a "slow" frequency 0 <= fs < {2**rank0}')
        k.emit(f'//   - writer thread context')
        k.emit(f'//')
        k.emit(f'// Lanes [16:16+{2**rank1}] hold control words for registers in the second pass:')
        k.emit(f'//')
        k.emit(f'//   - register index is a frequency 0 <= f < {2**rank1})')
        k.emit(f'//   - warpId is 0 <= dm_brev < {2**rank0}')
        k.emit(f'//   - reader thread context')
        k.emit()

        first_pass, dm_brev, dm, f, frev = k.get_tmp_rname(5)

        dr = rank1 - rank0
        fpass1 = 'threadIdx.y' if (dr==0) else f'(threadIdx.y << {dr}) | ((threadIdx.x >> {rank0}) & {2**dr-1})'

        k.emit(f'// Compute frev, dm.')
        k.emit(f'bool {first_pass} = (threadIdx.x < 16);   // first_pass')
        k.emit(f'uint {dm_brev} = {first_pass} ? (threadIdx.x & {2**rank0-1}) : threadIdx.y;   // dm_brev')
        k.emit(f'uint {dm} = __brev({dm_brev}) >> {32-rank0};   // dm')
        k.emit(f'uint {f} = {first_pass} ? ({fpass1}) : (threadIdx.x & {2**rank1-1});  // f')
        k.emit(f'uint {frev} = {2**rank1-1} - {f};   // frev')
        k.emit()

        k.emit(f'// Compute (srb_lag, srb_base) from (frev, dm).')
        k.emit(f'// This part uses some cryptic, highly optimized code from Dedisperser.srb_base()')

        if (B % 32) == 0:
            # Case 1: one time sample corresponds to an integer number of 32-bit registers.
            a = (B//32) * 2**(rank1-1) * (2**rank1-1)
            b = 2**(rank1+6) - a
            
            t, srb_base, srb_lag = k.get_tmp_rname(3)
            
            k.emit(f'uint {t} = {frev}*({frev}-1);')
            if B > 32:
                k.emit(f'{t} <<= {utils.integer_log2(B//32)};')

            k.emit(f'{t} += {a}*{dm} + {b};')
            k.emit(f'uint {srb_base} = (({dm}*{t}) >> 1) + ({frev} << 5);  // srb_base (32-bit registers, not time samples)')

            k.emit(f'uint {srb_lag} = {dm}*{frev};  // srb_lag')
            if B > 32:
                k.emit(f'{srb_lag} <<= {utils.integer_log2(B//32)};  // convert srb_lag (time samples) -> (32-bit registers)')
                
        else:
            # Case 2 (contrary case): should only get here if dtype==float16 and nspec==1.
            assert (self.dtype.scalar == '__half') and (self.nspec == 1)
            a = (2**rank1 - 1) * 2**(rank1-1)
            b = (256 - 2**rank1) * 2**(rank1-1)
            c = 2**(rank1-1) + 1

            u, t, srb_base, srb_lag = k.get_tmp_rname(4)
            k.emit(f'uint {u} = {a}*{dm} + {frev}*({frev}-1) + {b};')
            k.emit(f'uint {t} = ({dm}*{u}) + ({dm} & 1) * ({c}-{frev});')
            k.emit(f'uint {srb_base} = ({t} >> 2) + ({frev} << 5);  // srb_base')
            k.emit(f'uint {srb_lag} = ({dm}*{frev}) >> 1;  // srb_lag')

        k.emit()
        k.emit(f'// Compute srb_pos, and assemble control word from (srb_lag, srb_base)')
        k.emit(f'// Note: srb_pos = 32 * (nt_cumul / nt_per_segment), where nt_per_segment = {self.nt_per_segment}')
        
        # Left shift needed for (nt_cumul) -> (nt_per_segment), can be negative.
        ls = 5 - utils.integer_log2(self.nt_per_segment)

        srb_pos = k.get_tmp_rname()
        if ls > 0:
            k.emit(f'uint {srb_pos} = nt_cumul << {ls};   // srb_pos')
        elif ls < 0:
            k.emit(f'uint {srb_pos} = nt_cumul >> {-ls};  // srb_pos')
        else:
            k.emit(f'uint {srb_pos} = nt_cumul;  // srb_pos')

        k.emit(f'{srb_pos} += ({first_pass} ? 0 : 32);   // srb_pos: add reader/writer offset')
        k.emit(f'{srb_pos} %= ({srb_lag} + 32U);         // srb_pos: mod (srb_lag + 32)')
        k.emit(f'uint control_word = {srb_base} | ({srb_pos} << 15) | ({srb_lag} << 24);')
        k.emit('// Dedisperser._init_srb() ends here.')
        k.emit()


    def _srb_loc(self, k, control_lane):
        w, srb_base, srb_pos, srb_size, wraparound, ret = k.get_tmp_rname(6)
        k.emit(f'uint {w} = __shfl_sync(0xffffffff, control_word, {control_lane});  // srb_loc({control_lane=}) starts here')
        k.emit(f'uint {srb_base} = ({w} & 0x7fff);        // srb_base, 15 bits')
        k.emit(f'uint {srb_pos} = (({w} >> 15) & 0x1ff) + threadIdx.x;   // srb_pos, 9 bits (note laneId at end)')
        k.emit(f'uint {srb_size} = ({w} >> 24) + 32;      // srb_size, 8 bits (note +32 here to convert srb_lag -> srb_size')
        k.emit(f'uint {wraparound} = ({srb_pos} >= {srb_size}) ? {srb_size} : 0;  // wraparound')
        k.emit(f'uint {ret} = {srb_base} + {srb_pos} - {wraparound};  // srb_loc({control_lane=}) return value')
        return ret


    def _advance_rrb(self, k):
        k.emit('// Advance in-register ring buffer for next iteration of loop')
        self.rrb.advance_outer(k)
        k.emit()

    
    def _advance_srb(self, k):
        if not self.two_stage:
            return

        pos15, lag15, dpos15 = k.get_tmp_rname(3)
        
        k.emit(f'// Advance control words (for shared memory ring buffer)')
        k.emit(f'int {pos15} = (control_word & 0xff8000);  // pos15')
        k.emit(f'int {lag15} = ((control_word >> 9) & 0xff8000);  // lag15')
        k.emit(f'int {dpos15} = ({pos15} >= {lag15}) ? {lag15} : (-(32 << 15));  // dpos15')
        k.emit(f'control_word = (control_word & 0xff007fff) | ({pos15} - {dpos15});')
        k.emit()

    
    def _advance_inbuf(self, k):
        if self.input_is_ringbuf:
            self._advance_grb(k)
        else:
            k.emit('// Advance inbuf pointer')
            k.emit('inbuf += 32;')
            k.emit()
    

    def _advance_outbuf(self, k):
        if self.output_is_ringbuf:
            self._advance_grb(k)
        else:
            k.emit('// Advance outbuf pointer')
            k.emit('outbuf += 32;')
            k.emit()

    
    def _advance_grb(self, k):
        k.emit('// Advance global memory ring buffer')
        k.emit(f'grb_quads += (gridDim.x << {self.rank});   // nambient = gridDim.x')
        k.emit()
        

    def _lay_out_pstate(self, k):
        RL32 = (32*self.ndd) if self.apply_input_residual_lags else 0    # registers for apply_input_residual_lags, per warp
        RB32 = self.rrb.get_n32_per_warp()                               # registers for in-register ringbuf, per warp
        SM32 = utils.xdiv(self.shmem_nbytes,4)                           # shared memory 32-bit words, per threadblock
        W = self.warps_per_threadblock
        
        k.emit(f'// Per-threadblock persistent state layout is {self.dt32}[PS32], broken down as follows:')
        k.emit(f'//    {self.dt32} srb[SM32];')
        k.emit(f'//    {self.dt32} rrb[{W}][RL32+RB32];  // outer index is warp id')
        k.emit(f'//')
        k.emit(f'// where definitions of PS32, SM32, RL32, RB32 follow.')
        k.emit()
        k.emit(f'constexpr int {RL32 = };    // 32-bit elements per **warp** needed for apply_input_residual_lags')
        k.emit(f'constexpr int {RB32 = };    // 32-bit elements per **warp**, in **register** ring buffer')
        k.emit(f'constexpr int {SM32 = };  // 32-bit elements per **threadblock**, in **shmem** ring buffer')
        k.emit(f'constexpr int PS32 = SM32 + {W}*(RL32+RB32);   // total persistent state per **threadblock**')
        k.emit()
        
        self.pstate32_per_small_tree = SM32 + W*(RL32+RB32)

        k.emit("// Apply per-block offset to pstate")
        k.emit(f'int blockId = (gridDim.x * blockIdx.y) + blockIdx.x;')
        k.emit(f'{self.dt32} *pstate = ({self.dt32} *)pstate_;')
        k.emit(f"pstate += blockId * PS32;")
        k.emit()

        
    def _load_pstate(self, k):
        if self.two_stage:
            k.emit(f'extern __shared__ {self.dt32} shmem[];')
            k.emit()
            k.emit(f'// Load shmem ring buffer from global memory')
            k.emit(f'// NOTE no __syncthreads() here')
            k.emit(f'for (int s = 32*threadIdx.y + threadIdx.x; s < SM32; s += {32*self.warps_per_threadblock})')
            k.emit(f'    shmem[s] = pstate[s];')
            k.emit('__syncwarp();')
            k.emit()

        wp = self._warp_pstate1(k)
        
        if self.apply_input_residual_lags:
            k.emit('// Load persistent state for apply_input_residual_lags')
            for i in range(self.ndd):
                i32 = f' + {32*i}' if (i > 0) else ''
                k.emit(f'{self.dt32} dd_rlag{i} = {wp}[threadIdx.x{i32}];')
            
            k.emit()
            wp = self._warp_pstate2(k, wp)
        
        k.emit('// Read register ring buffer directly from global memory.')
        k.emit('// FIXME: would it be better to go through shared memory?')

        self.rrb.initialize(k, wp)
        k.emit()
        

    def _save_pstate(self, k):
        if self.two_stage:
            k.emit(f'// Write shmem ring buffer to global memory')
            k.emit(f'for (int s = 32*threadIdx.y + threadIdx.x; s < SM32; s += {32*self.warps_per_threadblock})')
            k.emit(f'    pstate[s] = shmem[s];')
            k.emit(f'__syncwarp();')
            k.emit()
        
        wp = self._warp_pstate1(k)
        
        if self.apply_input_residual_lags:
            k.emit('// Save persistent state for apply_input_residual_lags')
            for i in range(self.ndd):
                i32 = f' + {32*i}' if (i > 0) else ''
                k.emit(f'{wp}[threadIdx.x{i32}] = dd_rlag{i};')

            k.emit()
            wp = self._warp_pstate2(k, wp)
            
        k.emit('// Write register ring buffer to global memory.')
        k.emit('// FIXME: would it be better to go through shared memory?')
        k.emit()
        
        self.rrb.finalize(k, wp)
        k.emit()


    def _warp_pstate1(self, k):
        if (self.shmem_nbytes == 0) and (self.warps_per_threadblock == 1):
            return 'pstate'
        
        wp = k.get_tmp_rname()
        k.emit(f'// Per-warp ring buffer in global memory (length RL32+RB32)')
        k.emit(f'{self.dt32} *{wp} = pstate + SM32 + (threadIdx.y * (RL32+RB32));')
        k.emit()
        
        return wp

    
    def _warp_pstate2(self, k, wp):
        wp2 = k.get_tmp_rname()
        k.emit(f'// Per-warp ring buffer in global memory, second part (length RB32)')
        k.emit(f'{self.dt32} *{wp2} = {wp} + RL32;')
        k.emit()
        
        return wp2


    def _show_shmem_layout_in_comment(self, k):
        if not self.two_stage:
            return
        
        for dm in range(2**self.rank0):
            for frev in range(2**self.rank1):
                srb_lag = (frev * dm * self.nbits) // 32
                srb_size = srb_lag + 32
                srb_base = self.srb_base(dm, frev)
                k.emit(f'//   {dm=} {frev=}: {srb_lag=} {srb_size=} {srb_base=}')
        k.emit()
    
    
    def static_asserts(self):
        assert self.two_stage
        expected_pos = 0
        
        for dm in range(2**self.rank0):
            for frev in range(2**self.rank1):
                assert self.srb_base(dm,frev) == expected_pos
                lag32 = (frev * dm * self.nspec * self.nbits) // 32
                
                assert lag32 <= 255   # assumed in srb "control word" layout above
                expected_pos += (lag32 + 32)

        assert self.shmem_nbytes == (expected_pos * 4)
        # print(f'static_asserts(rank0={self.rank0}, rank1={self.rank1}): pass')
        

    def srb_base(self, dm, frev):
        """Called by static_asserts(). Also called directly in constructor for shmem_nbytes."""

        assert self.two_stage
        rank0, rank1 = self.rank0, self.rank1
        assert 0 <= dm <= 2**rank0   # note <=
        assert 0 <= frev < 2**rank1  # note <
        assert rank1 >= 2            # assumed below as noted

        B = self.nspec * self.nbits

        if (B % 32) == 0:
            # Case 1: one time sample corresponds to an integer number of 32-bit registers.
            
            # "Intuitive form"
            # n1 = 2**rank1
            # term1 = ((dm*(dm-1))//2) * ((n1*(n1-1))//2)   # d < dm, all f
            # term2 = dm * ((frev*(frev-1)) // 2)           # d == dm, f < frev
            # term3 = 32 * (dm*n1 + frev)                   # 32-bit padding from previous (dm,f)
            # return (term1 + term2) * (B//32) + term3
            
            # "Fast form" with slightly fewer ops (assumes rank1 >= 1)
            a = (B//32) * 2**(rank1-1) * (2**rank1-1)  # known at compile time
            b = 2**(rank1+6) - a                       # known at compile time
            t = (frev*(frev-1)) << utils.integer_log2(B//32)
            t += a*dm + b
            return ((dm*t) >> 1) + (frev << 5)

        else:
            # Case 2 (contrary case): should only get here if dtype==float16 and nspec==1.
            assert (self.nbits == 16) and (self.nspec == 1)

            # "Intuitive form" (assumes rank1 >= 2)
            # n1 = 2**rank1
            # term1 = ((dm*(dm-1))//2) * ((n1*(n1-1)) // 4)    # d < dm, all f
            # term1 -= (dm//2) * (n1//4)                       # corrections from odd d
            # term2 = (dm * frev * (frev-1)) // 4              # d == dm, f < frev
            # term2 -= (dm & 1) * (frev // 4)                  # correction if dm is odd
            # term3 = 32 * (dm*n1 + frev)
            # return (term1 + term2 + term3) * (B//32)

            # "Fast form" with slightly fewer ops (assumes rank1 >= 2)
            a = (2**rank1 - 1) * 2**(rank1-1)     # known at compile time
            b = (256 - 2**rank1) * 2**(rank1-1)   # known at compile time
            c = 2**(rank1-1) + 1                  # known at compile time
            u = a*dm + frev*(frev-1) + b
            t = (dm*u) + (dm & 1) * (c-frev)
            return (t >> 2) + (frev << 5)


####################################################################################################


class MultiDedisperser:
    """
    Represents multiple dedispersion kernels in the same .cu file.
    
    This is similar to how 'class PeakFinder' represents a single peak-finding kernel.
    The API includes a 'kernel_basename' member and a classmethod 'write_kernel()'.
    """
    
    def __init__(self, dtype, apply_input_residual_lags, input_is_ringbuf, output_is_ringbuf, nspec):
        """Construct a MultiDedisperser.

        Takes individual parameters (no 'rank' argument).
        The rank_list is computed internally in emit_kernel().
        """

        dtype = Dtype(dtype)
        
        assert 1 <= nspec <= (512 // dtype.nbits)
        assert utils.is_power_of_two(nspec)
        assert not (input_is_ringbuf and output_is_ringbuf)
        
        self.dtype = dtype
        self.apply_input_residual_lags = apply_input_residual_lags
        self.input_is_ringbuf = input_is_ringbuf
        self.output_is_ringbuf = output_is_ringbuf
        self.nspec = nspec

        if (not input_is_ringbuf) and (not output_is_ringbuf):
            rb = 'norb'
        elif (input_is_ringbuf) and (not output_is_ringbuf):
            rb = 'inrb'
        elif (not input_is_ringbuf) and (output_is_ringbuf):
            rb = 'outrb'
        else:
            raise RuntimeError('should never get here')

        lag = 'rlag' if apply_input_residual_lags else 'nolag'
        self.kernel_basename = f'dd_{dtype.fname}_{rb}_{lag}_s{nspec}.cu'


    def emit_kernel(self, k):
        """Emit kernel code to the given Kernel object."""
        
        # This expression for the max rank derives from the requirement that shared
        # memory lags must be at most 255 32-bit registers.
        max_rank = 13 - utils.integer_log2(self.dtype.nbits * self.nspec)
        max_rank = min(max_rank, 8)   # also Dedisperser's own bound on 'rank'

        # Compute the rank_list (all ranks from 1 to max_rank).
        rank_list = list(range(1, max_rank + 1))
        
        k.emit('// Autogenerated by pirate_frb.cuda_generator')
        k.emit()
        k.emit('// For a high-level overview, see comments at the top of')
        k.emit('// pirate_frb/cuda_generator/Dedisperser.py')
        k.emit()
        k.emit('#include <cstdio>')
        k.emit('#include <cassert>')
        k.emit('#include <ksgpu/device_fp16.hpp>   // f16_perm(), f16_align()')
        k.emit('#include "../../include/pirate/DedispersionKernel.hpp"')
        k.emit()
        k.emit('namespace pirate {')
        k.emit()

        k_code = k.splice()

        for rank in rank_list:
            dd = Dedisperser(
                dtype = self.dtype,
                rank = rank,
                apply_input_residual_lags = self.apply_input_residual_lags,
                input_is_ringbuf = self.input_is_ringbuf,
                output_is_ringbuf = self.output_is_ringbuf,
                nspec = self.nspec
            )

            dd.emit_global(k_code)
            k_code.emit()
            k_code.reset_names()
            
            k.emit(f'// Boilerplate to register the rank={rank} kernel when the library is loaded.')
            k.emit('namespace {')
            k.emit(f'struct register_hack{rank} {{')
            k.emit(f'register_hack{rank}() {{')
            k.emit()

            k.emit('GpuDedispersionKernel::RegistryKey k;')
            k.emit(f'k.dtype = ksgpu::Dtype::native<{self.dtype.scalar}>();')
            k.emit(f'k.rank = {rank};')
            k.emit(f'k.nspec = {self.nspec};')
            k.emit(f'k.input_is_ringbuf = {utils.tf(self.input_is_ringbuf)};')
            k.emit(f'k.output_is_ringbuf = {utils.tf(self.output_is_ringbuf)};')
            k.emit(f'k.apply_input_residual_lags = {utils.tf(self.apply_input_residual_lags)};')
            k.emit()
            
            k.emit('GpuDedispersionKernel::RegistryValue v;')
            k.emit(f'v.shmem_nbytes = {dd.shmem_nbytes};')
            k.emit(f'v.warps_per_threadblock = {dd.warps_per_threadblock};')
            k.emit(f'v.pstate32_per_small_tree = {dd.pstate32_per_small_tree};')
            k.emit(f'v.nt_per_segment = {dd.nt_per_segment};')

            if (not self.input_is_ringbuf) and (not self.output_is_ringbuf):
                k.emit(f'v.cuda_kernel_no_rb = {dd.kernel_name};')
            elif (self.input_is_ringbuf) and (not self.output_is_ringbuf):
                k.emit(f'v.cuda_kernel_in_rb = {dd.kernel_name};')
            elif (not self.input_is_ringbuf) and (self.output_is_ringbuf):
                k.emit(f'v.cuda_kernel_out_rb = {dd.kernel_name};')
            else:
                raise RuntimeError('Error: input_is_ringbuf == output_is_ringbuf == True')

            k.emit()
            
            k.emit(f'bool debug = false;')
            k.emit(f'GpuDedispersionKernel::registry().add(k,v,debug);')
            k.emit()
        
            k.emit(f'}}   // register_hack{rank} constructor')
            k.emit(f'}};  // struct register_hack{rank}')
            k.emit(f'register_hack{rank} hack{rank};')
            k.emit('}   // anonymous namespace')
            k.emit()

        k.emit('} // namespace pirate')


    @classmethod
    def write_kernel(cls, filename):
        """
        Called from 'autogenerate_kernel.py' in the toplevel pirate directory.

        The filename can include an optional leading directory and a trailing '.cu'.
        For example, /path/to/dd_fp16_inrb_rlag_s8.cu matches.
        """

        basename = os.path.basename(filename)

        rb_dict = { 'norb': (False,False), 'inrb': (True,False), 'outrb': (False,True) }   # (in_rb, out_rb)
        lag_dict = { 'nolag': False, 'rlag': True}   # rlag

        try:
            # Reminder: (?:...) defines a "non-capturing group".
            m = re.match(r'^(?:.*/)?dd_(fp\d+)_([a-z]+rb)_([a-z]+lag)_s(\d+)(?:\.cu)?', basename)
            dtype = Dtype(m.group(1))
            irb, orb = rb_dict[m.group(2)]
            rlag = lag_dict[m.group(3)]
            nspec = int(m.group(4))
        except:
            raise RuntimeError(f"cuda_generator.MultiDedisperser: couldn't parse {filename=}")

        multi_dd = cls(
            dtype = dtype,
            apply_input_residual_lags = rlag,
            input_is_ringbuf = irb,
            output_is_ringbuf = orb,
            nspec = nspec
        )
        
        if multi_dd.kernel_basename != basename:
            raise RuntimeError("MultiDedisperser.write_kernel(): internal error: expected "
                               + f" {multi_dd.kernel_basename=} and {basename=} to be equal")
        
        k = Kernel()
        multi_dd.emit_kernel(k)
        
        k.write_file(filename)