import os
import re

from . import utils

from .Dtype import Dtype
from .Kernel import Kernel
from .FrequencySubbands import FrequencySubbands
from .Dedisperser import Dedisperser


class SbDedisperser:
    def __init__(self, dd_rank, frequency_subbands):
        """Generator for the "subbanded dedispersion" cuda kernel.

        This emits the cuda kernels registered by the C++ class GpuSbDedispersionKernel
        (see include/pirate/DedispersionKernel.hpp for what the kernel computes, and
        for the constraints on its parameters).

        The kernel is the second dedispersion stage, writing the shape (ndm_out, M, ntime)
        subband array straight to global memory. It is float32-only, and assumes
        apply_input_residual_lags == input_is_ringbuf == True and nspec == 1, i.e. the same
        constraints as CoalescedDdKernel2. It also assumes (fs.pf_rank == dd.rank1), which
        is what makes the per-subband time lags free -- see the long docstring in
        Dedisperser.emit_subband_extraction().
        """

        assert isinstance(dd_rank, int)

        # float32 only. If a float16 variant is ever added, the dtype must appear in the
        # kernel name below AND in GpuSbDedispersionKernel::RegistryKey.
        self.dtype = dtype = Dtype('fp32')

        self.dd_rank = dd_rank
        self.frequency_subbands = frequency_subbands
        self.dt32 = dtype.simd32

        self.dd = Dedisperser(
            dtype = dtype,
            rank = dd_rank,
            apply_input_residual_lags = True,
            input_is_ringbuf = True,
            output_is_ringbuf = False,
            nspec = 1
        )

        assert self.dd.two_stage                                # equivalent to (dd_rank >= 3)
        assert frequency_subbands.pf_rank == self.dd.rank1      # see docstring above

        # From Dedisperser
        self.warps_per_threadblock = self.dd.warps_per_threadblock
        self.shmem_nbytes = self.dd.shmem_nbytes
        self.nt_per_segment = self.dd.nt_per_segment

        self.M = frequency_subbands.M

        # Typical kernel name: sbdd_r8_n5_n9_n7_n3_n1
        self.kernel_name = f'sbdd_r{dd_rank}_{frequency_subbands.fstr}'
        self.kernel_basename = self.kernel_name + '.cu'


    def emit_kernel(self, k):
        """Emits the complete kernel, including prologue, body, and registry registration."""

        assert isinstance(k, Kernel)

        # ---------------  Prologue  ---------------

        k.emit('#include "../../include/pirate/DedispersionKernel.hpp"')
        k.emit('#include "../../include/pirate/FrequencySubbands.hpp"')
        k.emit('#include "../../include/pirate/inlines.hpp"')
        k.emit()
        k.emit('using namespace std;')
        k.emit('using namespace ksgpu;')
        k.emit()
        k.emit('namespace pirate {')
        k.emit('#if 0')
        k.emit('}  // editor auto-indent')
        k.emit('#endif')
        k.emit()

        # ---------------  CUDA kernel  ---------------

        W = self.warps_per_threadblock
        B = utils.xdiv(16, W)   # threadblocks per SM (FIXME rethink?)

        k.emit(f'// Autogenerated by pirate_frb.cuda_generator')
        k.emit()
        k.emit(f'// Launch with {{ 32, {W} }} threads/warp')
        k.emit(f'// Launch with {{ Namb, Nbeams }} threadblocks')
        k.emit()

        k.emit(f'__global__ void __launch_bounds__({32*W}, {B})')
        k.emit(f'{self.kernel_name}(')
        k.emit(f'    void *grb_base_, uint *grb_quads_, long grb_frame0,   // dedisperser input (ring buffer)')
        k.emit(f'    float *sb_out_,                                       // subband output, see below')
        k.emit(f'    void *pstate_, int ntime,')
        k.emit(f'    ulong nt_cumul, bool is_downsampled_tree)')
        k.emit('{')
        k.emit(f'constexpr int M = {self.M};')
        k.emit()

        self.dd._emit_rsqrt2(k)
        self.dd._apply_inbuf_offsets(k)   # operates on grb* pointers, since input_is_ringbuf == True
        self._apply_sb_out_offsets(k)
        self.dd._init_srb(k)              # no-op if (self.dd.two_stage) is False

        # Save splice, for code to load pstate.
        # This code must be emitted near the end, after the ring buffer layout is finalized.
        # Note that pstate is managed by the dedispersion kernel.
        k_pstate = k.splice()

        k.emit(f'for (int itime = 0; itime < ntime; itime += {self.nt_per_segment}) {{')

        self.dd._load_input_data(k)
        self.dd._apply_input_residual_lags(k)

        # Dedisperser.emit_subband_extraction() emits the entire second stage, and yields one
        # (register name, multiplet index) pair per frequency subband multiplet. Note that it
        # must be fully consumed -- see its docstring, and the 'sbx_complete' assert below.

        for rname, m in self.dd.emit_subband_extraction(k, self.frequency_subbands):
            self._emit_store(k, rname, m)

        assert self.dd.sbx_complete

        self.dd._advance_rrb(k)
        self.dd._advance_srb(k)      # no-op if (self.dd.two_stage) is False
        self.dd._advance_inbuf(k)    # operates on grb* pointers, since input_is_ringbuf == True

        k.emit()
        k.emit('// Advance output pointer by one time segment.')
        k.emit(f'sb_out += {self.nt_per_segment};')

        k.emit('}   // outer time loop')

        # Now that the ring buffer has been finalized, we can sort out the pstate.
        self.dd._lay_out_pstate(k_pstate)    # initializes self.dd.pstate32_per_small_tree
        self.dd._load_pstate(k_pstate)
        self.dd._save_pstate(k)

        k.emit('}  // end of cuda kernel')


    def _apply_sb_out_offsets(self, k):
        """Emit per-block, per-warp and per-lane offsets for the 'sb_out' pointer."""

        k.emit(f'// SbDedisperser._apply_sb_out_offsets() starts here.')
        k.emit(f"// 'sb_out' is a fully contiguous shape (beams, ndm_out, M, ntime) array, where")
        k.emit(f'//   ndm_out = 2^(amb_rank + {self.dd.rank0}) = blockDim.y * gridDim.x.')
        k.emit(f'//')
        k.emit(f'// This is tricky because the block/warp indices correspond to bit-reversed DMs,')
        k.emit(f'// but the output array is not bit-reversed. (Same logic as')
        k.emit(f'// CoalescedDdKernel2._apply_pfout_offsets().)')
        k.emit()

        k.emit(f'float *sb_out = sb_out_;')
        k.emit()
        k.emit(f'// FIXME blockDim.y is a compile-time constant ({self.warps_per_threadblock}); could hardwire it.')
        k.emit(f'// FIXME could optimize out integer divisions')
        k.emit(f'uint ndm_out = blockDim.y * gridDim.x;')
        k.emit(f'uint lg2_ndm_out = __ffs(ndm_out) - 1;')
        k.emit(f'uint dm_out_brev = threadIdx.y * gridDim.x + blockIdx.x;   // dm is bit-reversed')
        k.emit(f'uint dm_out = __brev(dm_out_brev) >> (32 - lg2_ndm_out);')
        k.emit(f'long bd_out = (long(blockIdx.y) * ndm_out) + dm_out;       // (beam,dm), beam = blockIdx.y')
        k.emit()

        k.emit(f'// Apply per-block + per-warp offset:')
        k.emit(f'//   before: shape (beams, ndm_out, M, ntime), contiguous')
        k.emit(f'//   after:  shape (M, ntime), strides (ntime, 1)')
        k.emit(f'sb_out += bd_out * (long(M) * ntime);')
        k.emit()

        k.emit(f'// Apply per-lane offset. Afterwards, multiplet m at time (itime + laneId) is at')
        k.emit(f'// sb_out[m * m_stride], where "itime" is folded in by the "sb_out += {self.nt_per_segment}"')
        k.emit(f'// at the bottom of the time loop.')
        k.emit(f'sb_out += threadIdx.x;   // laneId')
        k.emit()

        k.emit(f'// Caller (GpuSbDedispersionKernel constructor) guarantees (M * ntime) < 2^31,')
        k.emit(f'// so 32-bit index arithmetic is safe here.')
        k.emit(f'int m_stride = ntime;')
        k.emit(f'// SbDedisperser._apply_sb_out_offsets() ends here.')
        k.emit()


    def _emit_store(self, k, rname, m):
        """Consumer of Dedisperser.emit_subband_extraction(): store one multiplet to global memory.

        Each store is a 32-bit instruction covering exactly one 128-byte cache line per warp.
        FIXME: a "wide" 64/128-bit store would be ~15% faster on an L40S (see the performance
        guidelines in notes/gpu_kernels.md), but would need a transpose on the time axis:
        lane j holds time (itime + j), so consecutive iterations of the time loop are 32
        samples apart, not adjacent.
        """

        fs = self.frequency_subbands
        n = fs.m_to_nd[m][0]                 # frequency subband index
        d = fs.m_to_nd[m][1]                 # fine-grained dm
        flo, fhi = fs.n_to_frange[n]         # coarse-freq range of the subband

        k.emit(f'sb_out[{m} * m_stride] = {rname};   // m={m}: subband n={n} (coarse freqs [{flo},{fhi})), fine dm={d}')


    def emit_registration(self, k):
        fs = self.frequency_subbands
        sb_counts = ', '.join(str(int(x)) for x in fs.subband_counts)
        m_to_n = ', '.join(str(int(n)) for n,d in fs.m_to_nd)
        m_to_d = ', '.join(str(int(d)) for n,d in fs.m_to_nd)
        n_to_flo = ', '.join(str(int(flo)) for flo,fhi in fs.n_to_frange)
        n_to_fhi = ', '.join(str(int(fhi)) for flo,fhi in fs.n_to_frange)

        k.emit('\n// Boilerplate to register the kernel when the library is loaded.')
        k.emit('namespace {')
        k.emit('struct register_hack {')
        k.emit('register_hack() {')
        k.emit('GpuSbDedispersionKernel::RegistryKey k;')
        k.emit(f'k.dd_rank = {self.dd_rank};')
        k.emit(f'k.subband_counts = {{ {sb_counts} }};')
        k.emit()
        k.emit('GpuSbDedispersionKernel::RegistryValue v;')
        k.emit(f'v.cuda_kernel = {self.kernel_name};')
        k.emit(f'v.shmem_nbytes = {self.shmem_nbytes};')
        k.emit(f'v.warps_per_threadblock = {self.warps_per_threadblock};')
        k.emit(f'v.pstate32_per_small_tree = {self.dd.pstate32_per_small_tree};')
        k.emit(f'v.nt_per_segment = {self.nt_per_segment};')
        k.emit()
        k.emit('// Checks consistency of python/C++ FrequencySubbands')
        k.emit(f'FrequencySubbands fs({{ {sb_counts} }});')
        k.emit(f'xassert_eq(fs.N, {fs.N});')
        k.emit(f'xassert_eq(fs.M, {fs.M});')
        k.emit(f'xassert(vec_equal(fs.m_to_n, {{ {m_to_n} }}));')
        k.emit(f'xassert(vec_equal(fs.m_to_d, {{ {m_to_d} }}));')
        k.emit(f'xassert(vec_equal(fs.n_to_flo, {{ {n_to_flo} }}));')
        k.emit(f'xassert(vec_equal(fs.n_to_fhi, {{ {n_to_fhi} }}));')
        k.emit()
        k.emit('bool debug = false;')
        k.emit('GpuSbDedispersionKernel::registry().add(k, v, debug);')
        k.emit('} // register_hack constructor')
        k.emit('}; // struct register_hack')
        k.emit('register_hack hack;')
        k.emit('} // anonymous namespace')
        k.emit()
        k.emit('}   // namespace pirate')


    @classmethod
    def write_kernel(cls, filename):
        """Called from 'autogenerate_kernel.py' in the toplevel pirate directory."""

        basename = os.path.basename(filename)

        # Typical basename: sbdd_r8_n5_n9_n7_n3_n1.cu
        m = re.fullmatch(r'sbdd_r(\d+)_((?:n\d+_)*n\d+)\.cu', basename)
        if not m:
            raise RuntimeError(f"Couldn't match filename '{filename}'")

        dd_rank = int(m.group(1))
        frequency_subbands = FrequencySubbands.from_fstr(m.group(2))

        sbdd_kernel = cls(dd_rank, frequency_subbands)

        if sbdd_kernel.kernel_basename != basename:
            raise RuntimeError("SbDedisperser.write_kernel(): internal error: expected "
                               + f" {sbdd_kernel.kernel_basename=} and {basename=} to be equal")

        k = Kernel()
        sbdd_kernel.emit_kernel(k)
        sbdd_kernel.emit_registration(k)

        k.write_file(filename)
